### ISSUE TITLE
USN journal access

### ISSUE THREAD

**Issue by mc0re** [microsoft/ProjectReunion#109]
Is USN journal access from UWP on the roadmap? I am generally only interested in the fact that a file has been changed since the last time I checked it, not what exact changes have been made.

**Comment by jonwis** [comment]
Can you give a few more details on the scope of what you'd like to know?  Changes to a directory? A file in the user's documents, pictures, or other libraries? An arbitrary file on the filesystem that the app has been given access to via something proposed in #45 ? How many files are you interested in at a time?

**Comment by mc0re** [comment]
It's a set of files in an arbitrary directory that the app got access to via `Windows.Storage.Pickers.FolderPicker`. I intended to validate the files were authentic on the first run by calculating hashes for them (a time consuming process), then on the next runs merely verify that they were not modified. We're talking in excess of 100 files.
In my case renaming of the files is acceptable (not considered to be a change).

**Comment by smaillet-ms** [comment]
You have a few options:

1.  Use the last modified time to check for modifications, much faster than hashing the file
2. Use [StorageFolder.TryGetChangeTracker](https://docs.microsoft.com/en-us/uwp/api/windows.storage.storagefolder.trygetchangetracker?view=winrt-19041) Which can retrieve a [StorageLibraryChangeTracker](https://docs.microsoft.com/en-us/uwp/api/Windows.Storage.StorageLibraryChangeTracker?view=winrt-19041) for the folder if the underlying File System supports one. This, leverages USN Journaling under the hood when available. NOTE: The name `StorageLibraryChangeTracker` is a bit misleading and historical, originally it was literally only for libraries, however when the TryGetChangeTracker method was introduced in 10.0.17134.0 the tracker was internally extended to support arbitrary folder locations.

**Comment by mc0re** [comment]
1. For what I know, changing the last-modified time is an easy job even for a less skilled user. I can't rely on this.

2. Correct me if I am wrong, but the fact that there is an [Enable](https://docs.microsoft.com/en-us/uwp/api/windows.storage.storagelibrarychangetracker.enable?view=winrt-19041#Windows_Storage_StorageLibraryChangeTracker_Enable) method suggests this feature only works while the program is running. Also, I don't see any sort of ID in [StorageLibraryChange](https://docs.microsoft.com/en-us/uwp/api/windows.storage.storagelibrarychange?view=winrt-19041), so I don't see a way to "remember", at what change the file is at present - to compare in the future.

**Comment by smaillet-ms** [comment]
Adam Wilson wrote [an article for MSDN](https://docs.microsoft.com/en-us/archive/msdn-magazine/2016/december/universal-windows-platform-file-system-monitoring-in-universal-windows-platform-apps) that goes over the details of using StorageLibraryChangeTracker.

**Comment by brflynn** [comment]
To answer the above questions @mc0re: 

You must call Enable() to set up registration for tracking changes for a given library or folder but the system will track and store updates even while you're not running. You can register for background task triggers to be notified on changes, otherwise it is an on demand polling approach to read them while the app is executing from the [ChangeReader](https://docs.microsoft.com/en-us/uwp/api/Windows.Storage.StorageLibraryChangeReader?view=winrt-19041)

There is no current way to identify a specific file or folder item by an identifier to bookkeep at this time other than the URL of the item which to your point, could change.

**Comment by jonwis** [comment]
@mc0re - once you get a chance to look through @brflynn 's content, please do let us know what other features you'd like to see in UWP USN / change-tracker functionality.

**Comment by mc0re** [comment]
Seems that the basic functionality is well covered, including buffer overruns. But it seems it only works for what Windows calls *libraries* - a predefined non-modifiable set of standard folders. So if my files are in, say, `D:\Videos\Here`, they can't be tracked.

**Comment by brflynn** [comment]
How are you accessing the API for D:\Videos\Here? Are you creating a StorageFolder object for that path and from that calling TryGetChangeTracker?

**Comment by mc0re** [comment]
I don't at the moment, I was investigating this possibility. Can one create a change tracker on an arbitrary directory?

**Comment by jonwis** [comment]
Yep, works great.  To start tracking:

* Use `FolderPicker.PickSingleFolderAsync` to get a `StorageFolder` from the user (or another means)
* Use `StorageFolder.TryGetChangeTracker` to get a change tracker and call `.Enable` on it
* Use `StorageApplicationPermissions.FutureAccessList.Add` to place the StorageFolder on the future access list and store the returned MRU token somewhere (I used `ApplicationData.Current.LocalSettings`)

To read changes:

* Fetch the MRU token from where you stored it
* Use `StorageApplicationPermissions.FutureAccessList.GetFolderAsync` to get the `StorageFolder` back
* Get that folder's change tracker again with `TryGetChangeTracker`
* Use `GetChangeReader` to retrieve the reader
* Walk through batches with `ReadBatchAsync` and `AcceptChangesAsync`

I put together [a little gist showing the technique](https://gist.github.com/jonwis/c61db33cc66016e6487e93acae356de3#file-changetrackersample-cs). (Not the greatest API sample, but it works.)

**Comment by duke7553** [comment]
@smaillet-ms 
> originally it was literally only for libraries, however when the TryGetChangeTracker method was introduced in 10.0.17134.0 the tracker was internally extended to support arbitrary folder locations.

Thanks for clarifying this. The name is slightly misleading, and I previously spent an entire week hooking up the Win32 ReadDirectoryChanges() in my UWP app. At least no one will make my mistake again! 😊
