### ISSUE TITLE
Question: How do I read the Proposal Tracking backlog/board?

### ISSUE THREAD

**Issue by riverar** [microsoft/ProjectReunion#131]
The [Proposal Tracking backlog/board](https://github.com/microsoft/ProjectReunion/projects/1) currently lists the following columns:

| Freezer | Back burner | Front burner | Code Complete, needs Docs/Samples |
|--|--|--|--|

Questions:
* How does the public _read_ this, exactly?
* What does each category mean? (As an owner of a culinary degree, I cook with both back and front burners.)
* How often are items in the freezer reconsidered?
* How long is each sprint?
* For [proposals that require OS work](https://github.com/microsoft/ProjectReunion/issues/126), will there be target release tracking? (e.g. Proposal X could be assigned to a GitHub milestone labeled _Windows 21H1_)

**Comment by m98770** [comment]
> The [Proposal Tracking backlog/board](https://github.com/microsoft/ProjectReunion/projects/1) currently lists the following columns:
> 
> Freezer	Back burner	Front burner	Code Complete, needs Docs/Samples
> Questions:
> 
> * How does the public _read_ this, exactly?
> * What does each category mean? (As an owner of a culinary degree, I cook with both back and front burners.)
> * How often are items in the freezer reconsidered?
> * How long is each sprint?
> * For [proposals that require OS work](https://github.com/microsoft/ProjectReunion/issues/126), will there be target release tracking? (e.g. Proposal X could be assigned to a GitHub milestone labeled _Windows 21H1_)

I believe  "Backlog,  ToDo , In Progress"   sounds much familiar and gives Public a clearer picture of time frames and priorities ,, which also serves the purpose of open sourcing development in the first place.

**Comment by mevey** [comment]
@riverar We've added a [Triage.md](https://github.com/microsoft/ProjectReunion/blob/master/docs/triage.md) to help answer your questions on the proposal process. We've updated the Project Board as well show the process better. Area owners will be placing their proposals under the right column over the next few days.

**Comment by riverar** [comment]
@mevey Perfect, thanks!
