### ISSUE TITLE
Validation in .NET

### ISSUE THREAD

**Issue by weitzhandler** [microsoft/ProjectReunion#142]
# Proposal: What happened to validation in the .NET

## Summary

Validation is one of the most critical building blocks in any application, server or client. Yet the .NET lacks an official and adequate solution to this matter.

DataAnnotations validation have been integrated with the .NET for a long time.
With the advancement of .NET it's been discovered that although decorating properties with inline attributes is a neat way to define validation, it comes with many limitations by the compiler (i.e. attributes may only take in constants, no generics etc.), as well as other downsides. DA has over time become completely abandoned and from what I read (will update when I find source), is no longer planned to be updated or be taken to the next level.

Additionally, UI frameworks (especially UWP and WinUI), don't have a conventional way of rendering the validation errors and exchanging validation data across app layers.

## Proposed solution

My suggestion hereby is for Microsoft and the .NET to thoroughly rethink the subject of validation and introduce a fully integrated validation framework (or officially adopt an existing), that is open for configuration, customization, and extensibility, and is engineered from scratch to cover as many scenarios as possible, for instance:

- Validation groups / rulesets (nested? inherited?)
- Dependency injection
- Unit test & mocking
- Entire graph validation
- Scalar value inline validation
- Static validation / argument validation `Check.IsNotNull` style
- Property and group human names and descriptions
- Error message and field it group name localization
- Inter-property or inter-entity validation
- Short circuiting on first error in group / entity in list / entity in graph / combination etc.
- Reuse validation in client & server entities, for example if client entities are generated by a tool (e.g. [ODataConnectedService](https://github.com/OData/ODataConnectedService)), to enable validation on UI saving a round-trip to server
- Validation process interception or customization
- Client side error tracking and notification (ViewModel)
- UI validation error rendering
- Respect `INotifyDataErrorInfo`, or have adapters to it

Cross posted [here](https://github.com/dotnet/runtime/issues/40157)

**Comment by mevey** [comment]
@weitzhandler You were right to cross post this. Let's track this proposal from the [.NET team's side ](https://github.com/dotnet/runtime/issues/40157) first.
