### ISSUE TITLE
StorageFolder.DisplayName doesn't return the localized name for a system folder

### ISSUE THREAD

**Issue by Jaiganeshkumaran** [microsoft/ProjectReunion#143]
Currently StorageFolder.DisplayName returns the actual name instead of the localized name for a system folder like the library folders or folders like Users. Instead it should return the localized name for these folders. Today to get the localized one has to use a full trust component which shouldn't be the case.

**Comment by Jaiganeshkumaran** [comment]
It works after changing the language list and restarting

**Comment by ptorr-msft** [comment]
@kevinguo305 , this is tracked by https://task.ms/28573841
