### ISSUE TITLE
[uwp] Bug: WebView doesn't allow interaction - only in release mode

### ISSUE THREAD

**Issue by jtorjo** [microsoft/ProjectReunion#144]
This is a really weird bug and it's simply been killing me.

I have a WebView that opens a web page from my website. In Debug mode, everything works perfectly. In Release, it doesn't allow any interaction with the user (the mouse is always "arrow", and clicking anywhere doesn't work).

I can't repro the bug in a simple standalone app -- it works there. This might even actually appear only on the deployed app only.

The only way I can show you what I mean is this: it's the app here - https://studiocinematic.com - click "About" in the toolbar, and you'll see a web browser control which doesn't allow interaction.

The layout of the app is highly complex. Once again, this works like a charm in Debug mode.

My use case is this: I want to have a feedback pane that would open a web page where the user would interact with us. When I open it in a WebView control the user can't do anything in that feedback page.

**Is this a known issue? Is there any workaround?**

I'm tired of trying pretty much anything, since to test an idea is pretty much 5-15 minutes of compile + deploy time (sometimes stupid compile errors that go away when I do a rebuild), and then back to square one.

**Comment by michael-hawker** [comment]
@jtorjo don't think you'll get much traction in this repo for this questions. I know all work on WebView is going into WebView2 currently, their feedback [repo is here](https://github.com/MicrosoftEdge/WebViewFeedback), but I'm not sure what they're doing with WebView feedback. The [WinUI repo](https://aka.ms/winuigithub) owns WebView2 in UWP for WinUI 3 though.

@adambarlow suggestions on routing this question?

**Comment by codendone** [comment]
@jtorjo It looks like the CommandBar gets disabled when clicking the About button.  Does the issue happen if you leave the CommandBar enabled?

There is a full-window Rectangle at the root of the CommandBar's visual tree which is blocking the input.  I don't yet know why/how, especially since it seems to have IsHitTestVisible=false.  I see some weird state on the CommandBar, which I speculate might be due to the CommandBar getting disabled during the button click and preventing/confusing some cleanup.

**Comment by jtorjo** [comment]
@codendone Thanks for getting back to me! I hate the CommandBar  - come to think of it, I have no idea why I used it. I had an insanely hard time using it.

So, I'll try using a grid and see if the same issue happens. Will get back to you!

**Comment by jtorjo** [comment]
@codendone Many many many thanks! I would have never thought of the CommandBar being the culprit!

May I ask what tool you used to figure this all out? I'm pretty sure it would be helpful for most of us :)
