### ISSUE TITLE
Question: Classic WinAPI apps with WinRT engine?

### ISSUE THREAD

**Issue by AzAgarampur** [microsoft/ProjectReunion#15]
Project Reunion seems like a big step in the right direction! I have a few questions:

- If Project Reunion is trying to merge UWP application with the classic WinAPI programs, will decoupling from the OS make the WinAPI programs loose some of their native functionality?
- Does the entire codebase have to be updated? Example: If I create a button control from `comctl32.dll` will I have a UWP button control instead? Or will I still have my classic GDI button?
- I'm assuming that the merged UWP functionality will be the APIs that only Windows desktop supports?

I hope someone understands my questions, and I'm eager to use Project Reunion when the time comes.

**Comment by jonwis** [comment]
Can you tell us more about the categories of Windows/Win32 APIs you're looking forward to use?

## Will Reunion APIs lose functionality?

We're not _removing_ any APIs from Windows.  Anything your app can do on any edition will keep working.  Reunion just makes that functionality more accessible to more apps.

Some Win32 APIs will come to Reunion with altered or limited functionality.  For instance, UWP (AppContainer) apps _probably_ shouldn't be able to add new users, create new sessions, send (or receive) window messages to other applications, directly open & modify the filesystem, etc.  I can certainly see how some of this functionality _could_ be useful, from an "apps have least privileges, but can get more privileges when approved by the user" point of view.  Reunion would let us add those powers to apps - with user approval - the same way you could have done with a Full Trust component.

## Does the entire codebase have to be updated?

Reunion's goal is incremental adoption.  We would aim to let you keep your button control and help you host your control either in a content frame inside another window, or inside a regular top-level `HWND`.

## Merged UWP functionality

Similar to the `WINAPI_FAMILY_APP` SDK partitioning system, Reunion will eventually provide a subset of Win32 APIs plus a set of Reunion-specific new functionality.  These APIs are those that Reunion can help you run _everywhere_ (Desktop, HoloLens, Xbox, Surface).  As above there will be some "Classic Desktop" APIs that are not brought to Reunion, but you can still use them by "reaching through" Reunion's partition out to the Windows Kit.

**Comment by AzAgarampur** [comment]
@jonwis Thanks a lot for response, it did answer the questions I asked.

I am creating apps for Windows desktop devices. I am interested in Project Reunion because I want my apps to have modern UI elements and fully use the Windows 10 experiences (notifications, lock screen icon, etc).

I aim for my programs to be fast and responsive. One of my programs is a multi threaded, intensive file I/O encryption and backup program. I was not going to use UWP because it was advised not to. Currently, for my interface I'm using the XAML Hosting API with C++/WinRT. For the actual buisness logic, I use the direct WinAPI functions like `ReadDirectoryChangesW`, `BcryptEncrypt`, `VirtualLock`, etc. This is why I was asking if Project Reunion would prevent my app from directly using those apis.

**Comment by jonwis** [comment]
You should be able to get what you want through a Desktop Bridge application, which supports those extensions, runs as full trust, and (thanks to WinUI3) will be able to use modern UX.  Project Reunion might help in a few places getting access to even more experiences as we build out our plans.  You'll certainly be able to call those APIs directly.

(Also, you might look into the [USN Journal](https://docs.microsoft.com/en-gb/windows/win32/fileio/change-journals) as a way to optimize your backup scans, even when your app isn't actively listening for directory changes.)

However, If you did want to use UWP, you might investigate the [BroadFilesystemAccess](https://docs.microsoft.com/en-us/windows/uwp/files/file-access-permissions) capability and the [...FromApp](https://docs.microsoft.com/en-us/previous-versions/windows/desktop/legacy/mt846585(v=vs.85)) category of APIs.  Another answer is to use a hybrid app, where your UX and experience components are UWP and you use a [Full Trust Component](https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/desktop-to-uwp-extend) for the business logic.
