### ISSUE TITLE
App crash when using configuration name different from Debug or Release

### ISSUE THREAD

**Issue by romulo-rosinha** [microsoft/ProjectReunion#164]
**Describe the bug**
Not sure this is a bug or just me doing something wrong, could not find documentation regarding this, but I get the following app crash when using a Configuration name different from Debug or Release:

> Faulting application name: App1.exe, version: 1.0.0.0, time stamp: 0x5bb69bfe
> Faulting module name: Windows.UI.Xaml.dll, version: 10.0.17763.404, time stamp: 0x5c3c199a
> Exception code: 0xc000027b
> Fault offset: 0x008dc0f1
> Faulting process id: 0x28bc
> Faulting application start time: 0x01d4ff7fbe41260f
> Faulting application path: C:\xxxxx\WinUIConfig\App1\bin\x86\Debug1\AppX\App1.exe
> Faulting module path: C:\Windows\System32\Windows.UI.Xaml.dll
> Report Id: d999fdc1-4bb6-46d0-9e39-8aaf0168a949
> Faulting package full name: 797cbdfa-8cfb-4c0f-9e19-79943324e67e_1.0.0.0_x86__wgcfbsqfkre0m
> Faulting package-relative application ID: App

**Steps to reproduce the bug**
Open attached project [WinUIConfig.zip](https://github.com/Microsoft/microsoft-ui-xaml/files/3132571/WinUIConfig.zip) and try to run the app using configuration __Debug1__ 
and platform __x86__. __Debug1__ is the same __Debug__ default configuration with a different name. The app should crash almost immediately.

Here is debug output from when the app crashes:

> Exception thrown at 0x75E8C6F2 in App1.exe: Microsoft C++ exception: EETypeLoadException at memory location 0x06C7D19C.
'App1.exe' (Win32): Loaded 'C:\src\WinUIConfig\App1\bin\x86\Debug1\AppX\System.Runtime.WindowsRuntime.dll'. 
'App1.exe' (Win32): Unloaded 'C:\src\WinUIConfig\App1\bin\x86\Debug1\AppX\System.Runtime.WindowsRuntime.dll'
'App1.exe' (Win32): Loaded 'C:\src\WinUIConfig\App1\bin\x86\Debug1\AppX\System.Runtime.WindowsRuntime.dll'. 
'App1.exe' (CoreCLR: CoreCLR_UWP_Domain): Loaded 'C:\src\WinUIConfig\App1\bin\x86\Debug1\AppX\System.Runtime.WindowsRuntime.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Exception thrown at 0x75E8C6F2 in App1.exe: Microsoft C++ exception: [rethrow] at memory location 0x00000000.
Exception thrown: 'System.TypeLoadException' in App1.exe
Exception thrown at 0x75E8C6F2 (KernelBase.dll) in App1.exe: WinRT originate error - 0x80131522 : 'System.TypeLoadException: Could not find Windows Runtime type 'Microsoft.UI.Xaml.Controls.XamlControlsResources'.
   at App1.App1_XamlTypeInfo.XamlTypeInfoProvider.InitTypeTables()
   at App1.App1_XamlTypeInfo.XamlTypeInfoProvider.LookupTypeIndexByName(String typeName)
   at App1.App1_XamlTypeInfo.XamlTypeInfoProvider.GetXamlTypeByName(String typeName)
   at App1.App1_XamlTypeInfo.XamlMetaDataProvider.GetXamlType(String fullName)
   at App1.App.GetXamlType(String fullName)'.
'App1.exe' (Win32): Loaded 'C:\Windows\SysWOW64\userenv.dll'. Cannot find or open the PDB file.
'App1.exe' (Win32): Loaded 'C:\Windows\SysWOW64\profext.dll'. Cannot find or open the PDB file.
'App1.exe' (Win32): Unloaded 'C:\Windows\SysWOW64\profext.dll'
'App1.exe' (Win32): Loaded 'C:\Windows\SysWOW64\profext.dll'. Cannot find or open the PDB file.
Exception thrown at 0x75E8C6F2 (KernelBase.dll) in App1.exe: WinRT originate error - 0x802B000A : 'Cannot deserialize XBF metadata type list as 'XamlControlsResources' was not found in namespace 'Microsoft.UI.Xaml.Controls'. [Line: 0 Position: 0]'.
Windows.UI.Xaml.dll!046F1727: (caller: 0438AD7D) Exception(1) tid(3470) 80004005 Unspecified error
Exception thrown at 0x75E8C6F2 in App1.exe: Microsoft C++ exception: wil::ResultException at memory location 0x06C7DEB0.
Exception thrown at 0x75E8C6F2 in App1.exe: Microsoft C++ exception: [rethrow] at memory location 0x00000000.
Windows.UI.Xaml.dll!046F243C: (caller: 0451975E) ReturnHr(1) tid(3470) 80004005 Unspecified error
    Msg:[Windows.UI.Xaml.dll!046F1727: (caller: 0438AD7D) Exception(1) tid(3470) 80004005 Unspecified error
] 
'App1.exe' (Win32): Loaded 'C:\src\WinUIConfig\App1\bin\x86\Debug1\AppX\System.Diagnostics.Debug.dll'. 
'App1.exe' (Win32): Unloaded 'C:\src\WinUIConfig\App1\bin\x86\Debug1\AppX\System.Diagnostics.Debug.dll'
'App1.exe' (Win32): Loaded 'C:\src\WinUIConfig\App1\bin\x86\Debug1\AppX\System.Diagnostics.Debug.dll'. 
'App1.exe' (CoreCLR: CoreCLR_UWP_Domain): Loaded 'C:\src\WinUIConfig\App1\bin\x86\Debug1\AppX\System.Diagnostics.Debug.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.

App runs fine if using configuration __Debug__.

**Expected behavior**
App does not crash.

**Version Info**
NuGet package version: Microsoft.UI.Xaml 2.1.190405004.2

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)                   |   |
| October 2018 Update (17763)   | Yes   |
| April 2018 Update (17134)        |    |
| Fall Creators Update (16299)     |    |
| Creators Update (15063)           |    |
| Anniversary Update (14393)      |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes   |
| Mobile                   |   |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Additional Context**
Not sure it matters, but I noticed the generated file __XamlTypeInfo.g.cs__ is much larger when using __Debug1__ (38KB) than when using __Debug__ (6KB) .

**Comment by StephenLPeters** [comment]
I think I agree that this is not a Winui issue given the fix proposed by RichPrism.  Although @jevansaks called this a bug in https://github.com/microsoft/microsoft-ui-xaml/issues/1406. I've transferred it to project Reunion which I think is a better home.

**Comment by stevewri** [comment]
So this sounds like a tooling issue wrt to how the configuration switch and package dependencies are handled (see Rich's workaround). Reunion isn't the right home, either, but we'll hold onto it until we get the right contact and area.

**Comment by andrewleader** [comment]
Thanks for reporting this! This is actually a Windows platform bug and not a Project Reunion bug, so I've filed a bug with the platform team (internal bug #31583074) and asked them to follow up here with any updates.

I'll close this thread since this isn't an active issue with Project Reunion itself, but I appreciate you submitting this detailed report!

If you'd like to track the status of the bug, you could submit this bug report through Feedback Hub and then share your link to your feedback so that I can link it up with the platform bug I created.
