### ISSUE TITLE
take a look at how uwp apps handle their state with suspension

### ISSUE THREAD

**Issue by Poopooracoocoo** [microsoft/ProjectReunion#170]
# Proposal: take a look at how uwp apps handle their state with suspension

## Summary

>this sometimes also happens to Settings. it could be a uwp wide problem. i tend to leave the bluetooth page open so i can quickly switch from listening on my phone to my laptop.

https://github.com/microsoft/Xaml-Controls-Gallery/issues/537
## Rationale

* basic usability lol

## Scope

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow developers to accomplish W | Must |
| This proposal will allow end users to accomplish X | Should |
| This proposal will allow developers to accomplish Y | Could |
| This proposal will allow end users to accomplish Z | Won't |

**Comment by Jaiganeshkumaran** [comment]
@Poopooracoocoo Suspend/Resume is a good thing because it reduces overall system resource usage so the running app can do more than wasting resources for a minimized app.

**Comment by Poopooracoocoo** [comment]
it just has issues with state management. i didn't comment on suspension as a whole but since you brought it up i'll just mention that MS replaced their UWP Edge with Chromium and replaced their UWP Skype with Electron.

**Comment by Jaiganeshkumaran** [comment]
@Poopooracoocoo Apps get atleast 5 minutes to save everything before it gets suspended. Modify App.OnSuspending event to save your data.

**Comment by stevewri** [comment]
Looking at the XAML controls thread, is this basically a bug in the settings app not saving its state properly when the settings app is suspended?

**Comment by Poopooracoocoo** [comment]
@stevewri I've also seen this in XAML Controls Gallery (as per the linked issue) but since I don't use any UWP apps for a long time or everyday (other than Settings), I don't know any more details.

**Comment by maxkatz6** [comment]
I think this issue should be updated to be more specific.
Or even closed, because it seems like an issue in specific applications, but not in UWP itself.
https://github.com/microsoft/Xaml-Controls-Gallery/issues/537#issuecomment-686786994

**Comment by maxkatz6** [comment]
By the way, there is more specific issue
https://github.com/microsoft/ProjectReunion/issues/111#issuecomment-662541683

**Comment by Poopooracoocoo** [comment]
thanks max! i'm going to let someone at ms close this in hopes that they'll fix this in their own apps like Settings.

**Comment by stevewri** [comment]
Closing; the settings app issue is tracked by microsoft/Xaml-Controls-Gallery#537 and the general Reunion lifecycle proposal by #111 .

**Comment by Poopooracoocoo** [comment]
@stevewri huh? the settings app is not the xaml controls gallery app.

**Comment by Poopooracoocoo** [comment]
uh @stevewri you never replied? this ain't fixed in the settings app now, is it??

**Comment by maxkatz6** [comment]
@Poopooracoocoo in win11 it seems to be fixed
