### ISSUE TITLE
Question: Using WinUI 3.0 on XboxGameBar (Windows.UI.Xaml and Microsoft.UI.Xaml converting)

### ISSUE THREAD

**Issue by visionarylab** [microsoft/ProjectReunion#181]
Hi all, I have a silly question. How and the workaround for following:

WinUI3 using Microsoft.UI.Xaml.Controls.Frame

`Windows.UI.Xaml.Controls.Frame rootFrame = new Microsoft.UI.Xaml.Controls.Frame Frame();`

XboxGameBarWidget needed Windows.UI.Xaml.Controls.Frame
```
                        widget1 = new XboxGameBarWidget(
                            widgetArgs,
                            Window.Current.CoreWindow,
                            rootFrame);
                        rootFrame.Navigate(typeof(Widget1), widget1);
```

**Comment by jeffstall** [comment]
Hi, WinUI 3.0 isn't supported with GameBar at this time. There is no work-around. We are tracking this feature request.

**Comment by odyright** [comment]
That's a typo issue; you can't directly convert from `Windows` to `Microsoft` with operand like "**=**".
`Windows.UI.Xaml.Controls.Frame rootFrame` shoould be `Microsoft.UI.Xaml.Controls.Frame rootFrame`
so
`Microsoft.UI.Xaml.Controls.Frame rootFrame = new Microsoft.UI.Xaml.Controls.Frame Frame();`

**Comment by odyright** [comment]
That's a typo issue; you can't directly convert from `Windows` to `Microsoft` with operand like "**=**".
`Windows.UI.Xaml.Controls.Frame rootFrame` should be `Microsoft.UI.Xaml.Controls.Frame rootFrame`
so
`Microsoft.UI.Xaml.Controls.Frame rootFrame = new Microsoft.UI.Xaml.Controls.Frame Frame();`
