### ISSUE TITLE
Proposal: Add labels like [UWP] and [Win32] for easier issue grouping

### ISSUE THREAD

**Issue by Felix-Dev** [microsoft/ProjectReunion#19]
"Project Reunion" targets both UWP and Win32 and we are already seeing issues for both app types. As such, for easier grouping and filtering of issues, it could be useful to have labels like "UWP" and "Win32" to clearly indicate which proposal/question is targeting which app type.

**Comment by mdtauk** [comment]
What about issues that are aimed at both platforms?  Include both labels?

**Comment by Felix-Dev** [comment]
@mdtauk Would make sense to me, yes.

**Comment by jonwis** [comment]
Ideally, Reunion targets both Win32 and UWP.  Anything we add should support both - Reunion aims to be identity, packaging, isolation, and lifecycle transparent.

Can you give an example (maybe using the current set of issues) of which tags you'd put on items, and why?

**Comment by mdtauk** [comment]
> Ideally, Reunion targets both Win32 and UWP. Anything we add should support both - Reunion aims to be identity, packaging, isolation, and lifecycle transparent.
> 
> Can you give an example (maybe using the current set of issues) of which tags you'd put on items, and why?

In the WinUI repo there is a discussion about different types used for things like Rect and Point - so if one API behaves oddly in either Win32 or UWP - then the issue would be asking for a fix for one over the other.

**Comment by Felix-Dev** [comment]
@jonwis I was hoping "ProjectReunion" would also cover APIs like AppWindow V1/V2 for UWP, to provide a similar powerful experience like Win32 Windowing APIs. (Not all win32 features might be brought over due to the sandbox.)

The File I/O issue https://github.com/microsoft/ProjectReunion/issues/8 for example is really just relevant for UWP as it "already works" for Win32 apps.
The Startup issue https://github.com/microsoft/ProjectReunion/issues/10 for example seems mainly aimed at *unpackaged win32 apps* and as such would probably not be relevant for UWP.

As such, it seems reasonable to me differentiate between UWP and Win32 issues here as I would imagie many (future) issues will be about bringing APIs from one side to the other (Win32 to UWP or vice-versa).

**Comment by jonwis** [comment]
Can you add a specific "feature request" for "AppWindow-like Win32 window positioning support"? Helping `HWND` based apps go full-screen or picture-in-picture or "move to the left monitor" and others are definitely useful bits of functionality for even non-UWP apps. 

Thanks for the suggestions - we'll noodle on ways to organize "make X thing available to Y" in tags.

**Comment by jonwis** [comment]
Thanks, I added the UWP (support for UWP apps) and Win32 (support for Win32 packaged and unpackaged) apps labels.
