### ISSUE TITLE
Question: How to deploy UWP app

### ISSUE THREAD

**Issue by Alkanores** [microsoft/ProjectReunion#194]
I created my UWP app package, but ms-appinstaller shows me error when I try to install.

![image](https://user-images.githubusercontent.com/49155506/93513679-e12f3280-f92e-11ea-8003-94ff50e0862a.png)

in english this be something like this:
"An error occurred while parsing the application package."

ms-appinstaller file: https://pastebin.com/GnutbTuc

If I run .msix, then it install my app successfully.

![image](https://user-images.githubusercontent.com/49155506/93514031-5ef33e00-f92f-11ea-8578-49a9ad440816.png)

**Comment by stevewri** [comment]
Is this specific to building with Reunion headers and libs? If not, this question should go through the Feedback Hub.

**Comment by Alkanores** [comment]
> Is this specific to building with Reunion headers and libs? If not, this question should go through the Feedback Hub.

Can you give me link on feedback hub?

**Comment by stevewri** [comment]
Here's a link to the general developer Q&A site: https://docs.microsoft.com/answers/index.html

**Comment by Alkanores** [comment]
> Here's a link to the general developer Q&A site: https://docs.microsoft.com/answers/index.html

Thanks. Closing issue.

**Comment by Alkanores** [comment]
https://docs.microsoft.com/en-us/answers/questions/98699/cannot-deploy-uwp-app-with-ms-appinstaller.html

(for those who in the future will look for an answer to this question)

**Comment by Alkanores** [comment]
@stevewri does uwp has a repository on github?

**Comment by maxkatz6** [comment]
@Alkanores which "UWP" repo do you need?
If you need UI layer - there is Microsoft.UI.Xaml repo. UWP app container specific code isn't open sourced, I believe. 

For ms-appinstaller you probably need something MSIX related.

**Comment by hansmbakker** [comment]
> https://docs.microsoft.com/en-us/answers/questions/98699/cannot-deploy-uwp-app-with-ms-appinstaller.html

@Alkanores that link seems dead..

**Comment by Alkanores** [comment]
> > https://docs.microsoft.com/en-us/answers/questions/98699/cannot-deploy-uwp-app-with-ms-appinstaller.html
> 
> @Alkanores that link seems dead..

![image](https://user-images.githubusercontent.com/49155506/93721289-b398f200-fb97-11ea-82a2-20e421158222.png)
this is the reason, why I write comment again.

**Comment by Alkanores** [comment]
> @Alkanores which "UWP" repo do you need?
> If you need UI layer - there is Microsoft.UI.Xaml repo. UWP app container specific code isn't open sourced, I believe.
> 
> For ms-appinstaller you probably need something MSIX related.

thanks
