### ISSUE TITLE
Question: Windows 10X Sandboxing & Win32 Project Reunion API:s

### ISSUE THREAD

**Issue by JensNordenbro** [microsoft/ProjectReunion#200]
Hi!

What does Project Reunion mean for the sandboxing tech in Windows 10X? 
Today when running the first win32-app on 10X a penalty exist, loading a containerized "legacy" environment. 
Will an app using win32-api:s from Project Reunion not need this approach or is this completely orthogonal?

**Comment by ptorr-msft** [comment]
Short answer: it's orthogonal. 

Win32 app -> Win32 Container.  
AppContainer app -> AppContainer (Native Container).

Reunion supports both Win32 and AppContainer (UWP) apps.

**Comment by JensNordenbro** [comment]
So Reunion is only about usage of former uwp/winrt apis in win32 apps? It will not restructure win32 in any way other than allowing for this?!  This means no common foundation?!

**Comment by Jaiganeshkumaran** [comment]
@JensNordenbro What I think is Project Reunion will allow more WinRT APIs for Win32 apps and make the usage consistent without interop methods. Basically, you can turn an old app into a modern WinRT app or start with a new Win32 app and get new modern features.

**Comment by JensNordenbro** [comment]
Sure, but looking at the illustrations also win32 seems to be lifted somehow but judging from the answers in this thread, that seems to be me just reading in too much into the pictures. 
Basically, I I thought/hoped also win32 would be based on a common ground together with WinRT with the same security policies / container security granulation etc  
Now it is just seems to be one more attempt at tempting devs to use tech developed for WinRT.

**Comment by ptorr-msft** [comment]
I'm not sure what you are looking for.

> I thought/hoped also win32 would be based on a common ground together with WinRT with the same security policies / container security granulation etc. 

Yes, this is the goal or Reunion... to be clear, there has always been a common ground - the NT kernel and much of the Win32 subsystem - but "UWP" and "Win32" apps diverged at the UI layer / app lifecycle / containment level.

> Now it is just seems to be one more attempt at tempting devs to use tech developed for WinRT.

This sounds like what you hoped for though - the containment technology developed for UWP ("WinRT") will be available for Win32 apps, as will all the new features developed since Windows 8 that had previously only been available to "UWP" apps (like WinUI).

**Comment by JensNordenbro** [comment]
So will I be able to lock down a win32 app using same mechaniams as for winrt https://docs.microsoft.com/en-us/previous-versions/windows/apps/hh967755(v=win.10)?redirectedfrom=MSDN ?

**Comment by ptorr-msft** [comment]
That is the kind of thing Reunion is aiming for. But it might take a while.

**Comment by JensNordenbro** [comment]
Ok Great!!! Then the pictures makes sense.

Any chanse that win32 will be layered on top of winrt fully and as a result building a win32 application in self contained mode  can bring all win32 dependencies with the application just as ..Net core allows to bring the runtime and dependencies along with the application?

**Comment by ptorr-msft** [comment]
In theory, yes. It's not clear exactly how it will be delivered yet though.

**Comment by JensNordenbro** [comment]
Nice!

**Comment by ecovio1** [comment]
@JensNordenbro 
> Any chanse that win32 will be layered on top of winrt fully and as a result building a win32 application in self contained mode can bring all win32 dependencies with the application just as ..Net core allows to bring the runtime and dependencies along with the application? (maybe tricky from a licensing standpoint)

winRT apis  will not even exist without win32 apis/subsystem.  
winRT apis are not built on top of kernel services. 
**winRT apis are built on top of win32 apis.**   
**_under the hood  all winRT apis are, win32 apis exposed through COMv2 interface._**  
technically all winRT apis are COMv2 apis.
