### ISSUE TITLE
"Project Reunion App Getting Started" documentation needed

### ISSUE THREAD

**Issue by rohanp-msft** [microsoft/ProjectReunion#212]
# Proposal: "Project Reunion App Getting Started" documentation needed

## Summary
Should include a section on App dev prerequisites for Project Reunion. **Other sections to be determined.**

## Important Notes
For the App dev prerequisites for Project Reunion section, the prerequisites are:
1. Windows SDK.
2. A supported compiler and build toolchain that supports NuGet.

**Comment by stevewri** [comment]
Elliot - does your sample work cover this?

**Comment by andrewleader** [comment]
Kevin published "development environment" docs for this: https://docs.microsoft.com/en-us/windows/apps/project-reunion/#set-up-your-development-environment
