### ISSUE TITLE
[Bug + feature proposal] Make MediaPlaybackList work properly with IBasicVideoEffect interface

### ISSUE THREAD

**Issue by mcosmin222** [microsoft/ProjectReunion#223]
# Proposal: Make MediaPlaybackList work properly with IBasicVideoEffect interface 

## Summary
Given that you have a class implementing IBasicVideoEffect
And you attach it to a MediaPlayer object 
and then you set a MediaPlaybackList as source to the MediaPlayer
When you start playing
Items in the MediaPlaybackList get **randomly** skipped, complaining about

> A valid type has not been set for this stream or a stream that it depends on. (Exception from HRESULT: 0xC00D6D60)

Particular attention needs to be given to the word "randomly" there. It sometimes can play many items without any issue, sometimes it fails instantly. You need a bit of patience to get this reproduced.

You can use the following repository to get setup:
https://github.com/mcosmin222/MediaPlaybackListVideoEffects

Open the SLN, build and run the thing, select a few video files using the file picker, preferably some with more than 10 seconds of video, then let it do its thing. It will create a MediaPlaybackList with 1000 items from the files you select. And then simply wait for it.

![image](https://user-images.githubusercontent.com/9284164/95079673-a1828c00-071f-11eb-86ce-caee2ddc1dd2.png)

This is an extremely difficult bug to reproduce. My suspicion is that it is some sort of threading error, the effect is not always applied at the right time. The bug seems to appear when switching the active playback item. It doesn't reproduce during mid playback. The sample will seek to a few seconds before the end of the file so you don't need to wait the entire file out.

## Rationale

* MediaPlaybackList should work fine with IBasicVideoEffect

## Scope

| Capability | Priority |
| :---------- | :------- |
| A prepopulated MediaPlaybackList should work fine with IBasicVideoEffect | Must |
| It should be possible to add and remove items from a MediaPlaybackList without causing issues, when using a IBasicVideoEffect | Must |

## Important Notes

While Microsoft suggests using Frame Server Mode to implement video effects, this will prevent the MediaPlayer from working as a casting source. MediaPlaybackList provides the best feature set: both gapless playback and support for casting. Other solutions to obtain video effects either have performance issues, or sacrifice either gapless playback or casting.

When applying the IBasicVideoEffect to a MediaPlayer with a different source, like a single MediaPlaybackItem, it will work properly.

Relevant APIs

[IBasicVideoEffect](https://docs.microsoft.com/en-us/uwp/api/windows.media.effects.ibasicvideoeffect?view=winrt-19041)

[MediaPlayer](https://docs.microsoft.com/en-us/uwp/api/windows.media.playback.mediaplayer?view=winrt-19041)

[MediaPlaybackList](https://docs.microsoft.com/en-us/uwp/api/windows.media.playback.mediaplaybacklist?view=winrt-19041)

[MediaPlaybackItem](https://docs.microsoft.com/en-us/uwp/api/windows.media.playback.mediaplaybackitem?view=winrt-19041)

This bug has first been reported in 2019

[MSDN forums, now deprecated](https://social.msdn.microsoft.com/Forums/en-US/6a8b41ee-71ad-4e83-8e76-f25ba8de327a/uwp-any-special-considerations-when-using-ibasicvideoeffect-with-mediaplaybacklist?forum=wpdevelop)

Forum support managed to reproduce the issue. The fix is long overdue.

## Open Questions

None as of yet.

**Comment by stevewri** [comment]
This isn't Reunion per se, but we'll see if we can find the API owners and reroute this appropriately.

**Comment by andrewleader** [comment]
Thanks for reporting this! This is actually a Windows platform bug and not a Project Reunion bug, so I've filed a bug with the platform team (internal bug #31584220) and asked them to follow up here with any updates.

I'll close this thread since this isn't an active issue with Project Reunion itself, but I appreciate you submitting this detailed report!
