### ISSUE TITLE
Question: What kinds of APIs are out of scope for Reunion?

### ISSUE THREAD

**Issue by mdtauk** [microsoft/ProjectReunion#23]
I know these are early days for this project, but it may be helpful if there were some kind of guidance as to what _asks_ are beyond the scope or ability for this project.

One example has been with WinUI.  There were certain asks around Windowing APIs and Models, which were OS dependant, and not within the control of the WinUI team/project.

If there were no bounds to this project, you could theoretically reduce Windows to a backend kernel and driver model - and everything from Shell to Apps being moved to this repo and open-sourced.

**Comment by Felix-Dev** [comment]
To add to @mdtauk, here are example issues of mine I created on the WinUI repo:

UWP: https://github.com/microsoft/microsoft-ui-xaml/issues/1888
Win32: https://github.com/microsoft/microsoft-ui-xaml/issues/1919, https://github.com/microsoft/microsoft-ui-xaml/issues/2005, https://github.com/microsoft/microsoft-ui-xaml/issues/2008

Based on my current understanding of this project, it appears to me these issues above would be a great fit for this repository.

I'm not sure about an issue like https://github.com/microsoft/microsoft-ui-xaml/issues/2186 (which targets UWP but for the "reunion's sake" could also be expanded to Win32).

**Comment by stevewri** [comment]
Reunion certainly will be looking at Windowing APIs and models. Are there other examples of APIs you think might be outside the scope?

**Comment by weitzhandler** [comment]
@stevewri lemme try. here are some:

- [Cross platform](https://bit.ly/32bGoAI) .NET UI.
- General validation in .NET. Right now, there is no proper validation in the entire .NET. DA has been officially abandoned, and FV not officially adopted. Plus FV has no support for Windows UIs. Validation is one of the key elements in any app, yet the .NET lacks any official or embraced end-to-end solution for it, that works in ASP.NET Core as it does in UWP or XAML.
- Server-client entity exchange. OData has been making nice progress lately, but it's still far from what RIA Services used to be. In  OData, you cannot share validation attributes, interface implementations, generic types, or XML documentation across the wire.

**Comment by mevey** [comment]
Project Reunion can't change fundamental Windows behaviors like processes, threads, memory management, handles, tokens, security boundaries, networking, sockets, shell windowing behaviors, user identity, etc. What we can change are behaviors that are specific to your apps. The FAQ covers what some of these areas are: https://github.com/microsoft/ProjectReunion/blob/master/docs/faq.md#what-kinds-of-apis-are-out-of-scope
@weitzhandler I'd advice that you create questions or proposals regarding the .NET  and OData scenarios.
