### ISSUE TITLE
Question: If this possible, to use functions from win32 API (UWP)

### ISSUE THREAD

**Issue by Alkanores** [microsoft/ProjectReunion#234]
I want to make UWP launcher and I need to create anticheat for this game. How can I include my anticheat win32 .dll and get info (if game started, if user cheater, etc.)

Thanks.

**Comment by Jaiganeshkumaran** [comment]
@Alkanores It depends on what API you call. Here's the list of Win32 API functions that can be accessed inside AppContainer UWP sandbox. If you are loading dynamically, you may need to use LoadPackagedLibrary instead of plain LoadLibrary and you should put in inside your package.

**Comment by Alkanores** [comment]
Thanks!
