### ISSUE TITLE
Question: Will there be templates for vb?

### ISSUE THREAD

**Issue by Padanian** [microsoft/ProjectReunion#24]
Mentioning Rust in the README ad seeing no mention to vb, which is still the 6th most used language in the world, is outraging.
Will there be support for vb?

**Comment by jonwis** [comment]
For which variant of VB are you looking for support?  VB.net, Vb6, VBA, ?

**Comment by Padanian** [comment]
Clearly VB.net.
VB6 and VBA are not variants to VB.net

**Comment by jonwis** [comment]
Hey @Scottj1s , would using [C#/WinRT](https://github.com/microsoft/CsWinRT) to produce a .NET assembly work for VB.net?

**Comment by jonwis** [comment]
Closing for now, feel free to reopen it.

**Comment by Scottj1s** [comment]
> Hey @Scottj1s , would using [C#/WinRT](https://github.com/microsoft/CsWinRT) to produce a .NET assembly work for VB.net?

Yes, it should.  Cswinrt generates CLS compliant code.  We once considered naming it Net/WinRT.  And we have early adopters using it from F#.
