### ISSUE TITLE
Question: Does Acrylic move out of the OS into ProjectReunion

### ISSUE THREAD

**Issue by mdtauk** [microsoft/ProjectReunion#28]
The WinUI team have had to drop support for HostBackdrop Acrylic due to it being tied up with the OS code.

So does Project Reunion allow for this Acrylic code to get updated in time for WinUI 3.0 release at the end of the year?

**Comment by AzAgarampur** [comment]
I hope so, but at the same time the project is trying to decouple from the OS too so it’s not really clear...

**Comment by mdtauk** [comment]
> I hope so, but at the same time the project is trying to decouple from the OS too so it’s not really clear...

This project will have some lower level APIs taken out of the OS - so if Acrylic needs lower level code to work - this could be how its done.

**Comment by jonwis** [comment]
Can you ask this on the WinUI3 repo?

Also, can you tell us more about how you're using HostBackdrop in your app?

**Comment by mdtauk** [comment]
> Can you ask this on the WinUI3 repo?
> 
> Also, can you tell us more about how you're using HostBackdrop in your app?

The AcrylicBrush used for sidebars or Calculator's background - requires the Host Backdrop.  WinUI has said they are having difficulty separating it from the OS.

So I wondered if it is within the scope of this wider Project Reunion codebase.

![image](https://user-images.githubusercontent.com/7389110/82387275-7fb59080-9a2e-11ea-8616-f7527ba2128d.png)

![image](https://user-images.githubusercontent.com/7389110/82387371-ba1f2d80-9a2e-11ea-8d71-656d71eca0de.png)

**Comment by jonwis** [comment]
Thanks for the suggestion! You're right, Acrylic is a super important part of the Fluent design we want to bring to all apps.  We're working on some things here for the future. For now, @stevewri  assigned to track.

**Comment by AzAgarampur** [comment]
I don't understand why WinUI is trying to decouple Acrylic backgroundbrush from the OS. It's not possible, as it needs the functionality of the DWM and DirectComposition engine to render content behind the application window.

**Comment by stevewri** [comment]
Like Jon said, we're looking at some ideas for this. The thread has gone fairly quiet, so I'll close it for now. Please feel free to open it back up, and/or we'll tag it with a pointer to a proposal if/when we can flesh out those ideas.

**Comment by mdtauk** [comment]
A thought that occured to me in another repo...

I wonder if going back to Windows 7 - WinUI/Reunion could provide a driver, which provides the Rendered layer needed to handle Acrylic.  WinUI apps on deployment and new OS versions could include the driver which provides the base layer render visual, via the Store.

Windows 7 and Vista before it must have had the capability for the Aero Glass rendering.  Windows 8/8.1 had the Visual Composition Layer.  So perhaps this is more of a Reunion ask, but if the driver handled the OS dependent stuff, the rest could all remain User level right?
