### ISSUE TITLE
WebView2 APIs are classic COM - shouldn't they be WinRT?

### ISSUE THREAD

**Issue by smj389** [microsoft/ProjectReunion#29]
If you look at the examples for WebView2, they are all terrible C++ using old COM APIs. 
If they were projected as WinRT APIs, we could use C++/WinRT or (eventually) Rust/WinRT to consume them.

**Comment by atanassov** [comment]
You're referring to the Preview version of the WebView2 API which indeed targets COM. We are aware of this and thinking about how to make the Stable API available to all languages through projection.
