### ISSUE TITLE
What's the recommend approach for programmatically identifying apps like Flight Simulator?

### ISSUE THREAD

**Issue by riverar** [microsoft/ProjectReunion#310]
Microsoft Flight Simulator (2020) appears to be a packaged app with Xbox virtual disk wrapping. Is there a recommended approach to programmatically identifying these types of applications and distinguishing them from _Immersive_ applications and traditional _desktop_ applications? 

* `IsImmersiveProcess` returns `FALSE` in this case
* `GetApplicationUserModelId` will return a valid AUMID, but that can be true for all app types

In our case, we discern between the two aforementioned types to drive how we retrieve the app's icon for display purposes. I'd prefer not to change our code to assume all apps are _immersive_ until failure.

**Comment by Jaiganeshkumaran** [comment]
@riverar Packaged desktop apps are not immersive apps.

**Comment by riverar** [comment]
@Jaiganeshkumaran Thanks, am aware of that. But it's not clear if Flight Simulator is a "desktop app" either. I think I'm just coming around to the idea that everything is _a la carte_ now and we're going to need better "app icon" APIs. I'll close this issue and open a new issue for that instead.

**Comment by Jaiganeshkumaran** [comment]
@riverar Flight simulator is a desktop app since it doesn't run inside UWP app container (low trust)

**Comment by riverar** [comment]
@Jaiganeshkumaran Understood. And I do see it's a full-trust app. But it's wrapped in an Xbox container that provides similar appcontainer functionality, so it's not immediately clear what it is (to me, at least). And there are certainly no docs on this.
