### ISSUE TITLE
Allow non-CoreApplication based apps to be a share target

### ISSUE THREAD

**Issue by Jaiganeshkumaran** [microsoft/ProjectReunion#312]
# Proposal: Allow non-CoreApplication based apps to be a share target
Today any app including HWND apps can host the share charm. However, till now only apps with a CoreWindow can be a target because the dialog doesn't support displaying other windows even if the app is packaged.

## Summary

Although you could create a new UWP project and use it as the target, for developers who are using third-party frameworks this is not simply feasible. Take the new Skype for example. It's packaged but it now lost the share charm support which is really necessary for a modern OS. Even on Android, Skype supports as a share target but not on your own platform anymore. This is not a good experience.

## Rationale

* More apps can become a share target
* Sharing will be much better in Windows

## Scope

| Capability | Priority |
| :---------- | :------- |
| This proposal will allow classic HWND developers to make their apps a share target | Must |
| This proposal will allow end users to share content directly to more apps | Should |

**Comment by jonwis** [comment]
This looks like something that could be added to @andreww-msft 's existing proposals of expanding the kinds of activations that apps support.  Share-target is an activation.

**Comment by andreww-msft** [comment]
Yes, ShareTarget is on our list of activation kinds to support in a later version of AppLifecycle. https://github.com/microsoft/ProjectReunion/issues/111
