### ISSUE TITLE
Docs suggestion: Document support of IWeakReferenceSource

### ISSUE THREAD

**Issue by benstevens48** [microsoft/ProjectReunion#315]
# Proposal: Document support of IWeakReferenceSource
This is a very minor suggestion. Please can you document somewhere which WinRT classes support IWeakReferenceSource. Maybe it's all of them in the Windows SDK? I couldn't find it documented anywhere (via a Google search), but it's quite important (in order to avoid reference cycles) to know this when writing C++ code which uses WinRT classes.

**Comment by stevewri** [comment]
I see that both IWeakReference and IWeakReferenceSource docs have broken methods links, should fix that as well.

**Comment by stevewhims** [comment]
Hi, @benstevens48, and thanks for filing this issue.

The subject matter experts say that IWeakReference support is on by default for Windows Runtime types in C++/WinRT, WRL, and C++/CX. For example, you can find more info in [Weak references in C++/WinRT](https://docs.microsoft.com/windows/uwp/cpp-and-winrt-apis/weak-references#weak-references-in-cwinrt). So, yes, you're right that it's our intent for all Windows Runtime types to support IWeakReferenceSource.

I'll see whether I can find a good place in the docs to make this clearer, so you can leave that with me.

@stevewri, I made some changes yesterday, and it looks like those broken links are now resolved (the links were redundant, and they're now gone).

-Steve

**Comment by benstevens48** [comment]
@stevewhims - OK, thanks for that. Technically, that means types I author myself will support it, but that doesn't guarantee that types in the Windows SDK do. In practice I suppose it means they probably do, but it would be nice if it was guaranteed.

**Comment by stevewhims** [comment]
@benstevens48, yes, I'd say that's an accurate assessment at present. We realize it would be better if it were guaranteed, or if there were a way to determine support at build time. Incidentally, Windows.UI.Compositon and Windows.Devices.Input.PenDevice are examples of exceptions: that is, namespaces where weak reference support is *not* on for those types. For such types, it's possible to run into a winrt::hresult_no_interface exception in rare cases--for example, when attempting to register an auto-revoke event handler. So it'd be necessary to register and revoke manually.

**Comment by andrewleader** [comment]
Closing this for now, let us know if anything else is needed!
