### ISSUE TITLE
Nuget packages should have well-defined structure

### ISSUE THREAD

**Issue by kennykerr** [microsoft/ProjectReunion#319]
Currently parsing a nuget package requires an msbuild engine to figure out where to locate winmd files, DLLs, and other dependencies. This makes it incredibly difficult to consume from any other kind of build system, whether cmake for C++ developers or Cargo for Rust developers, to name just two. It also isn't too reliable for C++ developers using msbuild, which is optimized for C# consumption.

Project Reunion should follow a consistent structure that allows any developer to download the package zip file and extract its contents reliably without any knowledge of msbuild. For example:

```
/winmd/
/architecture/x64/
/architecture/x86/
/architecture/arm/
/architecture/arm64/
```

The CI build for Project Reunion could have a script that validates that the nuget package can be downloaded purely using a zip library/tool and checks the structure to ensure that this convention is followed. 

Based on a conversation with @BenJKuhn.

**Comment by jevansaks** [comment]
The [nuget structure is documented](https://docs.microsoft.com/en-us/nuget/create-packages/creating-a-package#from-a-convention-based-working-directory) and fully .NET packages don't need any custom build targets. Where we get into trouble is custom build targets in the nupkgs. The big two:
1) To be consumed from C++ projects, we need custom targets ([documentation tells you to do this](https://docs.microsoft.com/en-us/nuget/guides/create-uwp-packages#adding-targets))
2) AppX/PackageDependency stuff never got folded in to the official structure so we have to carry custom build targets to handle that.

**Comment by kennykerr** [comment]
Even though there is a documented structure, projects are not required to follow this structure. Here's the latest example a customer (using C++ with msbuild) just came across and was forced to manually reference the winmd file:

https://www.nuget.org/packages/Microsoft.Services.Store.Engagement/

I'm sure there's a very good reason for this very different structure. Perhaps that's what you're alluding to above. But pretend I don't care and just want to suck out the winmds and DLLs. 

So yes, there is a documented structure - feel free to use that. Just be consistent and make sure it works without any knowledge of msbuild, props, targets, or any other buzz words. That's the ask.
