### ISSUE TITLE
Question: How to use the Microsoft.Toolkit.Uwp.Notifications NuGet for .NET 5?

### ISSUE THREAD

**Issue by 100RH** [microsoft/ProjectReunion#320]
Hello,
We are building a component for WinForms using Microsoft.Toolkit.Uwp.Notifications version 6.1.1. 
We were not able to build it for NET5 and we've noticed that the package is lacking .NET 5 lib both in 6.1.1 and in the latest 7.0.0-preview4. At the moment we are getting the following error, when trying to build with 6.1.1/7.0.0-preview4:

> Error	CS0012	The type 'ToastNotifier' is defined in an assembly that is not referenced. You must add a reference to assembly 'Windows.Foundation.UniversalApiContract, Version=10.0.0.0, Culture=neutral, PublicKeyToken=null, ContentType=WindowsRuntime'.

Adding the appropriate reference did not solve the problem.

Is there something that we are missing or do we need a new lib for .NET 5?
If so, do you know, when you are going to have one ready?

Regards,
Stoyan

**Comment by Jaiganeshkumaran** [comment]
@100RH Add CsWinRT to your project. If that does not work, report it here: https://github.com/windows-toolkit/WindowsCommunityToolkit

**Comment by 100RH** [comment]
@Jaiganeshkumaran thanks for the reply. 
I found that this is a duplicate of the following issue:
[https://github.com/windows-toolkit/WindowsCommunityToolkit/issues/3579](url)
