### ISSUE TITLE
Question: Use classic Windows 32 API Dll's in UWP Project

### ISSUE THREAD

**Issue by Alkanores** [microsoft/ProjectReunion#330]
Hey! Can I get step-by-step instruction, how I should use Win32 dll in UWP C# Project? Has this method limitations like Windows 10 version? Thanks.

my win32api.dll
```cpp
#include "pch.h"

#define DllExport   __declspec( dllexport )

BOOL APIENTRY DllMain( HMODULE hModule,
                       DWORD  ul_reason_for_call,
                       LPVOID lpReserved
                     )
{
    switch (ul_reason_for_call)
    {
    case DLL_PROCESS_ATTACH:
    case DLL_THREAD_ATTACH:
    case DLL_THREAD_DETACH:
    case DLL_PROCESS_DETACH:
        break;
    }
    return TRUE;
}

extern "C"
{
    DllExport void GetRamSize(OUT long long& ramSize)
    {
        ramSize = 132312;
    }
}
```

**Comment by Jaiganeshkumaran** [comment]
@Alkanores It should work as long as the APIs you're trying to is available in UWP.

**Comment by Alkanores** [comment]
> @Alkanores It should work as long as the APIs you're trying to is available in UWP.

Project Union exists for union of win32 and winrt api's? If Project Reunion cannot give me Windows API, why it exists?

**Comment by Jaiganeshkumaran** [comment]
@Alkanores Already many Win32 APIs are available in UWP before Reunion. Other APIs will come to UWP or may not come. See https://docs.microsoft.com/en-us/uwp/win32-and-com/win32-apis

**Comment by Alkanores** [comment]
> @Alkanores Already many Win32 APIs are available in UWP before Reunion. Other APIs will come to UWP or may not come. See https://docs.microsoft.com/en-us/uwp/win32-and-com/win32-apis

Get HWID for hardware ban? MemoryWriter for anticheat?

**Comment by Jaiganeshkumaran** [comment]
@Alkanores No but you can proposethem in UWP for Reunion

**Comment by Alkanores** [comment]
> @Alkanores No but you can proposethem in UWP for Reunion

I need this right now for production app, there must be another way.

Has .exe app limitations, if UWP launched it with Full Trust?

**Comment by Jaiganeshkumaran** [comment]
@Alkanores Full trust should have full access

**Comment by Alkanores** [comment]
> @Alkanores Full trust should have full access

Full access to WinRT or Win32 api?

**Comment by Jaiganeshkumaran** [comment]
@Alkanores Full trust component should have full access to both

**Comment by Alkanores** [comment]
> Full trust component should have full access to both however APIs related to XAML will not work from Win32 Full trust.

I don't need XAML Api from Win32 full trust, just run and communicate with UWP App by AppService. Just AntiCheat service.

Is this real?

**Comment by Jaiganeshkumaran** [comment]
@Alkanores Yes you can do that and it will work

**Comment by Alkanores** [comment]
> @Alkanores Yes you can do that and it will work

I ask again just in case.

1) Can I launch win32 exe app from UWP app throught Full Trust?
2) Can I communicate with win32 app from UWP app throught AppService?
3) Can I use ALL functions from win32 API (even those that UWP doesn't support) in my win32 app which I launch througth Full Trust?

**Comment by Alkanores** [comment]
> > @Alkanores Yes you can do that and it will work
> 
> I ask again just in case.
> 
> 1. Can I launch win32 exe app from UWP app throught Full Trust?
> 2. Can I communicate with win32 app from UWP app throught AppService?
> 3. Can I use ALL functions from win32 API (even those that UWP doesn't support) in my win32 app which I launch througth Full Trust?

@Jaiganeshkumaran

**Comment by AathifMahir** [comment]
@Alkanores Checkout this article for using full trust access on UWP, I think using this method you can use most of the win32 Api's

https://stefanwick.com/2018/04/06/uwp-with-desktop-extension-part-1/amp/?__twitter_impression=true

**Comment by Alkanores** [comment]
> @Alkanores Checkout this article for using full trust access on UWP, I think using this method you can use most of the win32 Api's
> 
> https://stefanwick.com/2018/04/06/uwp-with-desktop-extension-part-1/amp/?__twitter_impression=true

And how I can communicate between uwp app and win32 app?

**Comment by Alkanores** [comment]
@AathifMahir thanks!
