### ISSUE TITLE
There is some 3D modeling for UWP where you can use it with stylus or mouse.on: [your question here]

### ISSUE THREAD

**Issue by Javier118** [microsoft/ProjectReunion#336]
where you have functions like drawing 2D and 3d etc

**Comment by mdtauk** [comment]
There are Inking controls.

Win2D exists, and there was a 3D Viewer control being proposed.

There is a DirectX SwapChain background for displaying 3D rendered content.

**Comment by Javier118** [comment]
the idea as what the Shap3D app uses with rendization engine

**Comment by stevewri** [comment]
I'm not clear on some parts of the question. By "you can use it with stylus or mouse" do you mean a 3D viewer that would support *adding* (editing the scene graph) 3D content interactively with pen or mouse, or a 3D viewer that lets you *manipulate* the model with pen or mouse? (Or both?) The frameworks that work well with UWPs are Unity and DX, can you take a look at them?

**Comment by Javier118** [comment]
if you do not have a tactile screen you can use the mouse to do 3D cad modeling or if you have Tactil the power to use styles
