### ISSUE TITLE
Announcing Project Reunion V0.1! 

### ISSUE THREAD

**Issue by mevey** [microsoft/ProjectReunion#337]
Since the announcement of Project Reunion at Build this year, we’ve used this platform to directly engage and discuss features and issues that are important to you, the Windows developer community. We want to keep up the momentum by releasing an early build of Project Reunion to start the build pipeline and begin bringing in preview components. 

**So today, we are happy to announce the first Project Reunion preview!**  

V0.1 is just the beginning. This limited preview lays the foundation for Project Reunion’s runtime distribution and includes some of the work we’ve done towards creating the plumbing that makes sure your apps can consume Project Reunion APIs. _There’s still more to do_, to unify the platform, add more functionality such as Windowing and Storage APIs that will be released in the coming months, and do performance tuning. We will be publishing a more detailed roadmap in the new year, 2021. 

This preview is _not recommended for production use_, but try out the samples, experiment with the APIs, and give us feedback.  

### **Getting started with V0.1** 

Here are some documentation and samples available as part of this preview that you can try out, and most importantly, give feedback on. We encourage you to [ask questions, file bugs, and make proposals. ](https://github.com/microsoft/ProjectReunion/issues/new/choose)

- Project Reunion’s [**Hello World sample**](https://github.com/microsoft/Project-Reunion-Samples/tree/main/HelloWorld/reunioncppdesktopsampleapp) is a sandbox for you to test Project Reunion APIs without having to worry about the plumbing and setup, which includes a temporary workaround. It uses some [new App-Lifecycle APIs](https://github.com/microsoft/ProjectReunion/issues/111) that are in the works. 
- **DirectWriteCore** brings best-in-class text layout and rendering to your app and reduces the implementation cost across all Windows versions and other platforms because it is cross-platform and works downlevel. Checkout the [Font Viewer sample app](https://github.com/microsoft/Project-Reunion-Samples) to learn how you can utilize critical features, such as Variable Fonts, downlevel. 
- [**Modern Resources Toolkit (MRT) Core** ](https://github.com/microsoft/ProjectReunion/tree/main/dev/MRTCore)brings resource management innovation from the last twelve years to Win32 app developers. 

Other Project Reunion releases to check out: 

- WinUI 3 preview 3, which was released last month. This preview is currently packaged separately from Project Reunion V0.1. You can [learn how to use this preview to modernize your app UX ](https://docs.microsoft.com/en-us/windows/apps/winui/winui3/)  
- [Microsoft Edge WebView2](https://docs.microsoft.com/en-us/microsoft-edge/webview2/) for Win32 C/C++, which is generally available and ready for use in production applications. 

Important links: 

- [Project Reunion NuGet package ](https://www.nuget.org/packages/Microsoft.ProjectReunion/)
- [Project Reunion Docs](https://docs.microsoft.com/windows/apps/project-reunion )
- [All Project Reunion samples ](https://github.com/microsoft/Project-Reunion-Samples)

Stay tuned for more announcements, previews, and releases!

**Comment by Sunbreak** [comment]
Could we use Github Disscussions instead of issues?

**Comment by andrewleader** [comment]
@Sunbreak we're working on that 😊

**Comment by soumyamahunt** [comment]
The new project file format for Reunion sample app causing failure when using vcpkg packages, this is due to vcpkg detecting the project as uwp project instead of desktop app. I have already filed an issue in vcpkg repo [here](https://github.com/microsoft/vcpkg/issues/15409) also submitted [PR](https://github.com/microsoft/vcpkg/pull/15410) that should fix this issue for now. Since project reunion isn't finalized just yet and the format for project file may change in future, this issue needs some focus and should be discussed.
