### ISSUE TITLE
Question: Set package installation folder for WinUI Desktop app

### ISSUE THREAD

**Issue by VagueGit** [microsoft/ProjectReunion#339]
We are migrating a UWP/Store app to WinUI desktop. The install location is generated by the store as ~<Publisher><AppName><Hash> and displayed as Package family name.

I have copied the Package name, Package display name and Publisher display name from the UWP app to the WinUI app but the hash at the end of the Package family name is different, hence the install location is different.

We need the install location to be the same so we have access to existing app data.

How do we ensure the install location for the WinUI desktop app is the same as the UWP/Store app?

**Comment by jonwis** [comment]
Are you sure you copied the `/Package/Identity/@Publisher` field _exactly byte for byte_ as it was in the original manifest? That's what is used to build the package publisher hash.

@jvintzel can you advise further?

**Comment by VagueGit** [comment]
WinUI offers project templates for WinUI Desktop and WinUI UWP. I chose WinUI Desktop, not WinUI Desktop Bridge MSIX.

Project properties are presented differently between UWP and WinUI desktop so explicit guidance as to what to copy from which field to which field is appreciated.

**Comment by FreddyD-GH** [comment]
@VagueGit I believe the properties in your second screenshot are used for creating a Nuget package, not for creating the APPX/MSIX pacakge.  The WinUI Desktop project template should create two projects: the actual program, and a packaging project.  The packaging project should contain a Package.appxmanifest file and that's where you should enter the Package name, Package display name and Publisher display name.  The editor for the Package.appxmanifest file should look virtually identical to editing the manifest in UWP (your first screenshot).

**Comment by VagueGit** [comment]
Having entered everything identically, we still get a different hash at the end of the installation folder, unless we associate the app with the store.

and there's the rub

The previous version was a UWP store app. The WinUI desktop app will not be a store app. The Store app will be discontinued. So the WinUI app cannot be associated with the store and the installation folder will be different.

**Comment by DrusTheAxe** [comment]
>Store app will be discontinued. So the WinUI app cannot be associated with the store
That's fine. Just don't change your package identity and it's the same app, regardless if it's offered by Store or others.

> and the installation folder will be different.
Only if you change your identity. Don't do that.

That 'hash' is the `PublisherId`, which is derived from your package Publisher (the "CN=...354..." value in your screenshot). That's defined in the `<Identity>` element in appxmanifest.xml. It doesn't matter if your package is in the Store or even signed with the Store's cert, long as you don't change your manifested Publisher value you get the same PublisherId

**Comment by VagueGit** [comment]
@DrusTheAxe Thank you for helping run this to ground.

**Comment by VagueGit** [comment]
Apologies for closing this too soon. I've installed our old UWP app from the store. Then run in debug our Project Reunion/WinUI Desktop app which now has the same package id as the store app. Windows threatens to uninstall our old app and wipe it's state:
![image](https://user-images.githubusercontent.com/17174099/103146259-53b37800-4792-11eb-87fb-4401b0a9c4a0.png)

Identity name and publisher are identical for both apps.

We need to preserve state so we can upgrade the user data.

**Comment by jonwis** [comment]
@VagueGit  can you confirm that you got it working?

**Comment by VagueGit** [comment]
I can confirm that we got the package installation folder sorted, by setting the package identity of the WinUI desktop app to the same as the UWP store app. However once we apply the same package identity to the WinUI desktop app as is used in the UWP store app, the WinUI desktop app won't build/run unless it is associated with the UWP store app in the store.

That will be a problem for us once the UWP app is no longer in the store.
