### ISSUE TITLE
Question: Code for WinUI/Win32 template apps

### ISSUE THREAD

**Issue by zcbenz** [microsoft/ProjectReunion#34]
I'm very interested to see how WinUI 3 is used with C++/Win32, but currently in order to see the actual code I have to install a preview version of Visual Studio 2019.

Can you put the code of the template apps in this repo? Installing and uninstalling a Visual Studio can potentially break my development environment completely, it is a bit too pricy to have a peek of the code.

**Comment by hansmbakker** [comment]
In principle, Visual Studio 2019 and Visual Studio 2019 Preview can be installed side-by-side and should not bite each other. That said, it could indeed be nice to have the template code in a github repo, from which the template packages are generated. There people could also give feedback on the template code.

**Comment by jonwis** [comment]
@pag3 or @MikeHillberg or @marb2000 - This seems like a question for the WinUI3 repo?

You can also just download the [VSIX from here](https://marketplace.visualstudio.com/items?itemName=Microsoft-WinUI.WinUIProjectTemplates), rename it to .zip, and open it up.  In there you'll find various template definitions.

**Comment by MikeHillberg** [comment]
We do plan to get it all in GitHub, but we're not there yet. The [WinUI repo](http://github.com/microsoft/microsoft-ui-xaml) is best place to discuss it.

**Comment by zcbenz** [comment]
Thanks for the answers!
