### ISSUE TITLE
Are VB6/COM applications supported

### ISSUE THREAD

**Issue by melanysoft** [microsoft/ProjectReunion#340]
Can ProjectReunion be used to modernize existing Visual Basic 6 (Classic) EXE and COM DLL/OCX apps ?
In documentation you refer to C++, but there is this one sentence:

_Practically speaking, any language & runtime that can handle COM objects can support Project Reunion. Please file an issue with a specific language or runtime in mind._

Does it this mean VB6 is included too ?

**Comment by sylveon** [comment]
Technically yes, but you'll have interact with the raw WinRT ABI, which is usually more pain than it's worth.

**Comment by DrusTheAxe** [comment]
That's probably the easiest -- make classic COM inproc object(s) that VB can interact with (BSTR, Variant, yadda yadda) which call the WinRT APIs you desire.

**Comment by stevewri** [comment]
@melanysoft - is that a reasonable solution for VB6 apps for you? If not, please reopen and follow up!
