### ISSUE TITLE
Microsoft is great, but why not have a file creation service?

### ISSUE THREAD

**Issue by ayt-2013** [microsoft/ProjectReunion#344]
**Describe the bug**

**Steps to reproduce the bug**

**Expected behavior**

**Screenshots**

**Version Info**

NuGet package version: 

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |

**Additional context**

**Comment by stevewri** [comment]
I don't understand the ask here, can you be more specific?
