### ISSUE TITLE
Question: How do I embed files inside a PRI file with MRTCore?

### ISSUE THREAD

**Issue by wjk** [microsoft/ProjectReunion#348]
I am using MRTCore outside of the context of WinUI 3. (I have therefore built it from source as part of my project.) My plan is to have each assembly have a `*.pri` file alongside it that contains strings, image resources, and anything else I may need to localize or otherwise have multiple versions of. Basically a supercharged version of RESX.

However, while makepri.exe is happy to generate a PRI file that references outside files on disk, I have not figured out how to embed them within the PRI file itself. I know this is possible, as UWP apps embed their XBF files under certain circumstances that I have yet to isolate. (The default behavior is to dump loose XBF files into the project’s output path.)

What I need is the ability to have arbitrary binary files (usually PNGs, but that is not guaranteed to be the only file type) embedded within my PRI file. I also need to be able to control the URIs used to retrieve the resources, because I will be organizing resources for use at runtime in a specific fashion. Furthermore, RESW files are placed into a different URI subtree than a text file in the same directory, which I also do not want.

How would I do this? I have found nothing in the documentation for `makepri.exe`. My `priconfig.xml` file is below, as I have customized it from the default. Any assistance would be appreciated. Thanks!

-------

```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<resources targetOsVersion="10.0.0" majorVersion="1">
  <index root="\" startIndexAt="\">
    <default>
      <qualifier name="Language" value="en-US"/>
      <qualifier name="Contrast" value="standard"/>
      <qualifier name="Scale" value="100"/>
      <qualifier name="HomeRegion" value="001"/>
      <qualifier name="LayoutDirection" value="LTR"/>
      <qualifier name="Theme" value="light"/>
      <qualifier name="AlternateForm" value=""/>
      <qualifier name="DXFeatureLevel" value="DX9"/>
      <qualifier name="Configuration" value=""/>
      <qualifier name="DeviceFamily" value="Universal"/>
    </default>

    <indexer-config type="folder" foldernameAsQualifier="true" filenameAsQualifier="true" qualifierDelimiter="."/>
    <indexer-config type="resw" convertDotsToSlashes="false" initialPath=""/>
    <indexer-config type="resjson" initialPath=""/>
    <indexer-config type="resfiles" qualifierDelimiter="."/>
    <indexer-config type="priinfo" emitStrings="true" emitPaths="true" emitEmbeddedData="true"/>
  </index>
</resources>
```

**Comment by ayt-2013** [comment]
Hello, do not you feel that you got me wrong? I do not know Hello, do not
you feel that you got me wrong? I do not know anything about this issue I
entered this photo because the email I wrote is beautiful ❤️🧡💛💚💙💜

در تاریخ یکشنبه ۲۰ دسامبر ۲۰۲۰،‏ ۰۰:۲۳ William Kent <
notifications@github.com> نوشت:

**Comment by axelandrejs** [comment]
To embed files, you need to create a new index node covering those files, and add <indexer-config type="EmbedFiles"/>.

Note that this does not work for assets referenced in the manifest.

**Comment by wjk** [comment]
@alexandrejs "create a new index node covering those files, and add" what, exactly? There may be missing backquotes in your post, which prevents me from seeing what should be inside. (This happens often if the contents of a missed codeblock are XML or HTML.) Thanks!

**Comment by huichen123** [comment]
i think that's another <index root="\" startIndexAt="\">, and point startIndexAt to where your embed files locate. Also add <indexer-config type="EmbedFiles"/> in that node.

**Comment by axelandrejs** [comment]
As Hui said:). You can either isolate the embedded files into a folder and set the index root to that, or use a file list to explicitly specify those files.

**Comment by wjk** [comment]
@huichen123 Works like a charm! I have also used `makepri dump` to examine the contents of my PRI file, and they are exactly as I want them. Thanks so much!

**Comment by huichen123** [comment]
It doesn't seems to have a good way to add embedded resources currently. We probably need to make some targets file change to support that. As William has pointed out, PRI is different from MUI. It's supposed to be a loose file, instead of embedded in PE.

That said, I am able to add following to my project to embedded some files. You may do similar thing as a current workaround.

~~~
  <ItemGroup>
    <MyEmbeddedItems Include="app.manifest" />
    <MyEmbeddedItems Include="app.xaml" />
  </ItemGroup>

  <Target Name="AddMyEmbeddedItems" BeforeTargets="_GenerateProjectPriFileCore" AfterTargets="_CalculateInputsForGenerateProjectPriFileCore">
    <Copy SourceFiles="@(MyEmbeddedItems)" DestinationFolder="$(IntermediateOutputPath)\embed\" />
    <ReadLinesFromFile File="$(_EmbedFileResfilePath)" >
      <Output
        TaskParameter="Lines"
        ItemName="ItemsFromFile"/>
    </ReadLinesFromFile>

    <ItemGroup>
      <MyEmbeddedFileList Include="@(ItemsFromFile)" />
      <MyEmbeddedFileList Include="@(MyEmbeddedItems)" />
    </ItemGroup>

    <WriteLinesToFile
        File="$(_EmbedFileResfilePath)"
        Lines="@(MyEmbeddedFileList)"
        Overwrite="true"
        Encoding="Unicode"/>
  </Target>
~~~
