### ISSUE TITLE
Question: [Can we have mdi support for this?]

### ISSUE THREAD

**Issue by Shadowblitz16** [microsoft/ProjectReunion#352]
# Proposal: [MDI support] 

## Summary

Can we get mdi support even if its not recommended by Microsoft to use?  
Its great for small screen resolutions or single monitor workspaces.

## Rationale

* {Win32 supports it}
* {Multi monitor workspaces can be fixed by adding a pop out button to the mdi child title bar}
* {We could also have the ability to drag the window back into the mdi container}
* {Could support docking}
* {Its still a good interface pattern for small or single monitor computers}
* {Many companies still use it (like my dentist)}

## Scope

Don't understand this part sorry.

## Important Notes

I would think it should support treating windows as controls and adding mdi children is as easy as..
```
windowA.Controls =
{
    windowB,
    windowC.Controls =
    {
        windowD
    }
}
```

## Open Questions

I searched and didn't see any issues on this

**Comment by duke7553** [comment]
@Shadowblitz16 If Win32 supports the Multiple-Document Interface specification, then why not continue to use it? Project Reunion isn't about completely replacing your existing technology, but gradually enhancing your applications where needed. 

However, if you want to see this specification evaluated as a feature for WinUI: feel free to contribute your ideas, expectations, and opinions to open issues like [this](https://github.com/microsoft/microsoft-ui-xaml/issues/1080). Project Reunion is a family of components and WinUI is one of them. 

If you're happy with the existing MDI support in Win32, then you can enhance your app in [other](https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/) ways.

**Comment by Shadowblitz16** [comment]
Not sure what you mean.
I thought this interduces a common API for win32, winforms, wpf, and uwp and gets rid of them in the system in favor of this.

If so I was just wondering if mdi support could be added to the api

**Comment by mdtauk** [comment]
> Not sure what you mean.
> I thought this interduces a common API for win32, winforms, wpf, and uwp and gets rid of them in the system in favor of this.
> 
> If so I was just wondering if mdi support could be added to the api

Reunion will be about introducing a common wrapper around existing APIs which can be used by UWP and Desktop applications.  In time I am sure new APIs may be introduced.  

One being discussed is replacing the Common File and Folder dialogs with a modern one.  I would imagine apps running on Windows 8 may also be able to use this API, but it will probably just display the native Win32 one there.

**Comment by duke7553** [comment]
@Shadowblitz16 That's a common misconception. While Project Reunion aims to reduce differences in the features that the different application types can leverage, it is not a new app model.

**Comment by stevewri** [comment]
@Shadowblitz16 does that answer your question? Please reactivate if you have a followup!

**Comment by Shadowblitz16** [comment]
It answers the question yes
