### ISSUE TITLE
Hi! Merry Christmas I came to say that Microsoft has not been able to make much progress Google will soon be the best

### ISSUE THREAD

**Issue by ayt-2013** [microsoft/ProjectReunion#356]
![Polish_۲۰۲۰۱۲۲۳_۱۹۲۷۳۲۷۰۶.png](https://user-images.githubusercontent.com/73178045/103438978-13e70780-4c4e-11eb-855c-f3ebc64419f3.png)

**Comment by stevewri** [comment]
I don't see a question, feel free to reactivate if you have one.
