### ISSUE TITLE
Question: How does MAUI fit here?

### ISSUE THREAD

**Issue by tesar-tech** [microsoft/ProjectReunion#36]
This project is basically reunion of UWP and WPF => One best option for creating windows apps with capabilities from both technologies. And now, we have another way of making Windows app. [MAUI](https://github.com/dotnet/maui/).

How does it fit together, will be future maui app also under reunion. Will be every reunion app "compatible" with maui app?

**Comment by luisvargascr** [comment]
I wonder the same. Great question!

**Comment by texasbruce** [comment]
It's still unclear what API MAUI will target on Windows. I thought it would be UWP but now I think it might be targetting WinUI 3 now (or at least it is a good idea to)

BTW this project is a reunion of UWP, WPF, WinForms and MFC

**Comment by andrewleader** [comment]
FYI there's a big thread in the MAUI repo on this: https://github.com/dotnet/maui/issues/43#issuecomment-634109411

**Comment by stevewri** [comment]
One way to think about this is that Reunion's APIs are generally expected to lay in the layer that frameworks build upon. Maui could choose to relayer itself on top of Reunion components, in the same way as WinUI is relayering itself on top of other lifted APIs for input, rendering and composition. That will help extend Maui's reach to all the same Windows endpoints Reunion is targeting.
