### ISSUE TITLE
Unplugging a game controller sends shadow events forever

### ISSUE THREAD

**Issue by samhocevar** [microsoft/ProjectReunion#362]
**Describe the bug**
Unplugging a game controller leaves the layer responsible for UWP gamepad input thinking the controller is still present, and still sends virtual key event to UWP applications. Other applications are not affected.

**Steps to reproduce the bug**
1. Plug in a game controller
2. Open the Start Menu
3. Push a controller thumb stick in a direction that causes scrolling in the Start Menu, _e.g._ going to the right
4. Unplug the controller *without releasing the thumb stick*
5. Observe that scrolling continues even now
6. Observe that closing the Start Menu and reopening it causes scrolling to continue
7. Observe that the events are still sent to any other UWP application, _e.g._ Photos

This bug makes many other standard UWP applications harder to use: Settings, Photos, the screenshot tool…

**Version Info**
Reproduced multiple times on Windows 10.0.19042 Build 19042.

**Additional context**
I am using a standard Xbox One USB controller.

The issue appears to have been first mentioned [in a comment here](https://github.com/microsoft/microsoft-ui-xaml/issues/1496#issuecomment-547233837) and I believe it may be relevant for people in [this other issue](https://github.com/microsoft/microsoft-ui-xaml/issues/1495).

**Comment by andrewleader** [comment]
Hi @samhocevar, thanks for reporting this issue. Since this is a Windows platform issue, can you please file this through Feedback Hub? Feedback Hub will additionally allow you to collect logs that will be shared with the dev team. You can launch Feedback Hub from your Start menu.

I'll close this issue on this repo, since this issue is a Windows platform bug. Thanks!

**Comment by samhocevar** [comment]
I was unable to find my Feedback Hub entry so I entered a new one. The bug is still present in Windows 11, so it’s still pretty relevant. So if anyone wants to upvote it, here is the link: https://aka.ms/AAh93ww

**Comment by wkearney99** [comment]
The hilariously tragic part of this bug is I can't even use the Feedback app to 'Give Similar Feedback' because the input stream seems to think there's an endless stream of right-arrow presses being sent.  FML.

**Comment by Justywusty87** [comment]
Why is this closed? This is very much still an issue and I cannot find resolution anywhere. Does anyone have a workaround? This is the most annoying unfixed windows issue I have ever encountered and that guys video explains what is happening perfectly.. I don't even have to be pressing an input on the controller when i remove it.. Once i unplug it it always acts like it is holding down button.
