### ISSUE TITLE
WebAuthenticationBroker::AuthenticateAsync() will throw "Resource not found" exception when used without a network connection, and needs some fixes in general.

### ISSUE THREAD

**Issue by AzAgarampur** [microsoft/ProjectReunion#366]
**Describe the bug**

The `WebAuthenticationBroker` class has a few problems which need to be fixed. The biggest issue is the unexpected exception that occurs after the authentication broker window is closed when the network is not available. An unexpected exception is thrown and I can't seem to figure out the cause.

The other two not-as-critical (but still need to be improved) items are the 1) the broker window window loosing focus and 2) updating error text. Most of the time, the broker window is not the foreground window, and it looses focus, even when using the broker window itself. This is because the child `CoreWindow` for some reason does not have the `WS_CHILD` style enabled. The second item which should be updated is the error text that the broker text shows. For example, when not connected to the network, a generic message "We can't connect to your service" is displayed, which isn't properly aligned and does not follow the correct system font, size, etc.

Just general things that should be updated for a better, more immersive experience.

**Steps to reproduce the bug**
Attempt to use `WebAuthenticationBroker::AuthenticateAsync()` when not connected to the internet. After the error displays in the broker window, close the window. Notice an exception will be thrown.

**Expected behavior**
Broker window should close cleanly and not throw an exception

**Version Info**
Version 20H2 19042.685

**Comment by andrewleader** [comment]
Hi @AzAgarampur, thanks for filing this bug. Can I confirm that you're talking about the `Windows.Security.Authentication.Web.WebAuthenticationBroker` API (the [UWP API here](https://docs.microsoft.com/en-us/uwp/api/Windows.Security.Authentication.Web.WebAuthenticationBroker?view=winrt-19041))?

**Comment by AzAgarampur** [comment]
Yes, that's correct.

**Comment by andrewleader** [comment]
Thanks for confirming, since this is a platform bug and not a Reunion bug, I'm reaching out to the team responsible for these UWP APIs to make sure this bug is tracked on the Windows Platform side, and I'm closing it here.

Can you email me at aleader (at) microsoft.com so that I can make sure to connect you with the team for any additional details?

**Comment by AzAgarampur** [comment]
I've sent you an email regarding the issue. Let me know if you haven't received it.
