### ISSUE TITLE
Wanted to ask if it's envisioned that Project Reunion might ease the ability of a sandboxed UWP app (a) to share directly with Outlook or Outlook 365 and other desktop apps and (b) to be delivered/installed outside the Store.

### ISSUE THREAD

**Issue by dhholmes** [microsoft/ProjectReunion#37]

**Comment by mikebattista** [comment]
Interop between all kinds of apps is certainly a goal of Project Reunion.

By "sharing directly with Outlook and other desktop apps", I'm assuming you're talking about IPC. Is that correct?

Could you clarify your scenarios here?

**Comment by dhholmes** [comment]
In general, we want to figure out how a UWP app can have the full capabilities of any desktop app that's already "outside the sandbox".

In particular, our customers want a way to share via the default desktop email application (Outlook or Outlook 365), instead of UWP app "Mail".  We're currently limited by the Share service in UWP to only share with UWP apps that support the Share service.

We've looked at including a "trusted" Win32 app that exposes the traditional mail APIs, and use the FullTrustProcessLauncher to access it from the UWP app - a desktop bridge strategy.  However, we haven't figured out how to do so, and currently customers share from the UWP app to "Mail", and then cut & paste into an Outlook email message as a cumbersome workaround.

**Comment by mikebattista** [comment]
Thanks. I recently documented IPC between UWP and Win32 at https://docs.microsoft.com/en-us/windows/uwp/communication/interprocess-communication which has some links about the FullTrustProcessLauncher and other IPC options. Can you let me know how far you get and where you become blocked? I can get you answers and work on updating the documentation if necessary.

One of the things that was poorly documented before which I added was how to update ACLs to unlock more IPC options for UWP apps. This was captured at https://docs.microsoft.com/en-us/windows/uwp/communication/sharing-named-objects. Let me know if you find that useful.

Rounding out gaps here and ensuring the documentation reflects what's possible is all part of Project Reunion's goals.

In terms of delivering UWP apps outside of the Store, that is something we have supported more and more as MSIX has grown. Have you tried the latest capabilities of MSIX to deploy apps outside of the Store? A good resource to start would be https://docs.microsoft.com/en-us/windows/msix/app-installer/app-installer-root.

**Comment by dhholmes** [comment]
I really appreciate the links to updated info that hopefully makes the trusted Win32 app approach go more smoothly.  Your answer implies though that such an approach would still be needed in a Project Reunion world (i.e., no direct sharing with Outlook 365 "out of the box").  We have plans to revisit that approach at some point if direct sharing with Outlook 365 is not in the cards.  Does the info you reference assume VS 2019 (e.g., not VS 2017)?

**Comment by mdtauk** [comment]
Does Office 365 apps not support the share dialog?

**Comment by mikebattista** [comment]
Implementing the [Share contract](https://docs.microsoft.com/en-us/windows/uwp/app-to-app/share-data) is currently required for apps to participate in the Share service. Without Office implementing the contract themselves, we'd need to reevaluate how that works to remove the requirement to implement the contract, which I don't believe is currently in scope.

The alternative approach you described could be something you could implement today to unblock you and remove the cumbersome workaround.

**Comment by mdtauk** [comment]
If the reunion stuff could take on the Share contract side, then there could be scope for UWP sharing one way to WinAPI apps (Win32) - but WinAPI apps sharing to other WinAPI apps, could be much richer.

All of it using the same Share dialog.  And UWP apps can only receive content they have a contract for, so that share process becomes gated for security.

**Comment by tfennel** [comment]
Hi! Owner of the share contract here (well sort of, Ieva on my team owns it and she's working on getting her GitHub account linked as a Microsoft employee account)! The share contract is a great place to have feedback - it's not something we see a ton of use for, so learning the jobs to be done for those using it is valuable for planning as part of Reunion for sure.  We don't have anything concrete planned, but we're definitely interested in having/monitoring the conversation so we can consider how to improve.

**Comment by ptorr-msft** [comment]
Does the Share Contract provide the functionality you need? MAPI is quite powerful and lets you do things that the Share Contract doesn't.

We have a backlog item to enable out-of-proc COM (MAPI, OLE, etc.) _as long as the app has `runFullTrust` capability_ -- meaning the user would still have to be comfortable with your app having elevated permissions -- but you wouldn't have to build a separate EXE and run it via `FullTrustProcessLauncher`. Your "UWP" app could just do it. 

Is that attractive to you?

**Comment by dhholmes** [comment]
If Outlook 365 were to honor the UWP share contract, then we presumably would have what we need (and could avoid the extra step of asking if the user wants to share to desktop app Outlook vs. to another UWP app).
The runFullTrust capability does seem an attractive option, (a) if Microsoft would allow the UWP app to go into the Store with that capability, or (b) if the user could be asked if they agree to granting elevated permissions, and if they say no, for the Store to enable the app to be installed without the permissions.
(As another topic of interest, we have some customers who want to install the UWP app without going to the Microsoft Store, without staging their own Store, and without side-loading.)

**Comment by ptorr-msft** [comment]
Thanks @dhholmes - yes, Store already allows `runFullTrust` apps. We have another backlog item for "make `runFullTrust` optional" as well, so it's good to hear you're interested in it.

What is your customer's definition of "not side-loading"? From the OS' point of view, side-loading just means "not from the Microsoft Store."

**Comment by dhholmes** [comment]
Some of our UWP app customers want to deploy the app widely to their employees without allowing access to the Microsoft Store or licensing new or additional endpoint management tools.  (These may be issues that can't be solved through this forum.)

**Comment by ptorr-msft** [comment]
@jvintzel can likely help with that.

**Comment by Jaiganeshkumaran** [comment]
Technically non-packaged apps can use the share dialog. File Explorer is a great example of this where you can share a file by clicking the share button on the share ribbon.

**Comment by Poopooracoocoo** [comment]
btw is there a reason that edge isn't using msix?

@Jaiganeshkumaran this issue is about desktop apps being a share **target**

**Comment by mevey** [comment]
Perhaps there's an opportunity here to create a proposal for the _runFullTrust_ capability or to create a deployment specific question on sideloading. I'll close this out, @ieburk , owner of share contract has this on her radar.

**Comment by Poopooracoocoo** [comment]
@mevey hey do you know anything about edge and xbox not using msix? (off-topic, sorry)
