### ISSUE TITLE
Question: The future of Windowing in UWP (AppWindow)

### ISSUE THREAD

**Issue by Felix-Dev** [microsoft/ProjectReunion#38]
UWP's AppWindow V1 is still [in preview](https://docs.microsoft.com/en-us/uwp/api/windows.ui.windowmanagement.appwindow?view=winrt-18362&viewFallbackFrom=winrt-19041#remarks) after it was added to the 18362 SDK.

AppWindow V2, which was [introduced](https://channel9.msdn.com/Events/Build/2018/BRK3506) at Build 2018 two years ago, has been missing ever since. The presenter in question, @rkarman, even said MS wants to enable these new windowing app scenarios "as soon as possible" yet here we are, two entire years later, and we hardly know anything new at all. 

Recently, some new [AppWindow APIs](https://martinsuchan.github.io/ApiPeek/Diffs/win10.19555.to.win10.19569.fulldiff.html) were spotted in Insider Preview SDKs (19569) but they got removed again. Will those APIs be added back? When will they be added back? When will they actually make it into a production-ready SDK?

AppWindow V1/V2 is a critical component for the UWP development story. Yet we are hearing nothing about it. We were [told](https://github.com/microsoft/microsoft-ui-xaml/issues/1323#issuecomment-583774525) by @clarkezone that we might get to hear more about AppWindow in "the Build timeframe" but I'm not keeping my hopes up here as I don't find anything related to UWP windowing going on at Build.

Yes, there is a new Window class spec opened in WinUI but it doesn't yet cover any of the areas originally envisioned at that Build 2018 conference. And to my understanding, that new WinUI 3 Window class is just a wapper around either a CoreWindow on UWP or an HWND for Win32, As such, I believe all these UWP Windowing improvements talked about have to happen in a different component of the platform. And indeed, at Build 2019 with the introduction of WinUI 3, AppWindow [was briefly mentioned](https://youtu.be/hKMzFjGfoy0?t=3360) to be one of the post WinUI 3.0 goals.

Still, even with that "update" on AppWindow at Build last year, we really don't know much at all about the future windowing capabilities of the UWP. **A detailed windowing roadmap for UWP is deperately needed.** We also need to know when and where we can actually engage with the platform teams to drive forward UWP windowing. At least for now the actual team(s) at MS owning the AppWindow/UWP windowing seem to be out of reach for us, the passionate UWP community.

**Comment by rkarman** [comment]
We are actively working on the windowing story for Reunion right now and will have more details to share in a month or two.

**Comment by mdtauk** [comment]
> We are actively working on the windowing story for Reunion right now and will have more details to share in a month or two.

Hopefully it will cover both the 3.0 release feature set and what comes next after

**Comment by Felix-Dev** [comment]
Some new AppWindow APIs have been spotted in Windows 10 build 20150: https://martinsuchan.github.io/ApiPeek/Diffs/win10.2010.to.win10.2104.fulldiff.html (at the bottom of list)
Not all AppWindow APIs [spotted](https://martinsuchan.github.io/ApiPeek/Diffs/win10.19555.to.win10.19569.fulldiff.html) last year in build 19569 are back yet though, such as 
```
AppWindow.TryHide(Boolean shownInSwitchers) : Void
```

Waiting for news about the windowing story for UWP 🙂

**Comment by mevey** [comment]
@Felix-Dev @mdtauk , @rkarman just made an announcement on windowing here. https://github.com/microsoft/ProjectReunion/issues/157

Let's close this and continue the discussion on that thread.
