### ISSUE TITLE
[MRTCore] ResourceNotFoundEventArgs.SetResolvedCandidate will clobber if multiple handlers registered

### ISSUE THREAD

**Issue by alwu-msft** [microsoft/ProjectReunion#387]
The [function call operator](https://docs.microsoft.com/en-us/uwp/cpp-ref-for-winrt/event#eventoperator-function-call-operator) for C++/WinRT's `winrt::event` will invoke all registered event handlers (the order is not defined and so is not guaranteed, although I assume that it is FIFO). Because `ResourceNotFoundArgs` does not have a `Handled` property (or a means to determine if `SetResolvedCandidate()` had been previously invoked), there is no way for a handler for the `ResourceNotFound` event to know if another registered handler ran first and was able to provide a `ResourceCandidate`; the result is that handlers which run later will clobber handlers that run earlier.

The proposal is that a boolean `Handled` property be added to `ResourceNotFoundEventArgs`.

**Comment by huichen123** [comment]
Added ResourceMap::TryGetValue. WinUI will use that to handle when resource is not found. The chance that app itself has multiple conflicting ResourceNotFound handlers is slim. We will keep the current behavior.
