### ISSUE TITLE
Question: File I/O limitations in WinUI 3 apps?

### ISSUE THREAD

**Issue by AJLeuer** [microsoft/ProjectReunion#395]
I'm trying to make a desktop WinUI 3 app. First off, let me know if this isn't the right place to ask for help with that. Second, just to make sure I'm on the right track, this is the template I started with in Visual Studio - the "WinUI in Desktop" one:

![Creating App](https://user-images.githubusercontent.com/4187383/105641172-8dca7500-5e37-11eb-8e2d-4a1e838a981e.png)

My understanding is that will allow me to create an application that has all the capabilities of a Win32 application, but using the same UI toolkit that UWP apps use. Please correct me if I'm wrong about that.

With that out of the way, I'm now trying to do some file IO in my app, and it's not working as I'd expect. Here's my code (highly simplified for the purposes of this question):

```csharp

private static StreamWriter LogWriter;

//called at app startup
public static void StartLogging()
{
    var logFileDirectory = new FileInfo(@"C:\Users\Adam\AppData\Roaming\MyApp\");
    logFileDirectory.Directory?.Create();
    var logFile = new FileStream(@"C:\Users\Adam\AppData\Roaming\MyApp\Log.log", FileMode.OpenOrCreate, FileAccess.Write);
    LogWriter = new StreamWriter(logFile);
}

//called whenever something should be logged
public static void Log(string output)
{
    LogWriter.WriteLine(output);
    LogWriter.Flush();
}

//called when app finishes
public static void StopLogging()
{
    LogWriter.Close();
}
```

As far as I can tell from the way the app behaves, this code seems to be working. When I run it in Visual Studio it doesn't complain about not being able to find the file path, or open the file or anything like that. 

Here's the problem though: when I go to the path where I expect to find my log file  (`"C:\Users\Adam\AppData\Roaming\MyApp\Log.log"`), there's nothing there. In fact, not only does my log file not exist, but the `MyApp` directory's not there either.

It's at this point that it hit home that, despite what I wrote earlier, I've really no idea what the limitations of a WinUI app actually are. I still don't understand whether, at its core, my application is really a Win32 application, or if it's really a UWP app. But, that aside, I assumed for the time being that my app is a UWP app, and with that in mind I looked for documentation on giving UWP apps file system access. The one thing I found that seemed to be relevant was adding this line to my `.appxmanifest` file, under `<Capabilities>`:
```xml
<rescap:Capability Name="broadFileSystemAccess" />
```
This of course made no difference. The app still runs, supposedly opens my log file just fine, supposedly writes to it with no trouble, and closes it without complaint. It never once gives me any kind of error that would indicate it can't find or open a file, or that it doesn't have the right permissions. I don't notice any warnings or errors in Visual Studio. But, just the same, the log file is nowhere to be found.

**Comment by Jaiganeshkumaran** [comment]
@AJLeuer Currently all WinUI 3 apps are packaged so you should write to ApplicationData.Current.Roaming.

**Comment by stevewri** [comment]
@AJLeuer - does that unblock you? If not, reopen!

**Comment by AJLeuer** [comment]
That answers my question about whether I _should_ be able to write to the AppData folder, but there's still the mystery of why I can't find the log file my app supposedly created.
