### ISSUE TITLE
Discussion: Missing classes and types in Microsoft.Foundation

### ISSUE THREAD

**Issue by sjb-sjb** [microsoft/ProjectReunion#399]
Currently many of the WinUI classes and methods depend directly on types from Windows.Foundation. An example would be TypedEventHandler, and I am there are many other examples. 

It would be more logical to eliminate this dependency on Windows by putting the types into Microsoft.Foundation. After all, the objective is to separate the UI classes from Windows. 

Is it planned to make that change, or to just keep using Windows.Foundation namespace in WinUI ? If the latter then what other Windows namespaces are going to remain embedded in WinUI ? 

sjb

**Comment by andrewleader** [comment]
Thanks for posting this, excellent discussion, I'm simply going to move it to a GitHub Discussion because it fits more there :)
