### ISSUE TITLE
Access Denied When Using StorageProviderSyncRootManager

### ISSUE THREAD

**Issue by duke7553** [microsoft/ProjectReunion#402]
**Describe the bug**

Unfortunately, the code below returns an ACCESS_DENIED on the first line. I have broadFileSystemAccess capability granted and the Desktop Extension properly referenced in my app manifest. Other people online are having this same problem, and a [forum post](https://docs.microsoft.com/en-us/answers/questions/152909/access-denied-when-using-storageprovidersyncrootma.html) reply mentioned some team is working to fix this.

```
if (StorageProviderSyncRootManager.IsSupported())
 {
      var syncRoots = StorageProviderSyncRootManager.GetCurrentSyncRoots();
      foreach(StorageProviderSyncRootInfo syncRootInfo in syncRoots)
      {
            var cloudStorageItem = new DriveItem()
            {
                 Root = syncRootInfo.Path as StorageFolder,
                 Text = syncRootInfo.DisplayNameResource,
                 VirtualDriveIconPath = syncRootInfo.IconResource,
                 Path = syncRootInfo.Path.Path,
                 Type = DriveType.VirtualDrive,
             };
             list.Add(cloudStorageItem);
       }
}
```
Here's the stacktrace:

```
Access is denied. (Exception from HRESULT: 0x80070005 (E_ACCESSDENIED))|System.UnauthorizedAccessException: Access is denied. (Exception from HRESULT: 0x80070005 (E_ACCESSDENIED))
at System.StubHelpers.StubHelpers.GetWinRTFactoryObject(IntPtr pCPCMD)
at Windows.Storage.Provider.StorageProviderSyncRootManager.IsSupported()
at Files.Filesystem.DrivesManager.GetVirtualDrivesList(IList`1 list)
at Files.Filesystem.DrivesManager.EnumerateDrives()
at System.Threading.WinRTSynchronizationContextBase.Invoker.InvokeCore()
```

**Steps to reproduce the bug**

1. Reference StorageProviderSyncRootManager anywhere in your desktop-capable UWP app
2. Build/run and see exception at runtime

**Expected behavior**
StorageProviderSyncRootManager should work without failing if the criteria for using this API are met. Especially when checking IsSupported().

**Version Info**

NuGet package version: 
Not using project reunion

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (20251)              | YES   |
| May 2020 Update (19041)            | YES   |
| November 2019 Update (18363)       | YES   |
| May 2019 Update (18362)            | YES   |
| October 2018 Update (17763)        |    |

**Additional context**
Bug report I found elsewhere: https://github.com/MicrosoftDocs/winrt-api/issues/769

**Comment by jonwis** [comment]
@brflynn or @smaillet-ms - can you check into this?

**Comment by andrewleader** [comment]
Thanks for reporting this! This is actually a Windows platform bug and not a Project Reunion bug, so I've filed a bug with the platform team (internal bug #31583004) and asked them to follow up here with any updates.

I'll close this thread since this isn't an active issue with Project Reunion itself, but I appreciate you submitting this detailed report!

If you'd like to track the status of the bug, you could submit this bug report through Feedback Hub and then share your link to your feedback so that I can link it up with the platform bug I created.

**Comment by duke7553** [comment]
@andrewleader Thanks for filing the internal bug with the platform team. I understand why this was closed and opened the separate feedback hub ticket: https://aka.ms/AAb0u1t

**Comment by andrewleader** [comment]
Thanks! We've already got the `transfer-to-platform` label on this bug, so when we decide what to do about OS API bugs, this will be on the list! Thanks for bringing it up though @duke7553!

Just an update on the bug itself - we still don't have a release planned that would include addressing this bug, but it's assigned to the right folks and they saw and acknowleded the bug and added it to their backlog!

**Comment by duke7553** [comment]
@andrewleader Not sure how I missed that. Thank you Andrew!
