### ISSUE TITLE
StorageFile.GetThumbnailAsync sometimes never returns

### ISSUE THREAD

**Issue by benstevens48** [microsoft/ProjectReunion#404]
**Describe the bug**
Calling `StorageFile.GetThumbnailAsync` sometimes never returns. I have come across this situation on my PC which is running out of space (< 8GB left, but > 5GB). For several days, StorageFile.GetThumbnailAsync would never return any time I called it. However, it then started working again of its own accord.

**Steps to reproduce the bug**
See above, using a C# UWP app. It may be tricky to reproduce, because it obviously is related somehow to having a limited amount of disk space left, and even then sometimes doesn't reproduce.

**Expected behavior**
Ideally this method should still work and return a thumbnail. If the thumbnail cannot be cached due to lack of space, then so be it, but ideally it should still generate one. If generating a thumbnail is not possible, it should throw an error, not never return. If it never returns this is very awkward for my app as I limit the number of concurrently generated thumbnails to prevent massive CPU usage. Setting a timeout isn't much of a solution since it would need to be quite large to cover edge cases, but often thumbnails are needed when scrolling through lists of many files in which case they need to be generated in less than 1 second in general.

I expect the bug is probably in the underlying Win32 API, but not sure.

**Version Info**
Using built-in UWP.

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| November 2019 Update (18363)       | Yes   |

**Related bug**
I would like to reiterate my request (made in https://github.com/microsoft/ProjectReunion/issues/8#issuecomment-631095611) that the NeighboringFilesQuery passed to the app by File Explorer should not use the file system indexer, or whatever unreliable method it currently uses. At the moment on my PC, probably due to the limited space and the effect that has on the indexer, NeighboringFilesQuery often contains 0-3 files out of the few hundred that it should contain.

**Comment by andrewleader** [comment]
Thanks for reporting this! This is actually a Windows platform bug and not a Project Reunion bug, so I've filed a bug with the platform team (internal bug #31582984) and asked them to follow up here with any updates.
		
I'll close this thread since this isn't an active issue with Project Reunion itself, but I appreciate you submitting this detailed report!
		
If you'd like to track the status of the bug, you could submit this bug report through Feedback Hub and then share your link to your feedback so that I can link it up with the platform bug I created.

**Comment by benstevens48** [comment]
@andrewleader thanks for filing the issue. I submitted a Feedback Hub report here - https://aka.ms/AAb118c
