### ISSUE TITLE
WPF + .Net 5 + WinRT APIs not yet functional

### ISSUE THREAD

**Issue by Noemata** [microsoft/ProjectReunion#405]
**Describe the bug**

Critical WinRT APIs when consumed from a WPF .Net 5 app are not yet functional. One example is the AddPackageAsync API when used with a Progress<DeploymentProgress>  callback.  The call hangs sometimes.  Sometimes it works.

This was also reported here: https://github.com/dotnet/wpf/issues/4097

**Steps to reproduce the bug**

Here is the essential code:

```
                Progress<DeploymentProgress> progressCallback = new Progress<DeploymentProgress>((op) =>
                {
                    //var appxProgress = new AppxProgress(op.percentage, "...");
                    //progress.Report(appxProgress);
                });

                var pkgManager = new PackageManager();

                // MP! fixme: why do we hang on the await on occasion?
                Debug.WriteLine("Installing package ...");
                DeploymentResult result = await pkgManager.AddPackageAsync(uriToAppx, urisToDependencies, DeploymentOptions.ForceTargetApplicationShutdown).AsTask(progressCallback).WaitOrCancel(stop);
                Debug.WriteLine("Package installed ...");
```

1. Install any given UWP Appx package and you will see instances where "Package Installed..." is never reached (hangs).

A working sample project is located here: https://github.com/Noemata/AppxInstaller

**Expected behavior**

The call should always complete if no exception is raised.

**Screenshots**

n/a

**Version Info**

WPF + .Net 5 + WinRT API access.

NuGet package version: 

n/a

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |  No   |
| May 2020 Update (19041)            |  No   |
| November 2019 Update (18363)       |  Yes   |
| May 2019 Update (18362)            |  No   |
| October 2018 Update (17763)        |  No   |

**Additional context**

This hanging issue is not isolated to just this particular WinRT API.  Other WinRT APIs generate an unexpected exception when privileges are elevated even though the same APIs work with user level privileges (note: not specifically related, just identifying other problems).  The reverse of what you might expect to happen.

Because this API is a bootstrapping API that is essential to getting other things started (Installing an App), it's essential to get this fixed quickly or communicate that WPF + .Net 5 + WinRT isn't yet in a usable form (perhaps call it alpha level functionality).  Removing the preview designation from .Net 5 has implied that we can expect things to work in the context of commercial product development.

**Comment by Noemata** [comment]
After getting an OS update yesterday, the above problem with AddPackageAsync() has gone away. Thanks. The progress indicator works as expected within the WPF UI thread. There are still issues with WinRT APIs crashing when running with elevated privileges, but that's another matter entirely.

I would expect the following to work:

```
var folderPicker = new FolderPicker();
            this.InitializeWinRTChild(folderPicker);

            folderPicker.SuggestedStartLocation = PickerLocationId.DocumentsLibrary;
            folderPicker.FileTypeFilter.Add("*");
            var folder = await folderPicker.PickSingleFolderAsync();

            if (folder != null)
                Setup.InstallDirectory = folder.Path;
```

It doesn't matter what PickerLocationId folder is selected. I'll post a new bug item for this. Mentioning it here since it looks like the right people have eyes on this.

This issue can be closed.

**Comment by Noemata** [comment]
Spoke a little too soon.  With the OS update, the hanging issue is now very rare.  It still happens after dozens of consecutive attempts.  You can use the above repo to test with.  Repeat the install a few dozen times to see the issue.

**Comment by andrewleader** [comment]
Thanks for reporting this Noemata! This is actually a Windows platform bug and not a Project Reunion bug, so I've filed a bug with the platform team (internal bug #31582920) and asked them to follow up here with any updates.

I'll close this thread since this isn't an active issue with Project Reunion itself, but I appreciate you submitting this detailed report!

If you'd like to track the status of the bug, you could submit this bug report through Feedback Hub and then share your link to your feedback so that I can link it up with the platform bug I created.
