### ISSUE TITLE
Developer Kit for Native Arm Binaries

### ISSUE THREAD

**Issue by AathifMahir** [microsoft/ProjectReunion#414]
Hi,

I don't know this a proper place to open this request but on my point this is much needed thing that Microsoft should do as soon as possible and also this request depends on hardware division of Microsoft.

We absolutely need a Arm Developer Kit for testing Arm apps, currently if we need to test Arm Binaries we need to buy much expansive Surface Pro X or Some Expansive devices from Other OEM's

We'd love to see a less expansive device with Arm Processors, in that case we all totally take something like Intel NUC Mini PC that sports Windows 10 on Arm with Qualcomm Snapdragon 8cx or whatever Arm Soc that's compatible with Windows.

**Comment by andrewleader** [comment]
Thanks @AathifMahir, great feedback, we'll share this feedback with our core developer ecosystem teams! Closing this issue as it's not a Reunion-specific issue.
