### ISSUE TITLE
When will the roadmap be updated?

### ISSUE THREAD

**Issue by mrlacey** [microsoft/ProjectReunion#415]
On January 20th, [the WinUI team shared a roadmap announcement](https://youtu.be/MulUg7iD2-s?t=1994) that included details of releases of Project Reunion versions 0.5, 0.8, & 1.0

![WinUI3 roadmap including project Reunion release 0.5 in March 2021, release 0.8 in May 2021, and release 1.0 in October 2021](https://user-images.githubusercontent.com/189547/106619950-02549080-6569-11eb-9219-ca82279943c6.png)

**When will the Project Reunion roadmap be updated to include these releases?
Can these dates (& version numbers) be confirmed here?
In addition to WinUI3, what else will be in these releases?
What can we expect in terms of preview releases prior to these actual releases?**

[The existing roadmap document](https://github.com/microsoft/ProjectReunion/blob/main/docs/roadmap.md) has not been updated in over 6 months and is clearly out of date.
By keeping the roadmap up to date and in sync with other teams that are part of what comes under the "Project Reunion umbrella" you provide confidence that:
- you have a plan, 
- you are following that plan
- we can monitor and track progress
- what you say will ship, will ship (when you say)
- we can plan to adopt new technologies shortly after they are available.

I assume that you want fast adoption of the tools and functionality you release. However, if we can't know what is going to ship (and when) we have to wait until new versions ship before we know what we can use. In turn this means we can't even plan how to adopt any new functionality (let alone implement, test and release apps that use it) until your work is released.
I know slow adoption is not nice. It feels dreadful to put lots of effort into making something new only to see few people use it. Additionally, it reflects badly on the perception of the project as a whole when few people are seen to be using new features. In turn this degradation in the perception of the platform not only hurts you as the producer of the platform, but also us as people (not only developers) who work with it.

**Comment by tfennel** [comment]
Agreed @mrlacey, we owe an update and will work on that this week. Like how many things change at Microsoft 😁, some of the day to day for project reunion has shifted and some of us new folks are still getting ramped up. In the meantime to your questions:

1. When will the Project Reunion roadmap be updated to include these releases? 
**@andrewleader and @dayman40 are working on that this week.** 
2. Can these dates (& version numbers) be confirmed here? 
Well, I mean you know how it goes with dates. We feel good about them right now though, so I'll repeat them again:
**- 0.5 Spring - preview release, supported, including WinUI 3.
- 0.8 Summer - goal to scale up features available. 
- 1.0 Fall - goal to scale out. Fully supported release. May be first release supporting side by side preview and stable release - plan still forming on this.**
3. In addition to WinUI3, what else will be in these releases?
**Too early to state firmly, but some examples would be potentially a Windowing preview in 0.8. Possibly a notifications preview as well. As they firm up we'll get them in the formal roadmap.**
4. What can we expect in terms of preview releases prior to these actual releases?
**Again, plan still forming here, but likely that there won't be preview releases between 0.5 and 0.8. If we get the engineering systems working like we want at 0.8, we'll start rolling some previews of 1.0 after the 0.8 milestone.**

**Comment by dayman40** [comment]
Hi @mrlacey, 

Thank you for checking with us on our roadmap. We really appreciate your time here! As @tfennel said, @andrewleader and I are currently working on it this week and will use this issue to push an update to the roadmap. 

Thanks again.
Dina.

**Comment by dayman40** [comment]
Hi @mrlacey, 

We wanted to get back to you to let you know that we have updated our roadmap so you can now view our latest roadmap Updates [here](https://github.com/microsoft/ProjectReunion/blob/main/docs/roadmap.md). We will continue to work on further refining our roadmap and sharing with you what we're working on and what you can expect in the future. Please let us know if you have any questions, feedback, or any improvements you would like to have.

Thank you,
Dina Ayman.

**Comment by andrewleader** [comment]
Hey @mrlacey, I just wanted to inform you that we had accidentally made a typo on our previous update to the roadmap (saying 1.0 was coming in Q3). We only noticed it now (while publishing the [new updated clearer roadmap](https://github.com/microsoft/ProjectReunion/blob/main/docs/roadmap.md))... 1.0 had always been slated for Q4, but wanted to inform you of that typo and change in case you saw the previous roadmap and were expecting something in Q3!
