### ISSUE TITLE
[uwp] using the MediaComposition.RenderToFileAsync as IAsynOperationWithProgress cause huge memory leaks

### ISSUE THREAD

**Issue by jtorjo** [microsoft/ProjectReunion#421]
Treating the result of `MediaComposition.RenderToFileAsync` as `IAsyncOperationWithProgress` can cause HUGE memory leaks.
In my experiments, for a roughly 30 second file at 640x360, it will be a 150-200 Mb memory leak, while a 90 second file at 1920x1080 can cause a 4-5GB memory leak

**Steps to reproduce the bug**

The following:

	var composition = new MediaComposition();
	...
	var save = composition.RenderToFileAsync(file, MediaTrimmingPreference.Precise, encoding_profile);
	save.Progress = (i, progress) => {
	...
	};
	save.Completed = (i, status) => {
	...
	};

causes the memory leak. If I do the same code as above, but do an `await`, the memory leak goes away. 

	var composition = new MediaComposition();
	...
	await composition.RenderToFileAsync(file, MediaTrimmingPreference.Precise, encoding_profile);

To be clear, even if you have `save.Progress = (i,progress) => {};` and `save.Completed = (i,status) => {}`, the memory leak still happens.

**More details**

While I can't paste my whole application here, my code creates a video file. I do this, more or less like this:

	var clip = MediaClip.CreateFromColor(Colors.Transparent, TimeSpan.FromMilliseconds(duration_ms));
	clip.VideoEffectDefinitions.Add(new VideoEffectDefinition(typeof(SaveVideoEffect).FullName, save_configuration));
	
	var composition = new MediaComposition();
	composition.Clips.Add(clip);

	var  encoding_profile =  MediaEncodingProfile.CreateMp4( quality());
	var folder = await StorageFolder.GetFolderFromPathAsync(Path.GetDirectoryName(model_.commands_array.mp4_name));
	var file = await folder.CreateFileAsync(Path.GetFileName(model_.commands_array.mp4_name), CreationCollisionOption.GenerateUniqueName);
	// ... here, I call the RenderToFileAsync

The `SaveVideoEffect` is a class that will generate each frame of the resulting video.

If the `RenderToFileAsync` call is simply awaited, there's no memory leak. If I treat it as an `IAsyncOperationWithProgress` operation, as shown above, the memory leak appears.

I ended up commenting all the code that would consume any memory, the leaks still appear.

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| May 2020 Update (19041)            |  Yes   |
| November 2019 Update (18363)       | Yes  |
| May 2019 Update (18362)            | Yes  |
| October 2018 Update (17763)        | Not sure  |

**Comment by jonwis** [comment]
I've pinged our media folks, stay tuned!

**Comment by jonwis** [comment]
The team is tracking this as http://task.ms/31627483 (@andrewleader fyi).  They note that the callback fires every 250ms or so, which might be generating lots of GC pressure.  If you do have a minimal reproduction that we can debug please do share. the Team may post here asking more questions as they dig in.

We hope to welcome more of the Media stack to Project Reunion in the future. Until then I'm going to close this issue.

**Comment by jtorjo** [comment]
@jonwis Thanks! I can't access the task.ms link. 

About sharing a debug example - unfortunately it's close to impossible to have a small example, since this is part of a huge project (close to 300K LOC)
