### ISSUE TITLE
Will Project Reunion APIs have an impact on the current UWP Life Cycle's resource management? (example, impact on battery consumption when the app is suspended)

### ISSUE THREAD

**Issue by luisvargascr** [microsoft/ProjectReunion#43]
Some Win32API calls may require extensive use of resources and proper pointer management, I wonder how Project Reunion will handle these cases when Win32 APIs are needed and how these libraries will be optimized to comply with effective resource management that UWP life cycle offers.

**Comment by jesbis** [comment]
#9 is a proposal to bring better UWP-style lifecycle management capabilities to Win32 apps - would that help the scenario you have in mind? Please let us know on the proposal!

**Comment by jonwis** [comment]
Hey @luisvargascr - check out https://github.com/microsoft/wil for the tooling we use.  Specifically, https://github.com/microsoft/wil/wiki/RAII-resource-wrappers which has wrappers & helpers for many existing resources and ways to extend.  Feel free to try it out and file some issues over there.

**Comment by luisvargascr** [comment]
> #9 is a proposal to bring better UWP-style lifecycle management capabilities to Win32 apps - would that help the scenario you have in mind? Please let us know on the proposal!

Yes exactly. That would be pretty cool: lifecycle management... can this also be extended to regular WPF with proposal # 9? I will spend some more time reading about these initiatives.
