### ISSUE TITLE
Make Orca tool open source

### ISSUE THREAD

**Issue by jozefizso** [microsoft/ProjectReunion#430]
I would like to request to open source the Orca tool.

> Orca is a Windows Installer package editor provided as part of the Windows  Installer SDK and designed to provide full access to the database tables that  compose a Windows Installer package.

Orca is a great tool for working with MSI files and making sure we convert MSIs to modern format correctly.

**Comment by jvintzel** [comment]
Transferring since it is not a valid ask for the MSIX SDK

**Comment by cwruss** [comment]
Thanks for the suggestion @jozefizso. Unfortunately we will not be open sourcing the Orca tool at this time.
