### ISSUE TITLE
[MRTCore] MRTCore in WPF: building app fails with "'UAP.props' not found"

### ISSUE THREAD

**Issue by rohanp-msft** [microsoft/ProjectReunion#437]
**Describe the bug**
MRTCore in WPF: building app fails with "'UAP.props' not found"

**Steps to reproduce the bug**
1. Create WPF app.
2. Install the Project Reunion NuGet package (at this time, since the framework packages aren't available yet, you might have to install the TransportPackage, which isn't meant for app consumption, manually; since the name of the props and targets files in the package doesn't match the package name, they won't be automatically imported in the project file on package install)
3. Simply attempt to build the app. It fails with:
```
1>C:\Users\mn\.nuget\packages\microsoft.applicationmodel.resources\0.1.0-ci-20210204-213641\build\Microsoft.ApplicationModel.Resources.PriGen.targets(833,5): error APPX1639: File 'C:\Program Files (x86)\Windows Kits\10\DesignTime\CommonConfiguration\Neutral\UAP.props' not found. See http://go.microsoft.com/fwlink/?LinkID=798187 for more information.
```

**Expected behavior**
App builds successfully.

**Screenshots**
n/a

**Version Info**
Latest version of the Project Reunion TransportPackage NuGet package (support for this type of app needs to be _added_, so the version of the package doesn't matter).

NuGet package version: 
See point above, under Version Info.

Windows version:
Issue is independent of the Windows version.

**Additional context**
This issue was reported by Morten Nielson @dotmorten.

**Comment by rohanp-msft** [comment]
Added @huichen123 as Asignee since he's the one that fixed this. Closing this issue.

**Comment by rohanp-msft** [comment]
This was fixed under https://github.com/microsoft/ProjectReunion/issues/593

**Comment by andrewleader** [comment]
Servicing release `0.5.5` that fixes this issue is available now! You should be able to use Project Reunion non-WinUI features in your WPF MSIX .NET 5 apps now!
