### ISSUE TITLE
Preview 4 - FolderPicker and FilePicker not working / App crashes

### ISSUE THREAD

**Issue by AndyMahub** [microsoft/ProjectReunion#466]
Simple to reproduce:

I have downloaded VisualStudio 2019 Preview Version 16.9 and installed with WinUI 3 preview 4.

I have created a new WinUI Desktop App with .Net 5. 
In the method myButton_Click i have this code:

```csharp
string Filename = "";
var picker = new Windows.Storage.Pickers.FileOpenPicker();
((IInitializeWithWindow)(object)picker).Initialize(System.Diagnostics.Process.GetCurrentProcess().MainWindowHandle);
Windows.Storage.StorageFile file = await picker.PickSingleFileAsync();

and the interface in the same namespace:

[ComImport]
        [Guid("3E68D4BD-7135-4D10-8018-9FB6D9F33FA1")]
        [InterfaceType(ComInterfaceType.InterfaceIsIUnknown)]
        public interface IInitializeWithWindow
        {
            void Initialize(IntPtr hwnd);
        }
```

I build my app, the app starts without errors. After i click on the button, the app crashs with this message:
**Ausnahmefehler bei 0x76E36D21 (combase.dll) in App1.exe: 0xC000027B: Anwendungsinterne Ausnahme (Parameter: 0x1BD90608, 0x00000001)**

Without the interface i receive the message "Invalid Window handle".
The same behavior is with the FolderPicker.

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| No | Yes |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| October 2020 Update (19042)        | Yes   |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

This is my first bug report an i hope this is correct.
Best regards
Andy

**Comment by andrewleader** [comment]
@rkarman this is good feedback to consider for the future with AppWindow (maybe we can make the need for initializeWithWindow go away?). Anyways, closing this issue as this is by-design and expected that you must call initializeWithWindow today.

**Comment by Aloento** [comment]
> > @AndyMahub,
> > I have just tested the code below with Preview 4 bits, and it works for me.
> > ```cs
> >  public sealed partial class MainWindow : Window
> >  {
> >       ...
> > 
> >         private async void myButton_Click(object sender, RoutedEventArgs e)
> >         {
> >             var filePicker = new FileOpenPicker();
> > 
> >             //Get the Window's HWND
> >             var hwnd = this.As<IWindowNative>().WindowHandle;
> > 
> >             //Make folder Picker work in Win32
> > 
> >             var initializeWithWindow = filePicker.As<IInitializeWithWindow>();
> >             initializeWithWindow.Initialize(hwnd);
> >             filePicker.FileTypeFilter.Add("*");
> > 
> >             var folder = await filePicker.PickSingleFileAsync();
> >             myText.Text = folder != null ? folder.Path : string.Empty;
> >         }
> > 
> >         [ComImport]
> >         [Guid("3E68D4BD-7135-4D10-8018-9FB6D9F33FA1")]
> >         [InterfaceType(ComInterfaceType.InterfaceIsIUnknown)]
> >         public interface IInitializeWithWindow
> >         {
> >             void Initialize(IntPtr hwnd);
> >         }
> >         [ComImport]
> >         [InterfaceType(ComInterfaceType.InterfaceIsIUnknown)]
> >         [Guid("EECDBF0E-BAE9-4CB6-A68E-9598E1CB57BB")]
> >         internal interface IWindowNative
> >         {
> >             IntPtr WindowHandle { get; }
> >         }
> > ...
> > }
> > ```
> 
> YES! This works for me! :-) Thank you!
> But, is this a temporarily solution? Or comes a fix for this issue?

But now, it's not working for 0.8

**Comment by andrewleader** [comment]
@Aloento can you explain what's not working? Can you share your full code sample? What exception is being thrown and at what line?

Make sure you're calling `this.As<IWindowNative>().WindowHandle;` from a foreground UI thread from directly within a `Window` class (or pass your window instead of the `this` parameter`, you need to obtain the window handle from a Window class

**Comment by Aloento** [comment]
> @Aloento can you explain what's not working? Can you share your full code sample? What exception is being thrown and at what line?
> 
> Make sure you're calling `this.As<IWindowNative>().WindowHandle;` from a foreground UI thread from directly within a `Window` class (or pass your window instead of the `this` parameter`, you need to obtain the window handle from a Window class

**There is an unhandled exception at 0x76556AB1 (combase.dll) (in Reunion.exe): 0xC000027B: An internal application exception has occurred. (Parameter: 0x1D07C6E0, 0x00000001).**

```
using System;
using System.Runtime.InteropServices;
using Microsoft.UI.Xaml;
using Windows.Storage.Pickers;

// To learn more about WinUI, the WinUI project structure,
// and more about our project templates, see: http://aka.ms/winui-project-info.
namespace Waifu2x_Vulkan_Reunion
{
    public sealed partial class MainWindow : Window
    {
        public MainWindow()
        {
            InitializeComponent();
        }

        private async void MyButton_Click(object sender, RoutedEventArgs e)
        {
            var filePicker = new FileOpenPicker();

            //Get the Window's HWND
            var hwnd = As<IWindowNative>().WindowHandle;

            //Make folder Picker work in Win32

            var initializeWithWindow = FileOpenPicker.As<IInitializeWithWindow>();
            initializeWithWindow.Initialize(hwnd);
            filePicker.FileTypeFilter.Add("*");

            var folder = await filePicker.PickSingleFileAsync();
        }

        [ComImport]
        [Guid("3E68D4BD-7135-4D10-8018-9FB6D9F33FA1")]
        [InterfaceType(ComInterfaceType.InterfaceIsIUnknown)]
        public interface IInitializeWithWindow
        {
            void Initialize(IntPtr hwnd);
        }
        [ComImport]
        [InterfaceType(ComInterfaceType.InterfaceIsIUnknown)]
        [Guid("EECDBF0E-BAE9-4CB6-A68E-9598E1CB57BB")]
        internal interface IWindowNative
        {
            IntPtr WindowHandle { get; }
        }
    }
}
```

**Comment by Aloento** [comment]
> > @Aloento can you explain what's not working? Can you share your full code sample? What exception is being thrown and at what line?
> > Make sure you're calling `this.As<IWindowNative>().WindowHandle;` from a foreground UI thread from directly within a `Window` class (or pass your window instead of the `this` parameter`, you need to obtain the window handle from a Window class
> 
> **There is an unhandled exception at 0x76556AB1 (combase.dll) (in Reunion.exe): 0xC000027B: An internal application exception has occurred. (Parameter: 0x1D07C6E0, 0x00000001).**
> 
> ```cs
> using System;
> using System.Runtime.InteropServices;
> using Microsoft.UI.Xaml;
> using Windows.Storage.Pickers;
> 
> // To learn more about WinUI, the WinUI project structure,
> // and more about our project templates, see: http://aka.ms/winui-project-info.
> namespace Reunion
> {
>     public sealed partial class MainWindow : Window
>     {
>         public MainWindow()
>         {
>             InitializeComponent();
>         }
> 
>         private async void MyButton_Click(object sender, RoutedEventArgs e)
>         {
>             var filePicker = new FileOpenPicker();
> 
>             //Get the Window's HWND
>             var hwnd = As<IWindowNative>().WindowHandle;
> 
>             //Make folder Picker work in Win32
> 
>             var initializeWithWindow = FileOpenPicker.As<IInitializeWithWindow>();
>             initializeWithWindow.Initialize(hwnd);
>             filePicker.FileTypeFilter.Add("*");
> 
>             var folder = await filePicker.PickSingleFileAsync();
>         }
> 
>         [ComImport]
>         [Guid("3E68D4BD-7135-4D10-8018-9FB6D9F33FA1")]
>         [InterfaceType(ComInterfaceType.InterfaceIsIUnknown)]
>         public interface IInitializeWithWindow
>         {
>             void Initialize(IntPtr hwnd);
>         }
>         [ComImport]
>         [InterfaceType(ComInterfaceType.InterfaceIsIUnknown)]
>         [Guid("EECDBF0E-BAE9-4CB6-A68E-9598E1CB57BB")]
>         internal interface IWindowNative
>         {
>             IntPtr WindowHandle { get; }
>         }
>     }
> }
> ```

I know where is the problem.
I should use `using WinRT;`
It works fine.

**Comment by thehaseebahmed** [comment]
I'm facing something similar and not solutions seems to work for me. I'm building a WinUI 3 Desktop app on Windows 11 and in VS2019.

**Code:**
```
// Open a text file.
FileOpenPicker open = new();
open.SuggestedStartLocation = PickerLocationId.DocumentsLibrary;
open.FileTypeFilter.Add("*");

// When running on win32, FileOpenPicker needs to know the top-level hwnd via IInitializeWithWindow::Initialize.
if (Window.Current == null)
{
    IntPtr hwnd = GetActiveWindow();
    IInitializeWithWindow initializeWithWindowWrapper = FileOpenPicker.As<IInitializeWithWindow>();
    initializeWithWindowWrapper.Initialize(hwnd);
}

var files = await open.PickMultipleFilesAsync();
```

**Exception:**
Specified cast is not valid.

**Screenshot:**
![image](https://user-images.githubusercontent.com/11260154/125167516-67687e00-e1ba-11eb-989c-e12f505cd3e1.png)

**Comment by pavll** [comment]
@thehaseebahmed 
I had the same problem, the same workaround everywhere, but it didn't work for me. The solution is to add **`using WinRT;`**. Then the `myPicker.As<IIInitializeWithWindow>();` works.

**Comment by nickrandolph** [comment]
It appears the same work around is now required for MessageDialog. I'm still not sure I understand why this is "by-design" and if it is, I'm not sure I agree with the design. 
@andrewleader is there any way we can track an on-going issue to tidy this up in the long term? Surely there must be a more intuitive way so that we don't end up with code being littered with As<IInitializeWithWindow>() calls.

**Comment by jonwis** [comment]
Longer term, we're looking into adding `Microsoft.Windows.*` variants of these types, so you'd say like `var open = Microsoft.Windows.Storage.Pickers.FileOpenPicker(targetWindowId)` (where targetWindowId is a `Windows.UI.WindowId` you acquired from either `Window.Current` or somewhere else.)  See also #370 for a longer discussion of Windowing in the WinApSDK and how we're looking to slot it in.

There's a whole group of these "windowing interop helpers" that are relevant - anything that took an "implicit CoreWindow" needs to be updated.  See https://github.com/AdamBraden/WindowsInteropWrappers for a start at some.

**Comment by mcka-dev** [comment]
I have just tested the small code below, and it works for me.
```C#
private async void MyButton_Click(object sender, RoutedEventArgs e)
{
  var filePicker = new FileOpenPicker();

  // Pass in the current WinUI window and get its handle
  var hwnd = WinRT.Interop.WindowNative.GetWindowHandle(this);     
  WinRT.Interop.InitializeWithWindow.Initialize(filePicker, hwnd);

  filePicker.FileTypeFilter.Add("*");

   // Now you can call methods on filePicker
  var file = await filePicker.PickSingleFileAsync();
}
```

Without writing  `Guid("3E68D4BD-7135-4D10-8018-9FB6D9F33FA1")`

Wiki [Call WinRT COM interop interfaces from .NET 5+ apps](https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/winrt-com-interop-csharp)

**Comment by Aloento** [comment]
> I have just tested the small code below, and it works for me.
> 
> ```cs
> private async void MyButton_Click(object sender, RoutedEventArgs e)
> {
>   var filePicker = new FileOpenPicker();
> 
>   // Pass in the current WinUI window and get its handle
>   var hwnd = WinRT.Interop.WindowNative.GetWindowHandle(this);     
>   WinRT.Interop.InitializeWithWindow.Initialize(filePicker, hwnd);
> 
>   filePicker.FileTypeFilter.Add("*");
> 
>    // Now you can call methods on filePicker
>   var file = await filePicker.PickSingleFileAsync();
> }
> ```
> 
> Without writing `Guid("3E68D4BD-7135-4D10-8018-9FB6D9F33FA1")`
> 
> Wiki [Call WinRT COM interop interfaces from .NET 5+ apps](https://docs.microsoft.com/en-us/windows/apps/desktop/modernize/winrt-com-interop-csharp)

Using WinUI3, you'd better do like this:
WinRT.Interop.WindowNative.GetWindowHandle(**App.MainWindow**);

**Comment by orapps44** [comment]
I've tried all your proposal, unfortunnately none of them works on my side (WUINUI3 + .net 6.0).

I'm pretty disapointed to see even basics aren't fully supported yet...

**Comment by angelazhangmsft** [comment]
@orapps44 - do you have more information on the issues you ran into? There is a code sample for picker objects in the article [call interop APIs from a .NET 5+ app](https://docs.microsoft.com/windows/apps/desktop/modernize/winrt-com-interop-csharp). Feel free to file a new issue if you ran into problems following those docs.

**Comment by Jared-Henderson** [comment]
What if we are trying to do this from something like a UserControl that doesn't have access to the Window? In my case it's a UserControl within a Page within a Frame, would I have to pass the Window handle all the way down the chain?

**Comment by KenionX** [comment]
> WinRT.Interop.WindowNative.GetWindowHandle(**App.MainWindow**);

    private async void LoadFromFile(object sender, RoutedEventArgs e)
    {
        var fPicker = new FileOpenPicker();

        var handle = WinRT.Interop.WindowNative.GetWindowHandle(**ABootstrap.Resolve<MainWindow>()**);
        WinRT.Interop.InitializeWithWindow.Initialize(fPicker, handle);

        fPicker.FileTypeFilter.Add("*");

        var selected = await fPicker.PickSingleFileAsync();
    }

Replace ABootstrap.Resolve<MainWindow>() with a reference to your MainWindow, in my case I use dependencie injection to aquire it from everywhere.. you can just make a static reference if you like

**Comment by KenionX** [comment]
> I've tried all your proposal, unfortunnately none of them works on my side (WUINUI3 + .net 6.0).
> 
> I'm pretty disapointed to see even basics aren't fully supported yet...

    private async void LoadFromFile(object sender, RoutedEventArgs e)
    {
        var fPicker = new FileOpenPicker();

        var handle = WinRT.Interop.WindowNative.GetWindowHandle(ABootstrap.Resolve<MainWindow>());
        WinRT.Interop.InitializeWithWindow.Initialize(fPicker, handle);

        fPicker.FileTypeFilter.Add("*");

        var selected = await fPicker.PickSingleFileAsync();
    }

Replace **ABootstrap.Resolve<MainWindow>()** with a reference to your MainWindow, in my case I use dependency injection to aquire it from everywhere.. you can just make a static reference if you like

**Comment by marb2000** [comment]
@KenionX, are you using the latest version of the WinAppSDK? For example, I have installed the VS2022 17.1 and I selected the Windows App SDK project templates in the .NET Visual Studio Workload.  I  just replaced the default ButtonClick event that comes from the Blank app within your code, and it works well.

**Comment by bogdan-patraucean** [comment]
@marb2000 it does not work on WASDK 1.1 preview 3. Tried same code

```
private async void Button_Click(object sender, RoutedEventArgs e)
    {
        var picker = new FileOpenPicker();
        picker.FileTypeFilter.Add("*");

        InitializeWithWindow.Initialize(picker, App.MainWindow.GetHandle());

        var file = await picker.PickSingleFileAsync();
    }
```

GetHandle is an extension method that calls WinRT behind.

I use it in a ContentDialog that's attached to the XamlRoot of the MainWindow.

**Comment by cody3b** [comment]
Running into issues when applying this solution to FileSavePicker. Win UI 3 + .NET 5/6/7 + WASDK last 10 versions tested. No issues with FileOpenPicker though.
