### ISSUE TITLE
Question: What place has .NET Native after Project Reunion

### ISSUE THREAD

**Issue by pjmlp** [microsoft/ProjectReunion#53]
Apparently the long term roadmap will be to merge Win32 and UWP worlds into a common development experience.

Given the newly introduced C#/WinRT and the ONE .NET effort announced at BUILD, where does it leave .NET Native in a Project Reunion world?

**Comment by mveril** [comment]
For me .NET Native should be deleted

**Comment by Gavin-Williams** [comment]
The only way .Net Native should survive is if it's available to .Net 5. Are we going to reunite or what? Or are we going to still be in the same situation in 2 years time as we are now, using all these different frameworks and all complaining about how support is lacking for the particular variant we are stuck on. Lets get this sorted ..

.Net 5 and choose JIT or AOT at config. done.

**Comment by prayaas-a** [comment]
AOT/precompilation support should be opt-in and made available in v5.
.NET teams have worked on that in numerous projects now including CoreRT and WebAssembly. I hope it makes it to .NET 5.x because the performance boost can be huge.

**Comment by saint4eva** [comment]
> Now obviously .NET Core 4 materialized into .NET 5 but this makes me think it's on the burner for sooner or later.

The pandemic interfered with the roadmap, so it would likely be in .NET 6

**Comment by stevewri** [comment]
Does #105 address this question?
