### ISSUE TITLE
Fix build warnings during BuildMRT task in the CI/Pipeline

### ISSUE THREAD

**Issue by DrusTheAxe** [microsoft/ProjectReunion#571]
The CI/Pipeline produces multiple warnings during the BuildMRT step

Review any recent pipeline build for details. For instance https://dev.azure.com/ms/ProjectReunion/_build/results?buildId=146478&view=results has multiple warnings including

```
LINK(0,0): Warning LNK4075: ignoring '/INCREMENTAL' due to '/LTCG' specification

C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets(1460,5): Warning MSB8019: This build is consuming a component "D:\a\1\s\BuildOutput\Release\x86\MRM\MRM.lib" that is not packaged because the component is not coming from a Windows Store app project "D:\a\1\s\dev\MRTCore\mrt\core\src\MRM.vcxproj".

C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(2123,5): Warning MSB3271: There was a mismatch between the processor architecture of the project being built "MSIL" and the processor architecture, "x86", of the implementation file "D:\a\1\s\BuildOutput\Release\x86\Microsoft.ApplicationModel.Resources\Microsoft.ApplicationModel.Resources.dll" for "D:\a\1\s\BuildOutput\Release\x86\Microsoft.ApplicationModel.Resources\Microsoft.ApplicationModel.Resources.winmd". This mismatch may cause runtime failures. Please consider changing the targeted processor architecture of your project through the Configuration Manager so as to align the processor architectures between your project and implementation file, or choose a winmd file with an implementation file that has a processor architecture which matches the targeted processor architecture of your project.

C:\Program Files (x86)\Microsoft SDKs\UWPNuGetPackages\microsoft.net.native.compiler\2.2.8-rel-28605-00\tools\Microsoft.NetNative.targets(801,5): Warning : ILTransform : warning ILT0010: Could not find assembly 'System.Xml.XPath.XmlDocument, Version=4.0.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' referenced by 'Microsoft.TestPlatform.Utilities'.
```

**Comment by axelandrejs** [comment]
@DrusTheAxe @EHO-makai @huichen123 the first one is a long-standing issue. I don't know how to make VS happy here. We are building a regular win32 DLL that we then consume from our WinRT projection DLL. The WinRT build system seems to still have ties to UWP hence the complaint. Any suggestions for making that go away would be welcome.

The other two I don't recall seeing in the past.

**Comment by DrusTheAxe** [comment]
> the first one is a long-standing issue...The other two I don't recall seeing in the past.

Which first one - there's 4 issues :P

Did you mean the 2nd one:

C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets(1460,5): Warning MSB8019: This build is consuming a component "D:\a\1\s\BuildOutput\Release\x86\MRM\MRM.lib" that is not packaged because the component is not coming from a Windows Store app project "D:\a\1\s\dev\MRTCore\mrt\core\src\MRM.vcxproj".

Would this fix it? https://stackoverflow.com/questions/14194277/windows-store-apps-add-project-reference-warning#14197617

@BenJKuhn may have more ideas

**Comment by axelandrejs** [comment]
I thought I tried that but it had some negative side effect. But we can give it another spin.
