### ISSUE TITLE
Update ProjectReunion to use UCRT

### ISSUE THREAD

**Issue by DrusTheAxe** [microsoft/ProjectReunion#573]
MRM.vcxproj has this for Debug builds

```
  <ItemDefinitionGroup Condition="'$(Configuration)'=='Debug'">
    <ClCompile>
      <!-- We use MultiThreadedDebug, rather than MultiThreadedDebugDLL, to avoid DLL dependencies on VCRUNTIME140d.dll and MSVCP140d.dll. -->
      <RuntimeLibrary>MultiThreadedDebug</RuntimeLibrary>
      <PreprocessorDefinitions>_DEBUG;%(PreprocessorDefinitions)</PreprocessorDefinitions>
      <Optimization>Disabled</Optimization>
      <WarningVersion>18</WarningVersion>
    </ClCompile>
    <Link>
      <!-- Link statically against the runtime and STL, but link dynamically against the CRT by ignoring the static CRT
           lib and instead linking against the Universal CRT DLL import library. This "hybrid" linking mechanism is
           supported according to the CRT maintainer. Dynamic linking against the CRT makes the binaries a bit smaller
           than they would otherwise be if the CRT, runtime, and STL were all statically linked in. -->
      <IgnoreSpecificDefaultLibraries>%(IgnoreSpecificDefaultLibraries);libucrtd.lib</IgnoreSpecificDefaultLibraries>
      <AdditionalOptions>%(AdditionalOptions) /defaultlib:ucrtd.lib</AdditionalOptions>
    </Link>
  </ItemDefinitionGroup>
```

and this similar snippet for Release builds

```
  <ItemDefinitionGroup Condition="'$(Configuration)'=='Release'">
    <ClCompile>
      <!-- We use MultiThreaded, rather than MultiThreadedDLL, to avoid DLL dependencies on VCRUNTIME140.dll and MSVCP140.dll. -->
      <RuntimeLibrary>MultiThreaded</RuntimeLibrary>
      <PreprocessorDefinitions>NDEBUG;%(PreprocessorDefinitions)</PreprocessorDefinitions>
      <WarningVersion>18</WarningVersion>
    </ClCompile>
    <Link>
      <!-- Link statically against the runtime and STL, but link dynamically against the CRT by ignoring the static CRT
           lib and instead linking against the Universal CRT DLL import library. This "hybrid" linking mechanism is
           supported according to the CRT maintainer. Dynamic linking against the CRT makes the binaries a bit smaller
           than they would otherwise be if the CRT, runtime, and STL were all statically linked in. -->
      <IgnoreSpecificDefaultLibraries>%(IgnoreSpecificDefaultLibraries);libucrt.lib</IgnoreSpecificDefaultLibraries>
      <AdditionalOptions>%(AdditionalOptions) /defaultlib:ucrt.lib</AdditionalOptions>
    </Link>
  </ItemDefinitionGroup>
```

ProjectReunion projects should use the UCRT like MRTCore does. `DIR *.vcxproj /s /b` to find them all

**Comment by riverar** [comment]
And they should definitely not be statically linked in, for security reasons.

**Comment by jefgen** [comment]
IIRC, I think this was done for MRTCore based on the changes that I made for MS-ICU here:
https://github.com/microsoft/icu/blob/master/icu-patches/patches/012-MSFT-Patch-StaticLink_VCRuntime_VCStartup_STL_but_DynamicLink_UCRT.patch

This statically links the VCRuntime (`libvcruntime.lib`), VCStartup (`libcmt.lib`), and STL/MSVCP (`libcpmt.lib`), but dynamically links to the UCRT (`ucrt.lib`).

The UCRT (C Runtime library) `ucrtbase.dll` is included in Windows 10 and above as an OS component. (See https://docs.microsoft.com/cpp/c-runtime-library/crt-library-features ). However, the `vcruntime*.dll` and `msvcp*.dll` files are only available via the Visual C++ Redistributable (VC Redist) -- and the Redist must be installed manually beforehand.

By linking this way you can still use the OS provided/serviced UCRT, but avoid the need to preinstall the VC Redist. (This is also how .NET Core ships as well).

So perhaps the question is: Does ProjectReunion require the VC Redist to be preinstalled?

If the answer is yes, then you could likely use dynamic linking everything.
Whereas if the answer is no, then static linking the runtime/STL but dynamic linking the UCRT is better than static linking everything.

**Comment by riverar** [comment]
@jefgen Interesting, thanks for the context!

**Comment by Scottj1s** [comment]
Hybrid linking is a great solution for maintaining UCRT dynamic linkage and servicing, while relieving a binary from CRT redist complexity.  The one risk here is whether any static CRT/STL code is attempting to call WACK-prohibited imports.  That can be assessed on a case by case basis.
