### ISSUE TITLE
Crash while creating Regex.

### ISSUE THREAD

**Issue by SenthilKumaranRajan** [microsoft/ProjectReunion#603]
Crash While creating Regex.

string validator;
Regex regex;
public MainPage()
{
   this.InitializeComponent();
   validator = "^[a-zA-Z0-9_]*$";
    regex = new Regex(validator);
}

**Comment by andrewleader** [comment]
Closing as dupe of #599 (these are all related to resource loading issues on Windows 10 18363 and lower and tracking with 599).
