### ISSUE TITLE
Teach build pipeline to create Metadata text files for use by projects

### ISSUE THREAD

**Issue by DrusTheAxe** [microsoft/ProjectReunion#610]
The build pipeline defines the build metadata (version, release vs prerelease, etc) and creates MSIX packages using this information but some projects need this information during their build (e.g. DynamicDependencies, Bootstrapper, Installer).

The build process needs to push this information to the ProjectReunion repository for use when building certain components.

This information is for use by the build pipeline. It's NOT used for inner-loop development of ProjectReunion.sln.

[Update DynamicDependencies use build information (version, package names, DDLM CLSID, etc) #561](https://github.com/microsoft/ProjectReunion/issues/561) depends on this information.

# Metadata Files

Generate files containing metadata about the build at the start of the build process.
Push these files to ProjectReunion's repository when the Aggregator kicks off building `ProjectReunion.sln`

SUGGESTION: Push the metadata files to the `temp` directory e.g. `temp\Metadata-x64.json`.
ALTERNATIVE: Invent a new directory for build generated files (`build\generated`?) and add to `.gitignore`

## Content

Metadata includes:
* Target version
* Flavor(?) -- Release or Prerelease (or possibly Nightly, Dev, Canary, Alpha, Beta, RC, and/or other terms in the future)
* DDLM CLSID -- unique CLSID per version+architecture. Used at compile time instead of instead of “32E7CF70-038C-429a-BD49-88850F1B4A11” (default compiled into DDLM code for inner-loop)
* MSIX package names

`Flavor` -- what term are we using for this property?

##  Files

* `Metadata-<architecture>.json`
* `Metadata-<architecture>.h`

where `<architecture>` = x86 | x64 | arm64

Generate metadata as JSON and .h files. Most consumers can directly use constants defined in the .h. The .json file is needed for more complex scenarios (script to the rescue!)

### Generate .H must be C and RC.EXE Friendly

The .h file MUST be directly `#include`-able when compiling C, C++ and Resource (*.rc) files.

### Metadata-x64.json

```
{
    "Version" : {
        "Version" : "0.8.0.0",
        "Major" : 0,
        "Minor" : 8,
        "Build" : 0,
        "Revision" : 0
    },
    "Architecture" : "x64",
    "Flavor" : "Prerelease",		<== or "Release"
    "MSIX" : {
        "Framework" : {
            "Name" : {
                "Prefix" : "Microsoft.ProjectReunion.Foundation",
                "Base" : "Microsoft.ProjectReunion.Foundation-0.8",
                "Full" : "Microsoft.ProjectReunion.Foundation-0.8-Prerelease"
            },
            "PackageFamilyName" : "Microsoft.ProjectReunion.Foundation-0.8-Prerelease_8wekyb3d8bbwe"
            "PackageFullName" : "Microsoft.ProjectReunion.Foundation-0.8-Prerelease_0.8.0.0_x64__8wekyb3d8bbwe"
        }
        "Main" : {
            "Name" : {
                "Prefix" : "Microsoft.ProjectReunion.Main",
                "Base" : "Microsoft.ProjectReunion.Main-0.8",
                "Full" : "Microsoft.ProjectReunion.Main-0.8-Prerelease"
            },
            "PackageFamilyName" : "Microsoft.ProjectReunion.Main-0.8-Prerelease_8wekyb3d8bbwe"
            "PackageFullName" : "Microsoft.ProjectReunion.Main-0.8-Prerelease_0.8.0.0_x64__8wekyb3d8bbwe"
            },
        "DDLM" : {
            "Name" : {
                "Prefix" : "Microsoft.ProjectReunion.DDLM",
                "Base" : "Microsoft.ProjectReunion.DDLM-0.8.0.0-x64",
                "Full" : "Microsoft.ProjectReunion.DDLM-0.8.0.0-x64-Prerelease"
            }
        }
    }
    "DynamicDependencies" : {
        "LifetimeManager" : {
            "CLSID" : "…clsid…"
        }
    }
}
```

### Metadata-x64.h

```
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See LICENSE in the project root for license information.

#ifndef __METADATA_X64_H__
#define __METADATA_X64_H__

#define PROJECTREUNION_VERSION          0x0000000800000000llu
#define PROJECTREUNION_VERSION_MAJOR    0
#define PROJECTREUNION_VERSION_MINOR    8
#define PROJECTREUNION_VERSION_BUILD    0
#define PROJECTREUNION_VERSION_REVISION 0

#define PROJECTREUNION_VERSION_STRING   "0.8.0.0"

#define PROJECTREUNION_ARCHITECTURE_STRING    "x64"

#define PROJECTREUNION_FLAVOR_STRING    "Prerelease"

#define PROJECTREUNION_MSIX_FWK_PACKAGE_NAME_PREFIX    "Microsoft.ProjectReunion.Foundation"
#define PROJECTREUNION_MSIX_FWK_PACKAGE_NAME_BASE      "Microsoft.ProjectReunion.Foundation-0.8"
#define PROJECTREUNION_MSIX_FWK_PACKAGE_NAME_FULL      "Microsoft.ProjectReunion.Foundation-0.8-Prerelease"

#define PROJECTREUNION_MSIX_MAIN_PACKAGE_NAME_PREFIX   "Microsoft.ProjectReunion.Main"
#define PROJECTREUNION_MSIX_MAIN_PACKAGE_NAME_BASE     "Microsoft.ProjectReunion.Main-0.8"
#define PROJECTREUNION_MSIX_MAIN_PACKAGE_NAME_FULL     "Microsoft.ProjectReunion.Main-0.8-Prerelease"

#define PROJECTREUNION_MSIX_DDLM_PACKAGE_NAME_PREFIX   "Microsoft.ProjectReunion.DDLM "
#define PROJECTREUNION_MSIX_DDLM_PACKAGE_NAME_BASE     "Microsoft.ProjectReunion.DDLM-0.8.0.0-x64"
#define PROJECTREUNION_MSIX_DDLM_PACKAGE_NAME_FULL     "Microsoft.ProjectReunion.DDLM-0.8.0.0-x64-Prerelease"

#define PROJECTREUNION_DDLM_CLSID       "…clsid…"

#endif // __METADATA_X64_H__
```

**Comment by riverar** [comment]
If [GitVersion suggestion is implemented](https://github.com/microsoft/ProjectReunion/pull/597#pullrequestreview-614900618), most of this metadata could be automatically generated during CI and inner-loop dev (if desired). This requires, however, a stable repository layout and some [configuration](https://gitversion.net/docs/reference/configuration)/[planning](https://gitversion.net/docs/learn/how-it-works).

**Comment by DrusTheAxe** [comment]
Completed
