### ISSUE TITLE
In C#/.NET projects, image and resw files are not automatically picked up by the PRI in all cases.

### ISSUE THREAD

**Issue by rohanp-msft** [microsoft/ProjectReunion#613]
**Image files**
With a C#/.NET project, regardless of whether a new image file is created in the project or an preexisting one is added to the project, the Build Action will be None (with one exception which is described below the image). It needs to be Content. See image below.

![image_ba_2](https://user-images.githubusercontent.com/35987549/111851994-a2286c80-88d2-11eb-8e60-56c817efaf2d.png)

The exception:
If the preexisting images are placed in a folder called Assets\, the Build Action property for them is automatically set to Content. If they are placed in a folder with a different name, it isn't. (If the image is placed in the root project directory, Build Action is still None).
If a new image is created using Add New Item, the Build Action is None regardless of where the image file is placed. (I don’t think anyone is going to create a new image file like this though.)

**.resw files**
With a C#/.NET project:
- if a _preexisting_ .resw file is added to the project, the Build Action is None. It needs to be PRIResource
- if a new .resw file is created, the Build Action will be PRIResource already (this is because the Project Reunion VSIX is used here and that sets the property correctly).

**Workaround documentation**
The manual steps needed by the app dev to work around this are documented in the Note here:
Manage resources MRT Core (Project Reunion) | Microsoft Docs

**Environment**:
Project Reunion v0.5.0 VSIX and NuGet.
VS 2019 Preview.

**Non-issue**:
The C++ v0.5.0 Project Reunion projects.

**Comment by riverar** [comment]
@rohanp-msft your write up appears to be missing images

**Comment by rohanp-msft** [comment]
> @rohanp-msft your write up appears to be missing images

@riverar Thanks, Rafael! I've fixed that (and improved the description too).

**Comment by huoyaoyuan** [comment]
This is https://github.com/microsoft/microsoft-ui-xaml/issues/3648 .

**Comment by rohanp-msft** [comment]
> This is [microsoft/microsoft-ui-xaml#3648](https://github.com/microsoft/microsoft-ui-xaml/issues/3648) .

Hi @huoyaoyuan, yes it is. The issue wasn't fully understood until recently. Previously I thought it was upgrade specific. Feel free to dupe microsoft/microsoft-ui-xaml#3648 to this.

@JeanRoca as FYI

**Comment by rohanp-msft** [comment]
Fixed by https://github.com/microsoft/ProjectReunion/pull/771
