### ISSUE TITLE
Question: How do I detect media format codec support?

### ISSUE THREAD

**Issue by maxkatz6** [microsoft/ProjectReunion#64]
My application uses media playback which requires installed "[MPEG-2 Video Extension](https://www.microsoft.com/en-us/p/mpeg-2-video-extension/9n95q1zzpmh4)".
I know, there is API in Windows.Management.Deployment.PackageManager to find package by name for current user, and it works for me as expected. But it requires additional "packageQuery' restricted capability. I understand reason for that capability - there are a lot of dangerous APIs in PackageManager. But in my case I need just "true/false" result for one specific package, and open Store page if it isn't installed.

**Comment by maxkatz6** [comment]
It also seems like I can use StoreContext.RequestPurchaseAsync to ask user to install MPEG2 extension.
But it returns error code "0x803F6108" for sideloaded applications, so it will not work in my case.

**Comment by jonwis** [comment]
This is similar to #60 but specifically about a particular codec.

There are definitely a bunch of powerful APIs on PackageManager, but "Query" only lets you enumerate packages the user has installed - not actually modify them.

@aklemets  or @DavidS-msft - any sage advice here?

@maxkatz6, do you have a sample of the code that's not working?

**Comment by aklemets** [comment]
You can use MFTEnumEx to check if a MPEG-2 video decoder is installed, and prompt the user to download the MPEG-2 Video Extension if it is not. The format to query for is MFVideoFormat_MPEG2.

Something like this should work:

#include <mfapi.h>
 
bool IsMpeg2DecoderAvailable()
{
    MFT_REGISTER_TYPE_INFO inputType = { MFMediaType_Video, MFVideoFormat_MPEG2 };
    IMFActivate* pActivates = nullptr;
    UINT32 cActivates = 0;
    (void)MFTEnumEx(MFT_CATEGORY_VIDEO_DECODER, MFT_ENUM_FLAG_SYNCMFT, &inputType, nullptr, &pActivates, &cActivates);
    for (UINT32 i = 0; i < cActivates; i++)
    {
        pActivates[i]->Release();
    }
    CoTaskMemFree(pActivates);
    return cActivates != 0;
}

**Comment by maxkatz6** [comment]
@aklemets thanks! I will try it later.
By the way, there are a lot of APIs which is available only in C++ world (or with pinvoke in c#).
Is it something that also could be covered with ProjectReunion? Or this is job for [CsWinRT](https://github.com/microsoft/CsWinRT) ?

@jonwis 
If you are asking me about StoreContext.RequestPurchaseAsync, then it doesn't work with a reason: [0x803F6108](https://docs.microsoft.com/en-us/windows/uwp/monetize/error-codes-for-store-operations):
> The in-app purchase could not be completed because the app license is missing information. This error can occur when you side-load your app. To resolve this issue, uninstall the app and then reinstall it from the Store to refresh the app license

My app isn't registered in the store, so I understand, why it doesn't work.

**Comment by jonwis** [comment]
Ideally yes, we'd provide you a Project Reunion flavored wrapper, which would avoid the direct p/invoke along with the associated cleanup.  Instead, we'd provide an API that wraps the C++ in metadata which you can then use projected to your favorite language (including cswinrt!)

**Comment by benstevens48** [comment]
Not sure if this helps, but I think there is already a way to query for installed codecs in UWP - see <https://docs.microsoft.com/en-gb/windows/uwp/audio-video-camera/codec-query?view=dynamics-usd-3>.

**Comment by maxkatz6** [comment]
@benstevens48 it seems what I exactly need! Thanks.
