### ISSUE TITLE
Question: UWP toolchain updates or MSIX for UWP without .NET Native

### ISSUE THREAD

**Issue by mqudsi** [microsoft/ProjectReunion#65]
I have been playing around with Project Reunion and giving my feedback on the various components' GitHub repositories for the past couple of months, and have successfully created many different types of applications (WPF Core, WPF XAML host for WinUI 3, etc); however I've run into an issue with creating "traditional" UWP applications that consume all the various new APIs - it seems that the tooling for `Microsoft.NETCore.UniversalWindowsPlatform` has not caught up with all the improvements and attempting to run such a UWP app after it's been compiled to .NET Native throws `EEFileLoadException` on `System.Private.CoreLib` as a result.

This leads me to a question and what is either a bug or a feature request:

1) Will UWP tooling be updated to support the latest language features so that using these .NET Standard libraries (e.g. `System.Text.Json`) will "just work" in UWP applications?

2) UWP has always required compilation to .NET Native to be uploaded to the Microsoft Store (but it can be deployed without AOT if the package is instead side-loaded). I thought I could use MSIX to create a sparse package that contained the *non* .NET Native/non-AOT UWP application; e.g. with a solution tree like this:

```
Master Solution
|--UWP Project
|--Package Project
   |--Reference to UWP Project
```
where the UWP project does *not* have the "Compile with .NET Native toolchain" option checked for any of its configurations.

This does not seem to be a supported configuration as it causes the following error when compiling the sparse package project:

> 2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Microsoft\DesktopBridge\Microsoft.DesktopBridge.targets(646,5): error : Could not find a recipe file for the referenced UWP application at 'C:\Users\mqudsi\git\MySolution\MyProject\bin\x64\Release\Upload\MyProject.build.appxrecipe'. Please build the project.

**Comment by stevewri** [comment]
Does #105 cover this?

**Comment by stevewri** [comment]
Closing and tracking through #105
