### ISSUE TITLE
SpringVector3NaturalMotionAnimation.FinalValue throws System.InvalidCastException

### ISSUE THREAD

**Issue by laolarou726** [microsoft/ProjectReunion#675]
**Describe the bug**
When I trying to assign the Vector3 value as the final value for the SpringVector3NaturalMotionAnimation. It throws the following exception: System.InvalidCastException: 'Specified cast is not valid.'

**Steps to reproduce the bug**
1. Create a new blank project using ProjectReunion
2. Using the SpringVector3NaturalMotionAnimation
```c#
var ani = Compositor.CreateSpringVector3Animation();
ani.Target = "Translation";
ani.FinalValue = Vector3.Zero;
```

**Expected behavior**
SpringVector3NaturalMotionAnimation will be initialized as expected.

**Screenshots**
![image](https://user-images.githubusercontent.com/25716486/113263320-313a7900-9304-11eb-942a-4a8e7dafa772.png)
![image](https://user-images.githubusercontent.com/25716486/113263433-59c27300-9304-11eb-89cc-d5d281e1103a.png)
![image](https://user-images.githubusercontent.com/25716486/113263473-66df6200-9304-11eb-95ee-bc53d0c72c28.png)

**Version Info**
OS version: Windows 10 20H2 19042.906
Experience Pack: Windows Feature Experience Pack 120.2212.551.0

NuGet package version: 
+ Microsoft.ProjectReunion v0.5.0
+ Microsoft.ProjectReunion.Foundation v0.5.0
+ Microsoft.ProjectReunion.WinUI v0.5.0

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (19042)              |  Yes   |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |

**Comment by andrewleader** [comment]
Hey @jeffstall can you take a look at this? Thanks!

**Comment by manodasanW** [comment]
@laolarou726 This looks like an issue that was fixed in a CsWinRT update.  Can you update to the latest .NET SDK that came out today (5.0.202) and try again.

**Comment by laolarou726** [comment]
> @laolarou726 This looks like an issue that was fixed in a CsWinRT update. Can you update to the latest .NET SDK that came out today (5.0.202) and try again.

The casting problem seems resolved. But the Visual Studio keeping throws the exception below:

![image](https://user-images.githubusercontent.com/25716486/113815136-451f2880-97a5-11eb-860c-330a76099727.png)

When I click the continue button, the application window will show and nothing seems wrong.

**Comment by marb2000** [comment]
I believe this is a well-known issue of the C#/WinRT projections that will be solved soon. @manodasanW  and @Scottj1s amd I right?

**Comment by laolarou726** [comment]
> I believe this is a well-known issue of the C#/WinRT projections that will be solved soon. @manodasanW and @Scottj1s amd I right?

Thank you so much!

**Comment by manodasanW** [comment]
The initial cast issue was definitely a C#/WinRT issue and it seems to be gone after the .NET SDK update.  The other may or may not be, but looks to be a first chance exception and doesn't actually crash the app. @laolarou726 am I right?  Do you have a stack from when the first chance exception hits and error code?

**Comment by marb2000** [comment]
@manodasanW what .NET SDK version do we need to avoid this exception?

**Comment by manodasanW** [comment]
@marb2000 .NET SDK 5.0.202 has the fix for the invalid cast exception for vector3 from the original post.
