### ISSUE TITLE
Proposal: Add Windows PE support for Unpackaged Desktop Apps

### ISSUE THREAD

**Issue by MouriNaruto** [microsoft/ProjectReunion#676]
# Proposal: Add Windows PE support for Unpackaged Desktop Apps

## Summary

Windows PE (WinPE) is a small operating system used to install, deploy, and repair Windows 10 for desktop editions (Home, Pro, Enterprise, and Education), Windows Server, and other Windows operating systems. 

- Set up your hard drive before installing Windows.
- Install Windows by using apps or scripts from a network or a local drive.
- Capture and apply Windows images.
- Modify the Windows operating system while it's not running.
- Set up automatic recovery tools.
- Recover data from unbootable devices.
- Add your own custom shell or GUI to automate these kinds of tasks.

![image](https://user-images.githubusercontent.com/10867563/113278619-ba59ac00-9314-11eb-90be-cae84afc1cbd.png)

For more information, please read https://docs.microsoft.com/en-us/windows-hardware/manufacture/desktop/winpe-intro.

## Rationale

Add Windows PE support for Unpackaged Desktop Apps will bring several benefits, for example:

- The Windows system utilities developers can build their apps with the modern UI technology. I think it meets the goal for creating the Project Reunion. (Many Windows system utilities developers **only** use Win32 API to build their apps because they need to support Windows PE.)
- Microsoft can modernize their implementations for Windows 10 installation.
- Port Windows Terminal to Windows PE for improving the system maintenance experience.
- It can help developers include Microsoft to unify the Windows experience.

## Scope

| Capability | Priority |
| :---------- | :------- |
| Add Windows PE support for Unpackaged Desktop Apps | Must |

**Comment by manupstairs** [comment]
I think this is the common demand of equipment manufacturers.

**Comment by ecovio1** [comment]
I hope that MS will not pass this request  to the Feedback Hub and let it rot there forever; ( as first time in the last 9 years, windows Desktop development in general just has slowly started to become exciting again because of Project Reunion.)

**Comment by wangwenx190** [comment]
+1

**Comment by Jaiganeshkumaran** [comment]
The problem with Windows PE is that the base installation needs to fit on a DVD so adding more stuff will not help even if it's also installed on internal hard disk by OEMs for Windows Recovery Environment just causes duplicated files on the same PC. Windows PE doesn't even support anything after .NET Framework 4.5 and even then WPF isn't supported. Since the WinUI framework could be distributed with each app package separately instead of a global install, so it could work

**Comment by wjk** [comment]
Windows Forms support would be more than enough here IMO. No need to create anything heavyweight when a lightweight, (presumably) compatible approach already exists. Being able to run a WinForms app written targeting .NET 5 on WinPE would tick all the feature boxes I could ask for.

**Comment by MouriNaruto** [comment]
> Being able to run a WinForms app written targeting .NET 5 on WinPE would tick all the feature boxes I could ask for.

But we can't use the xml-based XAML layout in a standard WinForms app.
