### ISSUE TITLE
Remove the need for a packaging project for packaged desktop apps

### ISSUE THREAD

**Issue by Jaiganeshkumaran** [microsoft/ProjectReunion#710]
Today you need add a packaging project to package desktop apps but that isn't convenient all them time especially for new modern "desktop apps". Instead there could be an option to build an MSIX package without a packaging project similar to how it works for UWP apps by using the Package.appxmanifest inside the project if it's there.

**Comment by andrewleader** [comment]
Hey @Jaiganeshkumaran, this is already in the works! See #491 

Thanks!
