### ISSUE TITLE
Popup theme resource binding not working

### ISSUE THREAD

**Issue by KanniyappanP** [microsoft/ProjectReunion#722]
**Describe the bug**

I'm using the Popup control in my custom gallery control, and when I load/switch the theme to Dark in the application, the Popup background and foreground are not updated, but the colors are updated to the popup child via theme resource binding.

When I did this with template binding, this issue did not occur, and it only occurred in desktop applications, while UWP applications worked fine. 

**Steps to reproduce the bug**

1. Download the attached simple reproducible WinUI Desktop application [Popup_DarkTheme.zip](https://github.com/microsoft/microsoft-ui-xaml/files/6302561/Popup_DarkTheme.zip)
2. Click the Popup open button
3. Note Popup background and foreground not updated in Dark theme.

**Expected behavior**
Popup background and foreground should be updated properly in Dark theme.

**Screenshots**

**Gallery View**

![image](https://user-images.githubusercontent.com/56436173/114527794-00443780-9c66-11eb-9c0d-8acdd35a7dbb.png)

**Gallery Popup View** 

![image](https://user-images.githubusercontent.com/56436173/114527909-1eaa3300-9c66-11eb-8c4d-58b2e943300d.png)

**Version Info**
Project-Reunion NuGet package version 0.5.0
![image](https://user-images.githubusercontent.com/56436173/114530326-75b10780-9c68-11eb-9e3a-483af3b9e02e.png)

NuGet package version: 
[Microsoft.ProjectReunion 0.5.0]

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |

**Comment by andrewleader** [comment]
Hey @KanniyappanP, thanks for filing this, we'll track this issue in the microsoft-ui-xaml repo using the issue you created there: microsoft/microsoft-ui-xaml#4802
