### ISSUE TITLE
[Reunion 0.5] PickMultipleFilesAsync Crashes Application / Exception Thrown

### ISSUE THREAD

**Issue by eleanorleffler** [microsoft/ProjectReunion#731]
**Describe the bug**

In UWP, the FileOpenPicker works for both PickSingleFileAsync and PickMultipleFilesAsync.

In WinUI 3 Reunion 0.5 PickSingleFileAsync works, but PickMultipleFilesAsync causes a crash.

This [issue has been seen before](https://github.com/microsoft/microsoft-ui-xaml/issues/2716) in a previous release.

**Steps to reproduce the bug**

1. Clone the [WinUI3Reunion05_Problems](https://github.com/eleanorleffler/WinUI3Reunion05_Problems).
2. Go to the WinUI3IssuesReunion05 folder.
3. Open the WinUI3IssuesReunion05.sln solution in Visual Studio 2019 Preview.
4. Build and run with Debug x64.
5. Click on the sixth item on the Navigation View ("FileOpenPicker")
6. Click on the second button, "FileOpenPicker: Multiple Files", and select zero, one, or more files to see the crash.

**Expected behavior**

We expect to be able to select multiple files and the FileOpenPicker not to crash.

**Screenshots**

![ExpectedBehavior](https://user-images.githubusercontent.com/9272634/114945589-3ec92600-9e0f-11eb-8967-afed7a141271.PNG)

Screenshot#1 - Expected Behavior (UWP)

![CurrentBehavior](https://user-images.githubusercontent.com/9272634/114945567-3113a080-9e0f-11eb-9d44-b394f5458101.PNG)

Screenshot#2 - Current Behavior (WinUI3 Desktop)

**Version Info**

Targeting:
Target: Universal Windows
Target version: Windows 10, version 2004 (10.0; Build19041)
Min version: Windows 10, version 1809 (10.0; Build 17763)

NuGet package version: 
[Microsoft.ProjectReunion 0.5.0]
[Microsoft.ProjectReunion.WinUI 0.5.0]

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              | 						 |
| May 2020 Update (19041)            | 						 |
| November 2019 Update (18363)       | 						 |
| May 2019 Update (18362)            | 						 |
| October 2018 Update (17763)        | 			Yes			 |
| April 2018 Update (17134)          | 						 |
| Fall Creators Update (16299)       | 						 |
| Creators Update (15063)            | 						 |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | 		Yes			|
| Xbox               | 					|
| Surface Hub        | 					|
| IoT                | 					|

**Additional context**

**Comment by marb2000** [comment]
@Scottj1s, @manodasanW, and @angelazhangmsft, I think this is an issue with C#/WinRT projections. Can you take a look at the @eleanorleffler code, please?  
This is a code snipped:
```CS

private async void OnSelectFolder(object sender, RoutedEventArgs e)
{ 
           var filePicker = new FileOpenPicker();
            IntPtr windowHandle = (App.Current as App).WindowHandle;

            var initializeWithWindow = filePicker.As<IInitializeWithWindow>();
            initializeWithWindow.Initialize(windowHandle);
            filePicker.FileTypeFilter.Add("*");
            
            IReadOnlyList<StorageFile> files = await filePicker.PickMultipleFilesAsync();
           if (files.Count > 0)
            {
                StringBuilder output = new StringBuilder("Picked files:\n");
                foreach (StorageFile file in files)
                {
                    output.Append(file.Name + "\n");
                }
                System.Diagnostics.Debug.WriteLine(output.ToString());
            }
            else
            {
                System.Diagnostics.Debug.WriteLine("Operation cancelled.");
            }
}
```
And this is error:

```
System.Reflection.TargetInvocationException
  HResult=0x80131604
  Message=Exception has been thrown by the target of an invocation.
  Source=System.Private.CoreLib
  StackTrace:
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
  at WinRT.SingleInterfaceOptimizedObject..ctor(Type type, IObjectReference objRef)
   at Windows.Storage.Pickers.FilePickerSelectedFilesArray.<.ctor>b__8_0()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at Windows.Storage.Pickers.FilePickerSelectedFilesArray.get__default()
   at Windows.Storage.Pickers.FilePickerSelectedFilesArray.get_Count()
   at ReunionEbookReader.SettingsPage.<OnSelectFolder>d__11.MoveNext() in D:\Repos\ReunionEbookReader\ReunionEbookReader\ReunionEbookReader\SettingsPage.xaml.cs:line 100

  This exception was originally thrown at this call stack:
    [External Code]

Inner Exception 1:
COMException: The application called an interface that was marshalled for a different thread. (0x8001010E (RPC_E_WRONG_THREAD))
```
I think this code is executed in the UIThread, so no sure why they hit the marshaled exception.

**Comment by andrewleader** [comment]
Thanks @eleanorleffler for re-pinging us on this, we'll continue to track with #467 (your original bug). Apologies we haven't been able to get to it yet. Closing this one.
