### ISSUE TITLE
ArgumentOutOfRangeException was thrown when creating DateTimeOffset for MinDate

### ISSUE THREAD

**Issue by ssaran046** [microsoft/ProjectReunion#732]
**Describe the bug**

ArgumentOutOfRangeException was thrown when creating DateTimeOffset for GregorianCalendar MinSupportedDateTime.

var mindate = new DateTimeOffset(new GregorianCalendar().MinSupportedDateTime);

**Steps to reproduce the bug**

1. Create a simple sample in WinUI UWP
2. Write this code on a simple sample constructor "var mindate = new DateTimeOffset(new GregorianCalendar().MinSupportedDateTime);"
3. Now, Run the sample it throws an exception.

**Expected behavior**

It should not throw an exception.

**Screenshots**

![image](https://user-images.githubusercontent.com/24865096/114981169-31617980-9eab-11eb-9be5-18187c0ac15b.png)

**Version Info**

NuGet package version: 

[Microsoft.ProjectReunion 0.1.0-prerelease2]

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |

**Additional context**

**Comment by nickrandolph** [comment]
@ssaran046 are you able to upgrade to v0.5 of ProjectReunion and confirm whether this fixes the issue?

**Comment by ssaran046** [comment]
@nickrandolph  v0.5 of ProjectReunion don't have support to WinUI in UWP, so I can't upgrade.

**Comment by ssaran046** [comment]
@nickrandolph This issue exists on ProjectReunion v0.5 WinUI in Desktop too.

**Comment by nickrandolph** [comment]
You might want to check against 0.5.5 that was just released too.

**Comment by ssaran046** [comment]
@nickrandolph I can't check against ProjectReunion v0.5.5, so please ensure from your side.

**Comment by nickrandolph** [comment]
@ssaran046 I'm not sure what side you think I'm on 🤣 but can't you just updated to 0.5.5 and see whether it repros in WinUI for desktop (like you did before)?

**Comment by ssaran046** [comment]
@nickrandolph I can't build the v0.5.5 project.

**Comment by nickrandolph** [comment]
Have you got .net6 preview installed? If so, please add a global.json to your solution folder and set sdk version to .net 5

**Comment by nickrandolph** [comment]
Also, this isn't a bug, it's an error in your code. MinSupportedDateTime has a kind of unspecified. This seems to get interpreted as local time, which is then converted to utc code. Now I'm assuming that you, like me, are ahead in the world, so utc ends up being less than the minsupporteddatetime, which is why you see the error.

Try 
var mindate = new DateTimeOffset(new GregorianCalendar().MinSupportedDateTime.ToUniversalTime());

**Comment by ssaran046** [comment]
@nickrandolph below codes are working

var mindate = new DateTimeOffset(new GregorianCalendar().MinSupportedDateTime.ToUniversalTime());

var mindate = new DateTimeOffset(new GregorianCalendar().MinSupportedDateTime.ToLocalTime());

But it should not throw an exception if I didn't use local/UTC conversion.

**Comment by nickrandolph** [comment]
Why would you expect it not to throw an exception, you're specifying a date that's prior to the minsupporteddatetime?

When you call ToLocalTime() you get a datetime that when converted back to utc is still a valid datetime.
![image](https://user-images.githubusercontent.com/1614057/115194667-1acc5400-a131-11eb-8f3d-eba5f587698a.png)

**Comment by nickrandolph** [comment]
Here's a list of things that work/doesn't work (look at the variable name)
var minDateToUniversal_Works = new DateTimeOffset(new GregorianCalendar().MinSupportedDateTime.ToUniversalTime());
var minDateToLocalTime_Works = new DateTimeOffset(new GregorianCalendar().MinSupportedDateTime.ToLocalTime());
var minDateSpecifyKindUtc_Works = new DateTimeOffset(DateTime.SpecifyKind(new GregorianCalendar().MinSupportedDateTime, DateTimeKind.Utc));

var minDateSpecifyKindLocalTime_DoesntWork = new DateTimeOffset(DateTime.SpecifyKind(new GregorianCalendar().MinSupportedDateTime, DateTimeKind.Local));
var minDate_DoesntWork = new DateTimeOffset(new GregorianCalendar().MinSupportedDateTime);

**Comment by ssaran046** [comment]
@nickrandolph Below code, Below code, I have used MinSupportedDateTime only not the prior value of MinSupportedDateTime. Then why should it throw an exception?

var minDate_DoesntWork = new DateTimeOffset(new GregorianCalendar().MinSupportedDateTime);

**Comment by nickrandolph** [comment]
Because MinSupportedDateTime defaults to a kind of Unspecified. It appears that DateTimeOffset treats Unspecified as if it were a LocalTime and thus converts it to UTC (which given our timezone) puts it before the MinSupportedDateTime. 
Regardless, I don't think this is a Reunion bug, and pretty certain you'll see the same behavior in a .NET 5 console app - you could raise an issue with the dotnet repo if you think it's a legitimate bug
