### ISSUE TITLE
Project Reunion 0.5.5 Extension doesn't work on Visual Studio 2019 16.10 preview 2.0

### ISSUE THREAD

**Issue by runceel** [microsoft/ProjectReunion#740]
**Describe the bug**

I'm using Project Reunion 0.5.5 extension on Visual Studio 2019 Version 16.10.0 Preview 2.0. When I was trying to create a Blank App, Packaged (WinUI 3 in Desktop) project. Then the following error was occurred:

```
---------------------------
Microsoft Visual Studio
---------------------------
A problem was encountered creating the sub project 'App7 (Package)'.  The result "" of evaluating the value "$(ILLinkTasksAssembly)" of the "AssemblyFile" attribute in element <UsingTask> is not valid.  C:\Program Files\dotnet\sdk\6.0.100-preview.3.21202.5\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.ILLink.targets
---------------------------
OK   
---------------------------
```

**Steps to reproduce the bug**

1. Setup dev env: https://docs.microsoft.com/en-us/windows/apps/project-reunion/get-started-with-project-reunion
    - Visual Studio 2019 Version 16.10.0 Preview 2.0
    - Project Reunion 0.5.5
2. Create a project using Blank App, Packaged (WinUI 3 in Desktop) item template.
    1. Input a project name
    2. Select OK button
    3. Select target platforms, and then select OK button.

**Expected behavior**

A .NET 5 project and a packaged project are created.

**Screenshots**

![image](https://user-images.githubusercontent.com/79868/115188237-98876400-a11f-11eb-9e98-93aeaa569442.png)

**Version Info**

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2020 Update (19041)            | Yes   |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |

**Comment by nickrandolph** [comment]
I can reproduce this issue.

**Workaround**
Create global.json file in the folder where you plan on creating the solution and specify a .net5 sdk version number eg
{
  "sdk": {
    "version": "5.0.201"
  }
}
Create Project Reunion application in the folder where you created the global.json file.

**Comment by runceel** [comment]
Thank you @nickrandolph.
Your workaround was worked for me.

**Comment by andrewleader** [comment]
@Scottj1s can you take a look at this?

**Comment by Herdubreid** [comment]
I'm getting the following compilation error after creating a new WinUI 3 in Desktop app:
```
Severity	Code	Description	Project	File	Line	Suppression State
Error		This version of Project Reunion requires WinRT.Runtime.dll version 1.2 or greater. 
    Please update to .NET 5.0.6 SDK or later.  
    Or add a temporary Microsoft.Windows.SDK.NET.Ref FrameworkReference of version 10.0.*.16 or later.
    For example,
        <ItemGroup>
            <FrameworkReference Update="Microsoft.Windows.SDK.NET.Ref" RuntimeFrameworkVersion="10.0.18362.16" />
            <FrameworkReference Update="Microsoft.Windows.SDK.NET.Ref" TargetingPackVersion="10.0.18362.16" />
        </ItemGroup>
```

I've got version 5.0.300-preview.21180.15 of the .NET SDK, which I believe is the latest, and Target Framework net5.0-windows10.0.19041.0.

If I install .NET 6 preview, then I run into the problems described above.

**Comment by Herdubreid** [comment]
I got Reunion to compile by installing latest CsWinRT
https://www.nuget.org/packages/Microsoft.Windows.CsWinRT/

**Comment by runceel** [comment]
@Herdubreid 
I had met the same error you were facing.
As shown in the error message, adding the `ItemGroup` tag to the project file will resolve the error.

That is written the following document.
https://docs.microsoft.com/en-us/windows/apps/project-reunion/#net-sdk-references

**Comment by tedekeroth** [comment]
After adding the ItemGroup and also adding the global.json, as noted above, the compile errors do disappear. However, running the app breaks in Runtime with 

> System.Reflection.TargetInvocationException: 'Exception has been thrown by the target of an invocation.'
> COMException: Class not registered (0x80040154 (REGDB_E_CLASSNOTREG))
>

**Comment by Scottj1s** [comment]
For original issue (wapproj broken in VS 16.10), see also:
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1307712

**Comment by riverar** [comment]
@Scottj1s Don't think we should close this issue as it's still a bug without a fix in Project Reunion right?

**Comment by mrlacey** [comment]
> @Scottj1s Don't think we should close this issue as it's still a bug without a fix in Project Reunion right? cc: @andrewleader

See also [this discussion on the WinUI repo about providing clear next steps when something is closed](https://github.com/microsoft/microsoft-ui-xaml/issues/4736).

Knowing there's a related issue in a separate issue tracker (that I can't see) doesn't do anything to help me know when or if this will be fixed.

**Comment by andrewleader** [comment]
Thanks Rafael and Matt, great points. I'm following up with Scott to find out some more details and then will update this accordingly.

**Comment by Scottj1s** [comment]
Hi folks - apologies for linking to a private issue, which includes the following:

The fix for this bug was just committed to the .NET Sdk repo and should be available in 16.10 Preview 3 after .NET’s next insertion.
[Fix WAP proj problem by removing reliance on Microsoft.NET.Sdk.targets by edwardskrod · Pull Request #17042 · dotnet/sdk (github.com) ](https://github.com/dotnet/sdk/pull/17042)

I think that addresses questions above (specific fix availability, link to issue/PR, and this issue includes clear workaround steps).  If not, please ask.

**Comment by postnik0706** [comment]
Hi guys (I guess @nickrandolph and @runceel), how did you make the workaround work (I am assuming that to be the global.json addition to the solution folder)?
VS would not let you create a solution if the destination folder already exists. What am I missing here? I wanted to create a new clean solution from the template in VS.
Thanks!

**Comment by nickrandolph** [comment]
Example: say you want to create MyApplication, which you're going to put in the folder C:\temp, you would create the global.json file in C:\temp. Don't try to create it in C:\temp\MyApplication

**Comment by postnik0706** [comment]
Thanks; I cannot make this thing work. Looked up the installed sdks using 'dotnet sdk check', generated new global.json using 'dotnet new globaljson', tried creating a new app in a subfolder; I am pretty sure global.json is a CLI feature, VS does not care that the file is in that parent folder. Also tried creating an empty *.sln at the parent folder and adding a WinUI Blank app at a subfolder with the same disappointing result. And with Win UI template is not in the list of 'dotnet new' templates which is also disappointing.

**Comment by nickrandolph** [comment]
What's the contents of your generated global.json? What sdks do you have installed (run "dotnet --list-sdks")?

I assume that you only have the Project Reunion VS extension installed - if you previously had the WinUI extension, make sure you remove that.

**Comment by postnik0706** [comment]
That is correct, Project Reunion only is installed. WinUI is not installed.
Below is my cmd line output. Thanks for trying to help me out!

```
PS C:\Users\<username>\source\repos\reunion> dotnet --list-sdks
3.1.400-preview-015151 [C:\Program Files\dotnet\sdk]
5.0.300-preview.21180.15 [C:\Program Files\dotnet\sdk]
6.0.100-preview.3.21202.5 [C:\Program Files\dotnet\sdk]
PS C:\Users\<username>\source\repos\reunion> cat .\global.json
{
  "sdk": {
    "version": "6.0.100-preview.3.21202.5"
  }
}
PS C:\Users\<username>\source\repos\reunion>
```

**Comment by tedekeroth** [comment]
Im not sure exactly what you have tried, but start out with `maui-check` tool, here: https://github.com/Redth/dotnet-maui-check

After that, read this post: https://github.com/microsoft/microsoft-ui-xaml/issues/4894 and scroll down to asklar: https://github.com/microsoft/microsoft-ui-xaml/issues/4894#issuecomment-827028514

You can see there that the global.json should read:
```
{
    "sdk": {
        "version": "5.0.202"
    }
}
```
and that file should be created manually, before the solution is created. In my case, the global.json file is placed in the folder one-up from the sln file, like so:

```
/WinUITest/global.json
/WinUITest/App1/App1.sln
/WinUITest/App1/App1/App1.csproj
```
Then, using Visual Studio, I created a new solution, and navigated to `/WinUITest/` to place it there.

Please also note that the csproj file needs to be updated as stated above:

```
        <ItemGroup>
            <FrameworkReference Update="Microsoft.Windows.SDK.NET.Ref" RuntimeFrameworkVersion="10.0.18362.16" />
            <FrameworkReference Update="Microsoft.Windows.SDK.NET.Ref" TargetingPackVersion="10.0.18362.16" />
        </ItemGroup>
```

**Comment by postnik0706** [comment]
@tedekeroth Thanks, installing/switching to 5.0.202 sdk resolved the issue and adding FrameworkReference to csproj resolved another build time error.

**Comment by tedekeroth** [comment]
So, it works? =)

**Comment by postnik0706** [comment]
It works!

**Comment by nickrandolph** [comment]
So after all that, my initial fix was the answer.... 🤷‍♂️😒

**Comment by postnik0706** [comment]
@nickrandolph to be precise, your initial fix and the fact that the extension does not work properly with .net sdk 6.0.100-preview.3.21202.5.

**Comment by tedekeroth** [comment]
> So after all that, my initial fix was the answer.... 🤷‍♂️😒

Yes, it was =) What was a bit unclear to me was that it is needed to create global.json first and place it in a empty folder, and only then create the sln, with that folder as the parent folder.  =)

**Comment by git102347501** [comment]
The same question made me lose interest in winui3
