### ISSUE TITLE
ProjectReunion 0.5.5 build error: Unable to install nuget Microsoft.Windows.SDK.NET.Ref

### ISSUE THREAD

**Issue by LeftTwixWand** [microsoft/ProjectReunion#741]
**Describe the bug**

With the new ProjectReunion 0.5.5 template for Visual Studio from the [Marketplace](https://marketplace.visualstudio.com/items?itemName=ProjectReunion.MicrosoftProjectReunion) a new project structure looks like this:
![image](https://user-images.githubusercontent.com/50652041/115193087-5d237000-a0f4-11eb-95dd-6d234fee24f7.png)

The error is: `The version of Project Reunion requires WinRT.Runtime,dll version 1.2 or greater`
In the Microsoft.ProjectReunion.targets I see the next error text:
```XAML
 <Error Condition="'@(_WinrtRuntimeIncompatible)'!='' and '@(_WinrtRuntimeCompatible)'==''"
        Text="This version of Project Reunion requires WinRT.Runtime.dll version 1.2 or greater. 
              Please update to .NET 5.0.6 SDK or later.  
              Or add a temporary Microsoft.Windows.SDK.NET.Ref FrameworkReference of version 10.0.*.16 or later.
              For example,
        &lt;ItemGroup&gt;
            &lt;FrameworkReference Update=&quot;Microsoft.Windows.SDK.NET.Ref&quot; RuntimeFrameworkVersion=&quot;10.0.18362.16&quot; /&gt;
            &lt;FrameworkReference Update=&quot;Microsoft.Windows.SDK.NET.Ref&quot; TargetingPackVersion=&quot;10.0.18362.16&quot; /&gt;
        &lt;/ItemGroup&gt;" />
```
.NET 5.0.6 SDK is not officially released yet on [dotnet.microsoft.com](https://dotnet.microsoft.com/download/dotnet/5.0)
So I'm just trying to download Microsoft.Windows.SDK.NET.Ref from nuget, but getting this error:
`Package 'Microsoft.Windows.SDK.NET.Ref 10.0.19041.16' has a package type 'DotnetPlatform' that is not supported by project 'AppReunion'.`

**Steps to reproduce the bug**
Just create a new Project Reunion project with [ProjectReunion template 0.5.5 from the marketplace](https://marketplace.visualstudio.com/items?itemName=ProjectReunion.MicrosoftProjectReunion)

**Screenshots**
![image](https://user-images.githubusercontent.com/50652041/115194470-30705800-a0f6-11eb-85b4-b7c422975c59.png)

**Version Info**
OS version: 20H2
OS build version: 19042.746
Project target version: Windows 10, version 2004 (10.0 Build 19041)
Project min version: Windows 10, version 2004 (10.0 Build 19041)

**NuGet package version:**
Microsoft.Windows.SDK.NET.Ref - version 10.0.19041.16
Microsoft.ProjectReunion - version 0.5.5
Microsoft.ProjectReunion.Foundation - version 0.5.5
Microsoft.ProjectReunion.WinUI - version 0.5.5

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :--------------------: |
| Insider Build (xxxxx)              |    |
| May 2020 Update (19041)            | Yes   |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |

**Comment by nickrandolph** [comment]
Please see documentation at https://docs.microsoft.com/en-us/windows/apps/project-reunion/update-existing-projects-to-the-latest-release
Even though it's a new project, you still need to apply the upgrade steps

**Comment by LeftTwixWand** [comment]
@nickrandolph, yes, now it's working. Thanks!
