### ISSUE TITLE
Requesting FAQ regarding relationship between C++/Win32 and C++/WinRT

### ISSUE THREAD

**Issue by dr-eck** [microsoft/ProjectReunion#748]
I’m a little confused.  I’ve been hiding under the MFC rock for a couple decades and would really like to enter the modern era.  It looked as if C++/WinRT with WINUI 3 was the way to go, but then C++/Win32 showed up.

In the GitHub cppwin32 project README.md you state, “This projection is similar to C++/WinRT”, but that’s the only intimation of any relationship between the two.

Clearly, C++/WinRT is more mature than /Win32, but it appears that the former could easily get obsoleted by the latter.  C++/Win32 is the one that is mentioned on the Project Reunion website, so it appears to be favored.

I'm really hesitant to start writing code that depends on either /Win32 or /WinRT when I believe that either is a gamble.

It would be very helpful if the FAQ included an answer clarifying the relationship between C++/Win32 and C++/WinRT.  Is it safe to write code for either?

**Comment by stevewhims** [comment]
Yes, adding @mcleanbyron for info. McLean, let me know, I'll be happy to make those changes if you prefer. See the two links in the comment above to the Reunion content.

**Comment by mcleanbyron** [comment]
Thanks for the feedback. In the case of the articles mentioned here, "C++/Win32" isn't referring to a specific technology like C++/WinRT, but instead is a general term that refers to any desktop Windows application written in C++ (this includes applications that use C++/WinRT, but can also include other C++ Windows desktop apps). These same articles similarly use the term "C#/.NET 5" when referring generally to C# apps that target .NET 5. I see how this is confusing, and I'll follow up on making some changes to the "C++/Win32" term avoid this confusion.

**Comment by andrewleader** [comment]
Thanks @mcleanbyron for responding to this! Do you want to keep this issue open to track investigating making changes to this, or are you tracking that elsewhere? Thanks!

**Comment by mcleanbyron** [comment]
It makes sense to keep this issue open to track the doc updates called out here. I should have them done next week, and will follow back up with this when they're done.

**Comment by mcleanbyron** [comment]
The references to "C++/Win32" have been scrubbed out of the articles mentioned in this issue (https://docs.microsoft.com/en-us/windows/apps/project-reunion/ and https://docs.microsoft.com/en-us/windows/apps/project-reunion/deploy-apps-that-use-project-reunion), and from many other articles. Instead, these articles now use general terms like "C++ desktop (Win32)" or simply "C++ desktop".

@andrewleader - I think you can close this issue now (I don't have permissions).

**Comment by dr-eck** [comment]
Thanks to all of you for clearing this up!
