### ISSUE TITLE
Add new item dialog is not showing Resource file (.resw) on WinUI in UWP projects

### ISSUE THREAD

**Issue by sibille** [microsoft/ProjectReunion#757]
**Describe the bug**
The "Add New Item" dialog is not showing Resource file (.resw) on WinUI in UWP projects.

**Steps to reproduce the bug**
1. Create a new Blank App (WinUI in UWP) using the Reunion 0.5 Preview vsix
2. Click Add -> New Item on the projects context menu

**Expected behavior**
The "Add New Item" dialog should show "Resource file (.resw)" under the WinUI category as shown for Desktop Apps.

**Screenshots**
Add New Item to UWP App
![image](https://user-images.githubusercontent.com/24698018/115857043-82361c80-a42d-11eb-84ef-9abd6834aa01.png)

Add new item to Desktop App
![image](https://user-images.githubusercontent.com/24698018/115855908-156e5280-a42c-11eb-9ebd-89b047bc105e.png)

**Version Info**
Project Reunion VSIX 0.5.5

**Comment by huichen123** [comment]
There is resource file template under XAML. There is no difference.

**Comment by andrewleader** [comment]
As Hui mentioned, UWP apps should use the Resource file template under the XAML node, they're identical (there's nothing different about a WinUI 3 Resources file vs a XAML Resources file). Thanks!
