### ISSUE TITLE
 XAML visual designer does not show in WinUI 3 Desktop project.

### ISSUE THREAD

**Issue by ZhouJJJKKK** [microsoft/ProjectReunion#766]
**Describe the bug**
Xaml designer does not appear in my visual studio or blend. when I click the MainWindow.xaml, only the XAML text shows. However,  the same XAML file can be edited with the visual designer  in a UWP project. 

**Steps to reproduce the bug**

1. create a new WinUI 3 project,
2. Click on MainWindow.xaml

**Expected behavior**
An visual XAML designer appears just like UWP.

**Screenshots**
Xaml designer does not appear in my visual studio or blend within a WinUI3 Desktop project.
![image](https://user-images.githubusercontent.com/49114836/116181495-45c83080-a74d-11eb-95a7-d7137babd171.png)

it works on a UWP project with the same contents.
![image](https://user-images.githubusercontent.com/49114836/116182308-9db36700-a74e-11eb-97ae-588da777c9d3.png)

**Version Info**
both project 0.5.5 and 0.5.6

NuGet package version: 
A VCPKG Nuget package.

Windows 10.019042               

**Additional context**
My colleagues also meet the same bug.

**Comment by sidy3d** [comment]
Not really a bug, seems that the designer will not be implemented until WinUI 3.0 ships. See #3656.

**Comment by mrlacey** [comment]
Adding a direct link to the related WinUI issue https://github.com/microsoft/microsoft-ui-xaml/issues/3656#issuecomment-730558094

 I don't think this is something we can expect any time soon....

**Comment by ZhouJJJKKK** [comment]
> Adding a direct link to the related WinUI issue [microsoft/microsoft-ui-xaml#3656 (comment)](https://github.com/microsoft/microsoft-ui-xaml/issues/3656#issuecomment-730558094)
> 
> I don't think this is something we can expect any time soon....

Thank you. It was available in a Preview Vision of WinUI 3. I did not expect it removed.

**Comment by MoreporkGithub** [comment]
I get exactly the same behavior. Neither Blend nor VS 2019  will show a design surface for WinUI 3. I spent a lot of time trying to understand what I was missing , then found this thread.  If it will not be implemented "until WinUI 3 ships" I understood WinUI 3 HAD shipped and was now part of Reunion 05.

Will we get an update for VS 2019? How will I know when I can develop with WinUI 3?

Thanks.

**Comment by mrlacey** [comment]
@MoreporkGithub It's not that it won't be implemented until WinUI 3 ships,  it's that **it won't be considered until after** WinUI 3 (WinAppSDK v1.0) ships.

It seems more effort is being put into [Hot Reload](https://docs.microsoft.com/en-us/visualstudio/xaml-tools/xaml-hot-reload?view=vs-2019) and [Visual Studio Live Preview](https://youtu.be/FwYf1FDsjXQ?t=2034) (which will both, eventually, be available for WinUI 3) instead.
Hopefully, these tools will enable a suitably comparable experience and also bring other benefits in the future too. (Especially as Hot Restart improves.)
If your past XAML development experience has been heavily reliant on the visual designer then I can appreciate a big impact to your productivity. :(

**Comment by MoreporkGithub** [comment]
Thanks mrlacey, for your comment.

I've had to give up on it for now.

I did my first UWP project a few days ago using XAML for the first time, but I was really keen to try the new WinUI 3.

I have a lot of experience with Windows Forms and C# and have written tools to generate Windows Forms, but XAML is new to me and I have been working to understand it.

Obviously, we get used to the convenience of a Design surface and  I struggled to use XAML without one. I located the WinUI 3 library and tried cutting and pasting XAML code to see if I could get some controls onto a form but I was never able to make it work. 

Thanks for your comment (I have no idea what "hot reload" is but I'm sure I'll find out in time.)

**Comment by artsemionov** [comment]
There is no solution, issue should be reopened.

**Comment by rvxfahim** [comment]
Same issue here, how come such a major thing gets vanished.

**Comment by acrigney** [comment]
And VS2022 does not allow a designer or Blend for VS2022!!! Nespa?

**Comment by Zaryob** [comment]
Same issue

**Comment by michalss** [comment]
same here :( brig designer back pls...

**Comment by rollinbe** [comment]
Same issue

**Comment by martin999a** [comment]
No design view, no datagrid. Who TF is going to use WinUI 3??

**Comment by soroshsabz** [comment]
ITNOA

> @MoreporkGithub It's not that it won't be implemented until WinUI 3 ships, it's that **it won't be considered until after** WinUI 3 (WinAppSDK v1.0) ships.
> 
> It seems more effort is being put into [Hot Reload](https://docs.microsoft.com/en-us/visualstudio/xaml-tools/xaml-hot-reload?view=vs-2019) and [Visual Studio Live Preview](https://youtu.be/FwYf1FDsjXQ?t=2034) (which will both, eventually, be available for WinUI 3) instead. Hopefully, these tools will enable a suitably comparable experience and also bring other benefits in the future too. (Especially as Hot Restart improves.) If your past XAML development experience has been heavily reliant on the visual designer then I can appreciate a big impact to your productivity. :(

It is ship, so what is your plan?

**Comment by soroshsabz** [comment]
related to https://github.com/microsoft/microsoft-ui-xaml/issues/5917

**Comment by soroshsabz** [comment]
@mrlacey

**Comment by mrlacey** [comment]
@soroshsabz I don't work for Microsoft and I'm not on the core team for WAS or WinUI. As per the discussions linked above, the lack of direct feedback from the team about this over the last few years, and the resource prioritization from Microsoft, I can't imagine Microsoft building this.

**Comment by Slion** [comment]
> @soroshsabz I don't work for Microsoft and I'm not on the core team for WAS or WinUI. As per the discussions linked above, the lack of direct feedback from the team about this over the last few years, and the resource prioritization from Microsoft, I can't imagine Microsoft building this.

This is the scary part. I'm a big fan of WinUI, WindowsAppSDK and the whole Reunion thing. But it does not feel like Microsoft is going all in on in this.

**Comment by rvxfahim** [comment]
I think a MSFT representative should just announce whether there will ever be a designer for winui or not, and then we can all give this issue thread a break once and for all.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by mdtauk** [comment]
> I think a MSFT representative should just announce whether there will ever be a designer for winui or not, and then we can all give this issue thread a break once and for all.

They have essentially, during the WinUI community calls.  They word it as "not planned", or "not a priority"...
