### ISSUE TITLE
Reunion 0.5.5: Attribute metadata missing

### ISSUE THREAD

**Issue by dayman40** [microsoft/ProjectReunion#767]
Something regressed in Reunion 0.5.0 the attribute TemplatePart is defined correctly. This is blocking and potentially a ship recall bug.

// Reunion 0.5.5
namespace Microsoft.UI.Xaml

## [WindowsRuntimeType("Microsoft.UI")]  ß Notice all metadata data missing

{

    //

    // Summary:

    //     Represents an attribute that is applied to the class definition to identify the

    //     types of the named parts that are used for templating.

    [WindowsRuntimeType("Microsoft.UI")]  ß Notice all metadata data missing

    public sealed class TemplatePartAttribute : Attribute

    {

        public string Name;

        public Type Type;

 

        //

        // Summary:

        //     Initializes a new instance of the TemplatePartAttribute class.

        public TemplatePartAttribute();

    }

}

 

// Reunion 0.5.0

namespace Microsoft.UI.Xaml

{

    //

    // Summary:

    //     Represents an attribute that is applied to the class definition to identify the

    //     types of the named parts that are used for templating.

    [AllowMultiple]

    [AttributeUsage(AttributeTargets.Class, AllowMultiple = true)]

    [ContractVersion(typeof(WinUIContract), 65536)]

    [WebHostHidden]

    [WindowsRuntimeType("Microsoft.UI")]

    public sealed class TemplatePartAttribute : Attribute

    {

        public string Name;

        public Type Type;

 
        //

        // Summary:

        //     Initializes a new instance of the TemplatePartAttribute class.

        public TemplatePartAttribute();

    }

}

This code is failing to compile with error CS0579. 

This is blocking from moving to Reunion 0.5.5

Severity | Code | Description | Project | File | Line | Suppression State
-- | -- | -- | -- | -- | -- | --
Error | CS0579 | Duplicate 'TemplatePart' attribute | SpectrumComponents |* | 60 | N/A

 [TemplatePart(Name = PartDialogButton1, Type = typeof(SpectrumButton))]

    [TemplatePart(Name = PartDialogButton2, Type = typeof(SpectrumButton))]

    [TemplatePart(Name = PartDialogButton3, Type = typeof(SpectrumButton))]

    [TemplatePart(Name = PartDialogTitle, Type = typeof(ContentControl))]

    [TemplatePart(Name = PartDialogIcon, Type = typeof(BitmapIcon))]

    [TemplatePart(Name = PartDialogContent, Type = typeof(ContentPresenter))]

    [TemplatePart(Name = PartDialogButtonPanel, Type = typeof(Grid))]

    public sealed partial class SpectrumDialog : ContentDialog {}

**Comment by riverar** [comment]
This is unreadable @dayman40.

**Comment by dotMorten** [comment]
Did this only affect the `TemplatePartAttribute` class, or all attributes?
