### ISSUE TITLE
Crashes caused by XamlCompiler - not a part of WinUI framework

### ISSUE THREAD

**Issue by dayman40** [microsoft/ProjectReunion#768]
Right now the Xaml compiler determines if types are built into the WinUI framework by checking if they have our Microsoft.UI.Xaml.WinUIContract on them.  Now that CSWinRT has removed the ContractVersionAttribute projection in 0.5.5, the Xaml compiler thinks all types, even WinUI types, aren't part of the WinUI framework.  When a 0.5.5 app builds against a 0.5.0 library, it can crash because of the incorrect 0.5.5 codegen (which actually works fine on its own, but with needless overhead) interacting with the 0.5.0 codegen.  This also presents a perf issue since the compiler is generating extra type information for built-in WinUI types when it doesn't need to.

**Comment by dotMorten** [comment]
> it can crash because of the incorrect 0.5.5 codegen

@dayman40 I'm a little confused by this. Does this mean that if I shipped a class library built on top of 0.5.5, that it won't work with an app targeting 0.5.6 and I'm forced to rebuild and ship a v0.5.6 version? Or does this only affect libraries shipped on top off 0.5.0

**Comment by dayman40** [comment]
Tagging @RealTommyKlein to help clarify this for you, @dotMorten! :)

**Comment by RealTommyKlein** [comment]
@dotMorten - you technically shouldn't need to rebuild a library targeting 0.5.5, as the runtime crash only occurs if the app targets 0.5.5 while a library it built against targets a different version.  However, the crash present in 0.5.5 mentioned in this bug also increases the memory footprint of 0.5.5 apps/libraries, so you should still rebuild against 0.5.6.

**Comment by dotMorten** [comment]
@RealTommyKlein Thanks Tommy. Re-releasing right now on 0.5.6 is a bit disruptive - I'm curious how critical the memory footprint issue is? Is this a memory leak, or just an initial larger hit? Since we're still tagging our package pre-release, I'm leaning towards not generating a new 0.5.6-based build until our next regular release cycle.

**Comment by RealTommyKlein** [comment]
@dotMorten - no memory leak, but your binaries will be larger because the Xaml compiler generates unused code due to the metadata issue.

**Comment by dotMorten** [comment]
@RealTommyKlein Thanks for confirming. We just have a limited generic.xaml so I think we can live with that for now.

**Comment by dayman40** [comment]
Thank you @RealTommyKlein!! 

Please let us know if you have any further questions, @dotMorten.
