### ISSUE TITLE
Question: is Windows 7/8 supported?

### ISSUE THREAD

**Issue by Suriman** [microsoft/ProjectReunion#78]
Can an application that uses the Reunion API run on Windows 7/8?

**Comment by Felix-Dev** [comment]
Project Reunion is a set of components. Some of these components (like MSIX-Core or WebView V2) have support for Windows 7/8 and Windows 10. Other components, like WinUI 3, will not have support for Windows 7 and only target Windows 10. (Windows 8.1 support is also not currently the focus of WinUI 3 and might never arrive.)

While the next bit is probably not what you are mainly interested in, note that:
> Project Reunion is additive to your existing application code. If your app relies on Win32 API constructs you can keep doing so while starting to use more Project Reunion functionality. 

This, to my understanding, means that you can have platform checks in your code and still have your app use Reunion APIs only available on WIndows 10 while still working on WIndows 7/8. No two separate appalications are needed.

The Project Reunion team will probably be able to give you a more detailed answer, especially if you are interested in *specific* APIs/components.

**Comment by Jaiganeshkumaran** [comment]
Windows 7 is no longer supported so why do you need Windows 7 support?

**Comment by Suriman** [comment]
@Jaiganeshkumaran Because there are still many companies that use Windows 7.

**Comment by mdtauk** [comment]
> @Jaiganeshkumaran Because there are still many companies that use Windows 7.

Hopefully only for a short amount of time - there has to come a time when the platform is frozen, and future features and investment is moved forward

**Comment by stevewri** [comment]
Windows 7 lacks a lot of infrastructure for running UWP apps (for example, DWM always on, shell support for UWP launch, platform support for running UWPs.) The amount of "polyfill" would be daunting.

Windows 8 and 8.1 have UWP support, but also have lower market share. 

As Felix-Dev points out above, some Reunion components will be available farther downlevel, but we don't expect all Reunion components to have to support OSs that are no longer in regular support by the time said components ship.

**Comment by lindexi** [comment]
> 
> 
> @Jaiganeshkumaran Because there are still many companies that use Windows 7.
> 
> See:[ Windows 7 market share](https://netmarketshare.com/operating-system-market-share.aspx?options=%7B%22filter%22%3A%7B%22%24and%22%3A%5B%7B%22deviceType%22%3A%7B%22%24in%22%3A%5B%22Desktop%2Flaptop%22%5D%7D%7D%5D%7D%2C%22dateLabel%22%3A%22Trend%22%2C%22attributes%22%3A%22share%22%2C%22group%22%3A%22platformVersion%22%2C%22sort%22%3A%7B%22share%22%3A-1%7D%2C%22id%22%3A%22platformsDesktopVersions%22%2C%22dateInterval%22%3A%22Monthly%22%2C%22dateStart%22%3A%222019-06%22%2C%22dateEnd%22%3A%222020-05%22%2C%22segments%22%3A%22-1000%22%7D).

@Suriman I can not agree with you more.

I am in China. And nearly half of users in China are still using win7 system. This data is provided by Baidu https://tongji.baidu.com/research/site?hmsr=%E7%BB%9F%E8%AE%A1footer%E9%93%BE%E6%8E%A5&hmpl=footer&hmcu=footer&hmkw=&hmci=footer#os

This means that no company in China has the courage to give up support for the win7 system. I point out that this is not to deny your question. I want to show that there are different market conditions for different regions and countries.

**Comment by lindexi** [comment]
Why we want to use this technology which make we have to give up half of the market

No matter how advanced the technology is, it is undeniable that we will lose all win7 users in the fierce market competition

**Comment by edwardchanjw** [comment]
Some of these components (like MSIX-Core or WebView V2) have support for Windows 7/8 and Windows 10. 

It actually good if we have example from these. Nowadays all people resolve to Electron/Native alternative, This version could be alternative to Electron. But maybe no good enough for people who don't use .NET. Furthermore, QT indie did really good job there. But it is decent, when you need deep integration with Windows API.

**Comment by Jaiganeshkumaran** [comment]
On Windows 8.x will some of these new API work with WinRT apps or only desktop apps.

**Comment by softboy99** [comment]
stupid decision

**Comment by YapingXin-Aerospace** [comment]
> Windows 7 is no longer supported so why do you need Windows 7 support?

My customers still running Windows 7 !
