### ISSUE TITLE
Visual Studio error when creating Blank App, Packaged (WinUI 3 in Desktop) (C#) project

### ISSUE THREAD

**Issue by Daniellled** [microsoft/ProjectReunion#781]
**Describe the bug**

When creating a new Blank App, Packaged (WinUI 3 in Desktop) application Visual Studio fails to create the package project and displays the following error text:

A problem was encountered creating the sub project '{project name} (Package)'. The result "" of evaluating the value "$(ILLinkTaskAssembly)" of the "AssemblyFile" attribute in element <UsingTask> is not valid. {DotNet SDK path}\Microsoft.Net.ILLink.targets

**Steps to reproduce the bug**

1. Start Visual Studio
2. Create a new project
3. Select Black App, Packaged (WinUI 3 in Desktop) (C#)
4. Name the project
5. Check 'Place solution and project in the same directory'
6. Click Create
7. Select Target version - 19041 to 17763
8. Click OK

**Expected behavior**
Project should be created per - https://docs.microsoft.com/en-us/windows/apps/winui/winui3/get-started-winui3-for-desktop 

**Screenshots**
![image](https://user-images.githubusercontent.com/83433189/116629305-832bea00-a916-11eb-84da-9a2c8a1e9452.png)

**Version Info**
Visual Studio Version:
Microsoft Visual Studio Enterprise 2019 Preview
Version 16.10.0 Preview 2.1

Project Reunion Visual Studio Extension Version:
0.5.6

.Net SDK Version:
6.0.100-preview.3.21202.5

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        | Yes   |

**Additional context**
I am trying to play with MAUI by following instructions starting here - https://devblogs.microsoft.com/dotnet/announcing-net-multi-platform-app-ui-preview-3/

I am able to run the MAUI test app located here - https://github.com/dotnet/net6-mobile-samples/tree/main/HelloWinUI3

**Comment by huichen123** [comment]
same as https://github.com/microsoft/ProjectReunion/issues/740

**Comment by andrewleader** [comment]
Closing this (same as #740), you'll want to update to Reunion 0.5.6 and also be sure to add the explicit .NET SDK reference as documented in the docs here: https://docs.microsoft.com/en-us/windows/apps/project-reunion/#net-sdk-references
