### ISSUE TITLE
The target "ResolvePackageAssets" does not exist in the project

### ISSUE THREAD

**Issue by anovik** [microsoft/ProjectReunion#782]
After upgrading my WinUI3 in UWP project to Microsoft.Reunion version 0.5.6 the error appears

>The target "ResolvePackageAssets" does not exist in the project

I am upgrading my project from 0.5-prerelease (working fine) to version 0.5.6.

Windows 10 version is 19041.

I am working in VS 2019 16.9.4 but I think this error also takes place in VS 2019 Preview.

**Comment by nickrandolph** [comment]
Did you follow instructions here: https://docs.microsoft.com/en-us/windows/apps/project-reunion/update-existing-projects-to-the-latest-release

**Comment by anovik** [comment]
Thanks for your quick reply.

Yes, I followed these instructions but it didn't solve the problem.

As for instructions, it would be really nice to pay some more attention to UWP projects, not only desktop ones.

**Comment by nickrandolph** [comment]
oh wait, just realized you were trying to get this to work with a UWP project. My understanding is that UWP is not supported with 0.5.x of Project Reunion. My understanding is that support will come back in the previews of 0.8.

Please also watch the roadmap, as it's very clear that Desktop is the priority for this release. UWP continues to operate well with WinUI2.x and won't gain any other benefit from Project Reunion in the short term imho.

**Comment by anovik** [comment]
OK, for now I am happy with 0.5 prerelease. But could you give the link in what Reunion release it is planned to support UWP back?

**Comment by nickrandolph** [comment]
You can see my thoughts on this here - https://nicksnettravels.builttoroam.com/we-dont-need-winui-for-uwp/
and specifically comments from MS regarding the 0.8 preview at https://github.com/microsoft/ProjectReunion/issues/105#issuecomment-825158278

**Comment by anovik** [comment]
Thanks for your thoughts :) But I still need WinUI for UWP for my app though there are a lot of things I agree with you :)

Will be waiting for 0.8 preview and close this issue for now.

**Comment by nickrandolph** [comment]
Perhaps consider this - https://nicksnettravels.builttoroam.com/winui-3-on-windows10x/
Essentially having dual targets that let you use WinUI3 for Desktop and WinUI2.x for UWP = best of both worlds
