### ISSUE TITLE
Open source media player element

### ISSUE THREAD

**Issue by hupo376787** [microsoft/ProjectReunion#80]
# Proposal: Open source media player element

## Summary
Currently `MediaPlayerElement` has so many bugs and shortcomings, it's terriable,

**Comment by maxkatz6** [comment]
It will be open sourced with WinUI 3. But I have never heard about its bugs. Maybe you are talking about MediaPlayer? I would hope to see it open sourced too, but it isn't part of WinUI.

**Comment by hupo376787** [comment]
I'm using `MediaPlayerElement` on uwp. Currently it causes whole screen black when playing some videos, can't keep playback rate when changed video source, can't get closed caption's exact font size, transport control get massed after adding cunstom icons, etc. 
I have seen so many voices on user voice forum.

**Comment by hupo376787** [comment]
But it's a big step after `MediaPlayerElement` open sourced.
