### ISSUE TITLE
Azure pipeline fails on nuget restore

### ISSUE THREAD

**Issue by LeftTwixWand** [microsoft/ProjectReunion#802]
**Describe the bug**

I'm trying to configure a pipeline for a ProjectReunion solution, but on `nuget restore` command it crashes with the next error:
`The nuget command failed with exit code(1) and error(NU1201: Project MyProjectReunion is not compatible with uap10.0.17763 (UAP,Version=v10.0.17763). Project MyProjectReunion supports: net5.0-windows10.0.19041 (.NETCoreApp,Version=v5.0)`

**Steps to reproduce the problem:**
1. Create empty ProjectReunion solution
2. Set up a pipeline
3. Add `nuget restore` step

My sample solution: [github.com/LeftTwixWand/ProjectReunionPipelines](https://github.com/LeftTwixWand/ProjectReunionPipelines.git)

**Version Info**

NuGet package version: 
Microsoft.ProjectReunion - 0.5.6

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :--------------------: |
| Insider Build (xxxxx)              |    |
| May 2020 Update (19041)            |  Yes   |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |

**Additional context**

**Comment by andrewleader** [comment]
@huichen123 can you look into this? There's a sample solution in the bug to try the repro.

**Comment by huichen123** [comment]
as a workaround for the time being, you can move "<AssetTargetFallback>net5.0-windows$(TargetPlatformVersion);$(AssetTargetFallback)</AssetTargetFallback>" in the wapproj down after TargetPlatformVersion is defined.
