### ISSUE TITLE
Flagged enum does not return correct value

### ISSUE THREAD

**Issue by Vinothini-V** [microsoft/ProjectReunion#803]
**Describe the bug**
Flagged enum does not return correct value. When a value is assigned to the flagged enum property, it does not returns the assigned value. 

**Steps to reproduce the bug**
Assign value to flagged enum property. Then check the value, it retruns wrong value. Like if we assign Check,UnCheck and Intermediate enum values to a property, it returns only Check and UnCheck value.

1. Run the attached sample
2. Click on 'Button'.
3. Then it returns wrong value.

**Expected behavior**
The assigned values should be returned.

**Screenshots**
![image](https://user-images.githubusercontent.com/72746313/117284421-6ba7b080-ae84-11eb-8a0f-b52748687793.png)

**Version Info**
Project-Reunion NuGet package version - 0.5.0-prerelease
OS version(s) - 19042.928

NuGet package version: 
Project Reunion - 0.5.0-prerelease

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2020 Update (19041)            | Yes   |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |

**Additional context**
Sample : 
[App13.zip](https://github.com/microsoft/ProjectReunion/files/6433937/App13.zip)

**Comment by jonwis** [comment]
@Scottj1s - should this move to the C#/WinRT repo?

**Comment by Scottj1s** [comment]
The problem is with the definition of the enum.  Note that while the [Flags] attribute enables bitwise operations on values of the enum, it does not automatically assign reasonable values for each enumerator (i.e., non-zero powers of 2).  That must be done manually:
    [Flags]
    public enum CheckedState
    {
        Check = 1,
        UnCheck = 2,
        Intermediate = 4
    }

See:
https://docs.microsoft.com/en-us/dotnet/api/system.flagsattribute?view=net-5.0
