### ISSUE TITLE
UIA isn't properly handling display scale value

### ISSUE THREAD

**Issue by dayman40** [microsoft/ProjectReunion#807]
Here are two issues that I found with UIA mixing and matching physical and logical pixels:

	
In CUIAWindow::ElementProviderFromPointImpl, physical screen pixels are passed in, and we then convert those to physical app pixels, but then we pass those physical pixels into our hit-testing stack without converting them to logical pixels. Converting to logical pixels fixes this issue.
	In CUIElement::TransformToWorldSpace, we account for the scale in the case where we've found the root visual in UWP apps, but we've already accounted for the scale at that point, meaning that we've multiplied by the scale twice. Here, we just don't need to account for the scale.

**Comment by riverar** [comment]
@andrewleader Is the milestone correct here?

**Comment by andrewleader** [comment]
Yes, we're aiming at fixing this in a 0.5 servicing update (we've currently just been using 0.5 as the milestone including servicing fixes, if you think we should create separate milestones for each servicing update let us know!)

**Comment by riverar** [comment]
@andrewleader Oh got it. Might be less confusing if the milestone name reflected the actual update version (e.g. 0.5.9). And maybe not have "Q1" designation (which has passed).

**Comment by andrewleader** [comment]
Yeah agreed. We'll try to improve that in the future by looking at what other GitHub repos do and see if there's a best practice. Just for transparency, I don't think we're going to address figuring that out soon (got lots of other higher impact topics to focus on).

**Comment by btueffers** [comment]
Fixed in 0.5.7
