### ISSUE TITLE
Currently WinUI Desktop apps always show focus rects on launch, even if the app was launched via mouse/touch/pen

### ISSUE THREAD

**Issue by dayman40** [microsoft/ProjectReunion#808]
Properly determine on island initialization whether focus rects should initially be shown

Currently WinUI Desktop apps always show focus rects on launch, even if the app was launched via mouse/touch/pen. This is because CXamlIslandRoot always initializes to SetLastInputDeviceType(Keyboard).

The fix includes copying some code from the CoreWindow path, which sends WM_CHANGEUISTATE to get Windows to set the last input type. JupiterWindow then receives WM_UPDATEUISTATE with that information. For Islands, we don't have a window subclass so we can't receive WM_UPDATEUISTATE, but we can send WM_QUERYUISTATE after the WM_CHANGEUISTATE completes to get that state.

**Comment by btueffers** [comment]
Fixed in 0.5.7
