### ISSUE TITLE
Azure pipeline fails on the VSBulid step: Project Reunion requires WinRT.Runtime.dll version 1.2 or greater

### ISSUE THREAD

**Issue by LeftTwixWand** [microsoft/ProjectReunion#826]
**Describe the bug**

So, I have absolutely empty ProjectReunion 0.5.7 project, created with the [ProjectReunion for Visual Studio Extension](https://marketplace.visualstudio.com/items?itemName=ProjectReunion.MicrosoftProjectReunion). 
Steps in my [azure-pipelines.yml](https://github.com/LeftTwixWand/ProjectReunionPipelines/blob/master/azure-pipelines.yml) file:

1. Use NuGet 5.8.0
2. Use latest .NET 5 SDK (Now it's 5.0.203)
3. Use latest .NET 5 Runtime (Now it's 5.0.6)
4. NuGet Restore Command
5. VSBuild

For my local computer build it's enough. But the Azure pipeline has the problem:
**This version of Project Reunion requires WinRT.Runtime.dll version 1.2 or greater.**

A few weeks ago In this issue: [github.com/microsoft/ProjectReunion/issues/741](https://github.com/microsoft/ProjectReunion/issues/741#event-4612335370) I described the same problem with `Microsoft.Windows.SDK.NET.Ref` in the Project Reunion 0.5.5. This was fixed by adding the references the to .csproj file:
```XAML
<ItemGroup>
    <FrameworkReference Update="Microsoft.Windows.SDK.NET.Ref" RuntimeFrameworkVersion="10.0.18362.16" />
    <FrameworkReference Update="Microsoft.Windows.SDK.NET.Ref" TargetingPackVersion="10.0.18362.16" />
</ItemGroup>
```

With the release of .NET 5.0.6 runtime this problem was fixed. But not in the pipelines, as I think.
So, my empty project has the build error, but if I'm bringing back these references to my .csproj file, the build is working fine:
```XAML
<ItemGroup>
    <FrameworkReference Update="Microsoft.Windows.SDK.NET.Ref" RuntimeFrameworkVersion="10.0.18362.16" />
    <FrameworkReference Update="Microsoft.Windows.SDK.NET.Ref" TargetingPackVersion="10.0.18362.16" />
</ItemGroup>
``` 

There are two pipelines build in my [test repository](https://github.com/LeftTwixWand/ProjectReunionPipelines.git) and only one difference - is that one commit has the `Microsoft.Windows.SDK.NET.Ref`:
[Failed](https://github.com/LeftTwixWand/ProjectReunionPipelines/runs/2584756570) - Without references
[Successful](https://github.com/LeftTwixWand/ProjectReunionPipelines/runs/2585030440) - With references

**Steps to reproduce the problem:**
1. Create empty ProjectReunion solution
2. Set AssetTargetFallback for .wapproj file for successful nuget restore command ([Sample](https://github.com/LeftTwixWand/ProjectReunionPipelines/commit/0baa7a7c335e7e317ca02caf032cf4846d0c1c5a))
2. Set up a pipeline, like this one: [azure-pipelines.yml](https://github.com/LeftTwixWand/ProjectReunionPipelines/blob/master/azure-pipelines.yml)

Or just check my sample solution: [github.com/LeftTwixWand/ProjectReunionPipelines](https://github.com/LeftTwixWand/ProjectReunionPipelines.git)

**Version Info**
.NET Runtime - 5.0.6
.NET SDK - 5.0.203

NuGet package version: 
Microsoft.ProjectReunion - 0.5.7

**Comment by BenJKuhn** [comment]
This is by design, and will resolve itself once .NET updates contain the latest C# WinRT, which will happen in the coming weeks. In the meantime you can either manually update targets to use the latest version per the release notes, or stay on the previous version   of Project Reunion until .NET is updated. Note that due to timing issues, the error message in Project Reunion is inaccurate, adn the version of .NET containing the updated C# WinRT Runtime will be 5.0.7, rather than 5.0.6.
