### ISSUE TITLE
The UWP projects templates missing in Visual Studio with Project Reunion Extension 0.57

### ISSUE THREAD

**Issue by sonnemaf** [microsoft/ProjectReunion#828]
**Describe the bug**
The C# UWP Project templates are missing in Visual Studio after installing version 0.5.7 of the Project Reunion Extension. I can only create ```WinUI 3 in Desktop``` projects.

**Steps to reproduce the bug**

1. Install the Project Reunion Extension from https://marketplace.visualstudio.com/items?itemName=ProjectReunion.MicrosoftProjectReunion
2. Start Visual Studio 2019 Preview (I use Version 16.10.0 Preview 3.0)
3. Create a new Project
4. Type ```WinUI``` in the 'Search for template' textbox. 
5. You only get  ```WinUI 3 in Desktop``` projects.

**Expected behavior**
A list of projects which also contain UWP projects

**Screenshots**
![image](https://user-images.githubusercontent.com/9335559/118450910-fd20e900-b6f4-11eb-9f55-c9cd53b577a7.png)

**Version Info**
[Version 0.5.7](https://marketplace.visualstudio.com/items?itemName=ProjectReunion.MicrosoftProjectReunion)

**Comment by mrlacey** [comment]
These were deliberately [removed in March because they are "not supported in release"](https://github.com/microsoft/ProjectReunion/pull/591) and there are "runtime restrictions preventing their functionality"

This was also before the 0.5.5 release and so I do not believe that the removal of UWP templates was in 0.5.7. (I even remember them not being in 0.5.6)

Removing something that isn't supported and may not work makes sense, but raises the question: **How can people test WinUI3 with UWP?**

**Comment by mrlacey** [comment]
Just checked the packages. 
UWP project templates haven't been available since **before** the ProjectReunion v0.5.0 package was released

**Comment by roxk** [comment]
To develop for WinUI3 UWP, I'm using the 0.5-prerelease version of both the nuget package and extension, as described [here](https://docs.microsoft.com/en-us/windows/apps/winui/winui3/get-started-winui3-for-uwp). The blank app template is still available in this extension.

For upgrading, AFAIK there is no documentation for upgrading from preview 4 to 0.5 for UWP, the [only one](https://docs.microsoft.com/en-us/windows/apps/project-reunion/update-existing-projects-to-the-latest-release#update-from-winui-3-preview-4) seems to be for desktop only. Regardless, upgrading was relatively painless, just make sure all project reunion related packages in the project file are identical to the one in a blank app created using the extension.

**Comment by andrewleader** [comment]
Thanks roxk for helping answer this! As roxk said, only the previews contain UWP right now, you can use the previous prerelease as described.
