### ISSUE TITLE
Title: Border control should not get the keyboard focus

### ISSUE THREAD

**Issue by jeganraj-m** [microsoft/ProjectReunion#834]
**Describe the bug**
Border control gets the focus in click, and it should not get the focus.

**Steps to reproduce the bug**
Add Border and TextBox control, select TextBox then Border. You could see focus lost in TextBox.

**Expected behavior**
Border control should not have focus

**Screenshots**
![image](https://user-images.githubusercontent.com/74640452/118654106-d56d7600-b805-11eb-8994-fddbcea988f8.png)

![image](https://user-images.githubusercontent.com/74640452/118654161-e3bb9200-b805-11eb-9966-93178763ef21.png)

**Code**

`<Grid x:Name="rootGrid">
    <Grid.RowDefinitions>
        <RowDefinition Height="Auto" />
        <RowDefinition Height="Auto" />
        <RowDefinition Height="Auto" />
    </Grid.RowDefinitions>
    <StackPanel Grid.Row="1"
                Orientation="Horizontal">
        <Border Height="50"
                Width="200"
                Background="Yellow" />
        <TextBox Height="50"
                 Width="200" />
    </StackPanel>
    <TextBlock x:Name="focusElement"
               Grid.Row="3"
               Width="300" />
    <Button Grid.Row="4"
            Click="Button_Click"
            Content="Current focus element"
            AllowFocusOnInteraction="False" />
</Grid>`

private void Button_Click(object sender, RoutedEventArgs e)
        {
            focusElement.Text = (FocusManager.GetFocusedElement(rootGrid.XamlRoot).ToString());
        }

**Version Info**
Project-Reunion NuGet package version -  0.5.6
OS version - 20H2

NuGet package version: 
Microsoft.ProjectReunion  -  Version="0.5.6"
Microsoft.ProjectReunion.Foundation -  Version="0.5.6"
Microsoft.ProjectReunion.WinUI -  Version="0.5.6"

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| 20H2 19042.985             |  Yes  |
| Insider Build (xxxxx)              |    |
| May 2020 Update (19041)            |   |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |

**Comment by Jaiganeshkumaran** [comment]
@jeganraj-m This issue isn't really Reunion related, please move it to https://github.com/microsoft/microsoft-ui-xaml

**Comment by andrewleader** [comment]
Closing this since new issue has been created on XAML already, thanks!
