### ISSUE TITLE
Crash on startup of WinUI3 C# Project - Basic App Instructions - COMException: Class not registered (0x80040154 (REGDB_E_CLASSNOTREG))

### ISSUE THREAD

**Issue by ivberg** [microsoft/ProjectReunion#848]
**Describe the bug**

I followed basic WinUI3 instructions with all the latest & greatest stable tooling (to my knowledge)
https://docs.microsoft.com/en-us/windows/apps/winui/winui3/
https://docs.microsoft.com/en-us/windows/apps/winui/winui3/desktop-build-basic-winui3-app

However, the app crashes on startup - Crash on startup of WinUI3 C# Project - Basic App Instructions - COMException: Class not registered (0x80040154 (REGDB_E_CLASSNOTREG))

Also the app F5/Debug didn't immediately work. I had to build the project.

[For bugs related to WinUI, please open a bug on the WinUI3 repository: https://github.com/microsoft/microsoft-ui-xaml]
Please clarify this. I don't understand the two repos. The other repo bug report has similar instructions pointing to this repo to file bugs on WinUI3. So not sure which one to use

**Steps to reproduce the bug**

1. https://docs.microsoft.com/en-us/windows/apps/winui/winui3/desktop-build-basic-winui3-app
2. Verify all steps followed
3. Hand-added SDK refs per https://docs.microsoft.com/en-us/windows/apps/project-reunion/#net-sdk-references
4. Build/Run/Crash

**Expected behavior**
Example template app doesn't crash

**Screenshots**
System.Reflection.TargetInvocationException
  HResult=0x80131604
  Message=Exception has been thrown by the target of an invocation.
  Source=System.Private.CoreLib
  StackTrace:
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean wrapExceptions, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& hasNoDefaultCtor)
   at System.RuntimeType.CreateInstanceDefaultCtorSlow(Boolean publicOnly, Boolean wrapExceptions, Boolean fillCache)
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, Boolean wrapExceptions)
   at System.Activator.CreateInstance[T]()
   at WinRT.WeakLazy`1.get_Value()
   at Microsoft.UI.Xaml.Application._IApplicationStatics.get_Instance()
   at Microsoft.UI.Xaml.Application.Start(ApplicationInitializationCallback callback)
   at AppUI.Program.Main(String[] args) in C:\src\App\AppUI\AppUI\obj\x86\Debug\net5.0-windows10.0.19041.0\App.g.i.cs:line 26

  This exception was originally thrown at this call stack:
    System.Runtime.InteropServices.Marshal.ThrowExceptionForHR(int)
    WinRT.BaseActivationFactory.BaseActivationFactory(string, string)
    Microsoft.UI.Xaml.Application._IApplicationStatics._IApplicationStatics()

Inner Exception 1:
COMException: Class not registered (0x80040154 (REGDB_E_CLASSNOTREG))

**Version Info**
Project Reunion 0.5
    <PackageReference Include="Microsoft.ProjectReunion" Version="0.5.7" />
    <PackageReference Include="Microsoft.ProjectReunion.Foundation" Version="0.5.7" />
    <PackageReference Include="Microsoft.ProjectReunion.WinUI" Version="0.5.7" />

      <FrameworkReference Update="Microsoft.Windows.SDK.NET.Ref" RuntimeFrameworkVersion="10.0.18362.16" />
      <FrameworkReference Update="Microsoft.Windows.SDK.NET.Ref" TargetingPackVersion="10.0.18362.16" />

>dotnet --list-sdks
5.0.203 [C:\Program Files\dotnet\sdk]

Latest production VS (which is listed as supported): 16.9.6

NuGet package version: 

See above

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (21387)           | Yes - 21387.co_release_fun.210518-1507
| May 2020 Update (19041)      
| November 2019 Update (18363)  
| May 2019 Update (18362)    
| October 2018 Update (17763)   

**Additional context**
Filed the same bug on other repo has it's not clear which repo this bug should go
https://github.com/microsoft/microsoft-ui-xaml/issues/5054

**Comment by BenJKuhn** [comment]
Can you confirm that you're starting the app using the app project or the packaging project? If not running the packaging project, this is expected, since the package provides the missing registrations.

**Comment by ivberg** [comment]
I am using the app project. This is not expected for me at all and this isn't in the docs. How are devs supposed to F5/Debug and rapid iterate on code if they have to package/deploy the app every time?

Specifically
https://docs.microsoft.com/en-us/windows/apps/winui/winui3/get-started-winui3-for-desktop
Create a WinUI 3 desktop app with C# and .NET 5
9. Build and run your solution to confirm that the app runs without errors.  <- This doesn't mention anything about using the packaging project or lack of F5 support.

**Comment by nickrandolph** [comment]
Pains of early adoption + docs sometimes miss things. Currently the packaging project has to be the startup project for debugging. I'd imagine that as reunion delivers the ability to run unpackaged, the need for a separate packaging project might disappear completely (similar to UWP in that regard).

Also, this is sort of covered in the docs you linked:
![image](https://user-images.githubusercontent.com/1614057/119060352-5babd700-ba15-11eb-8cc2-8502e2408015.png)

Please feel free to mark this issue closed once you've verified the app runs when the packaging project is set as startup.

**Comment by ivberg** [comment]
I guess what happened is either I switched away the default project, or I added this to an existing solution with a default project (which I did) and it didn't set the package as the default.  I found it counterintuitive because normally you F5/Debug the project and then deploy later. Apparently this is not yet supported.

It does work now although it seems like a re-deploy is needed with each iterative change - yikes!

**Comment by ToolmakerSteve** [comment]
> Can you confirm that you're starting the app using the app project or the **packaging project**? If not running the packaging project, this is expected, since the package provides the missing registrations.

Thank you for this vital bit of information. That AFAIK is missing from Microsoft's docs.

-------------------------------------
DETAILS (in case anyone else has similar situation):

**Updating a .Net Framework project to WindowsAppSDK.**

I had copied first section of .csproj from sample project made by template "Blank App, Packaged (WinUI 3 in Desktop)", **but had not included files / directives related to packaging**.

And was using our custom app entry point; not running WinUI 3 initialization.  
We don't use WinUI 3-specific APIs -- we adapted ancient code, to grab the application's MainWindow.

Got almost everything working in .Net 8, including using many Maui Essentials.  
Finally hit an Essentials feature (GeoLocation) that triggered that ComException / Class not registered.

When I added the startup lines from sample project's auto-generated App.g.i.cs:
```cs
static void Main(string[] args)
{
    global::WinRT.ComWrappersSupport.InitializeComWrappers();
    global::Microsoft.UI.Xaml.Application.Start((p) => {
        var context = new global::Microsoft.UI.Dispatching.DispatcherQueueSynchronizationContext(global::Microsoft.UI.Dispatching.DispatcherQueue.GetForCurrentThread());
        global::System.Threading.SynchronizationContext.SetSynchronizationContext(context);
        new App();
    });
}
```

I got that exception on line `global::Microsoft.UI.Xaml.Application.Start`.
