### ISSUE TITLE
Window.Current.CoreWindow.GetAsyncKeyState(VirtualKey.Control) - sometimes incorrect while handling mouse-wheel

### ISSUE THREAD

**Issue by jtorjo** [microsoft/ProjectReunion#852]
**Describe the bug**

`Window.Current.CoreWindow.GetAsyncKeyState(VirtualKey.Control)` doesn't always give accurate results when the CTRL hotkey is pressed.

I've encountered this while processing mouse-wheel, but I'm almost certain it happens on other occasions as well.

**Steps to reproduce the bug**

	ctrl.PointerWheelChanged += ctrl_PointerWheelChanged;
	private void ctrl_PointerWheelChanged(object sender, PointerRoutedEventArgs e)
	{
		var ctrl_key_pressed = Window.Current.CoreWindow.GetAsyncKeyState(VirtualKey.Control) == CoreVirtualKeyStates.Down;
		Console.WriteLine("ctrl-pressed=" + ctrl_key_presed);
	}

1. Run this code. 
2.  Press CTRL, and keep it pressed
3.  Keep using the scroll wheel, so you constantly receive events
4.  Every one in 15-20 events will show `ctrl-pressed=false`

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| May 2020 Update (19041)            | Yes |
| November 2019 Update (18363)       | Yes   |

**Comment by kevinguo305** [comment]
Hi @jtorjo 

Can you also create an issue in our feedback hub and share the link please? Be sure to use the ‘reproduce my problem’ option to collect data about what you’re seeing.

Thanks for filing this issue!
