### ISSUE TITLE
Where is Project Reunion 0.8?

### ISSUE THREAD

**Issue by riverar** [microsoft/ProjectReunion#859]
Am I missing something?

From [Windows Developer Blog](https://blogs.windows.com/windowsdeveloper/2021/05/25/the-windows-developers-guide-to-microsoft-build-2021/) (via Microsoft Build):

> With the Project Reunion 0.8 preview you can create and modernize your Windows apps seamlessly for both client and cloud endpoints. To get started, simply install the Project Reunion Visual Studio template and you’ll have access to the project templates and APIs you need.  [...] You can learn more about Project Reunion 0.8 preview and provide feedback in our GitHub. We’re constantly evaluating feedback and if there’s something missing, we want to know! 

From the Microsoft Build Book of News, [6.1.3. Project Reunion 0.8 Preview Release](https://news.microsoft.com/build-2021-book-of-news/#a-613-project-reunion-08-preview-release):

> Project Reunion 0.8 Preview SDK is a new in-market update that allows developers to build and ship Windows apps faster without waiting for the Windows operating system (OS) to update. (Project Reunion 0.5 was released in March.)

**Comment by andrewleader** [comment]
We are working on getting the 0.8 Preview released as soon as possible. Stay tuned to the Discussions where we'll announce when it's live!

**Comment by andrewleader** [comment]
0.8 Preview is now available! https://docs.microsoft.com/windows/apps/project-reunion/preview-channel
