### ISSUE TITLE
When will .Net 5 get UWP?

### ISSUE THREAD

**Issue by Gavin-Williams** [microsoft/ProjectReunion#86]
When I create a UWP-WinUI app it's still using Microsoft.NetCore.UWP and there are no properties displayed. I assume this is the same .net core that UWP has been using.

When I create a Desktop-WinUI app it's using the the .Net 5 preview.

Are we waiting for something? Or have I misunderstood what .Net 5 represents? Is UWP getting .Net 5 or not?

**Comment by Felix-Dev** [comment]
Seems like a duplicate of https://github.com/microsoft/ProjectReunion/issues/17 which also covers the .NET 5 + UWP topic.

**Comment by Gavin-Williams** [comment]
@Felix-Dev Thanks for that link, that seems to cover this.

So UWP might get .Net 5 by the end of 2021. 

Yikes, it'll be tough for a lot of people I think to hold out. I will probably just switch to .Net 5 (where a future is guaranteed) and screw the consequences. Yep, I'll lose SharpDX and there's no obvious way to write graphics apps on .Net 5 (except write the entire graphics stack yourself from scratch in C++/WinRT - ROFL) But I can't stick with SharpDX anyway in the long term (as it's unsupported) or UWP past my current project. It just doesn't make sense anymore.

**Comment by jtorjo** [comment]
> It just doesn't make sense anymore.

Did it ever? :)

Basically, it seems MS is incredibly confused about it. What about us, the developers?

Trust me, I feel your pain - the reason I moved to UWP was the need for win2d. So I'm between a nail and a hard place - I can't go back to WPF , and UWP support is pretty much "in the air"

**Comment by sjb-sjb** [comment]
@jtorjo, problem with that is the lack of NET 5 in UWP. There are too many things enabled by NET 5 (like C# 9 and Source Generators) to just do nothing for a few years until Microsoft finally brings NET 5 to UWP.

**Comment by robloo** [comment]
Here is a fun dialog with the latest VS 2019 version. Microsoft is being disingenuous that those using UWP can continue to do so. Things are breaking more and more especially with third party libraries no longer supporting .NET standard 2.x. Meanwhile, WinUI3 itself is still too buggy and missing features (map, inking, media, etc.). What a great situation...

![image](https://user-images.githubusercontent.com/17993847/134435223-ed224d6f-7b7d-4f49-90c9-373a35632bf6.png)

**Comment by jtorjo** [comment]
> What a great situation...

Trust me, I know. 😢 Imagine doing profiling on a 200K LOC app, and MS's profiling is pretty useless, and I can't use any other tools because they don't support UWP. And that's just one of the many many issues I'm facing

**Comment by pubtom** [comment]
If you need .NET>5 in UWP please give a vote on this: https://developercommunity.visualstudio.com/t/Add-NET-678-support-to-UWP/1596483
