### ISSUE TITLE
UWP: Microphone/camera permission dialog opens on the wrong window

### ISSUE THREAD

**Issue by FrayxRulez** [microsoft/ProjectReunion#862]
**Describe the bug**

Currently, the popup to accept access to microphone/camera opens on top of the main window in UWP apps, even if the `MediaCapture` is initialized from a different `CoreWindow`.

**Steps to reproduce the bug**

1. Create a new `ApplicationView`
2. Initialize a `MediaCapture` from the new view thread
3. Notice the dialog opening on the main window instead

**Expected behavior**

Permission dialog opens on the right thread view

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2020 Update (19041)            | Yes   |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |

**Additional context**

Would it make sense to write a proposal to extend `DeviceAccessInformation` functionality to also request the device permisson?
Currently it can be used to check the status, but developers are forced to initialize a (most often dummy) `MediaCapture` instance to properly request the access.

**Comment by andrewleader** [comment]
Hi @FrayxRulez, thanks for filing this. This looks like an OS API issue and not a Reunion API issue, you can file a bug about by using Feedback Hub. You can share your Feedback Hub bug report link here and I can make sure it gets to the right team! Thanks!

**Comment by riverar** [comment]
@andrewleader What category/sub-category do you suggest for this issue?

**Comment by andrewleader** [comment]
They can use `Developer Platform` -> `API Feedback` for this one.

**Comment by jonwis** [comment]
@aklemets, FYI - it looks like `MediaCapture` doesn't have a `...ForWindow` mechanism yet.
