### ISSUE TITLE
Cannot reference Microsoft.Identity.Client within the same project

### ISSUE THREAD

**Issue by pellea** [microsoft/ProjectReunion#879]
**Describe the bug**

Cannot reference Microsoft.Identity.Client within the same project as Project Reunion 0.5.7.
It causes this following exception: 
```
2>C:\Users\adrie\.nuget\packages\microsoft.projectreunion.winui\0.5.7\buildTransitive\Microsoft.UI.Xaml.Markup.Compiler.interop.targets(618,9): 
Xaml Internal Error error WMC9999: Cannot find type System.Windows.DependencyObject in module WindowsBase.dll.
```

**Steps to reproduce the bug**

1.Create a WinUI project with Project Reunion 0.5.7
2. Add package Microsoft.Identity.Client (version: 4.31.0)

**Version Info**

NuGet package version: 

Include="Microsoft.Identity.Client" Version="4.31.0"
Include="Microsoft.ProjectReunion" Version="0.5.7"
Include="Microsoft.ProjectReunion.Foundation" Version="0.5.7"
Include="Microsoft.ProjectReunion.WinUI" Version="0.5.7"

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (21390)              | Yes   |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |

**Additional context**

TargetFramework : net5.0-windows10.0.19041.0
TargetPlatformMinVersion : 10.0.17763.0

**Comment by andrewleader** [comment]
Hi Adrien, thanks for filing this, I've filed an issue on the Identity team tracking this: https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/2673
