### ISSUE TITLE
Question: [Will this support making new apps using WINDOWS FORMS and add UWP like features ]

### ISSUE THREAD

**Issue by fisforfaheem** [microsoft/ProjectReunion#90]
I love making apps through, windows forms .... But i wish it was cross platform and available to android and ios too.

**Comment by jonwis** [comment]
Project Reunion is focusing on Windows first. Let's continue the discussion on WinForms - especially for UWPs - in your #91 .

**Comment by fisforfaheem** [comment]
OK
