### ISSUE TITLE
FileSavePicker Break in WinUI3 Desktop

### ISSUE THREAD

**Issue by Aloento** [microsoft/ProjectReunion#909]
**Describe the bug**

The FileSavePicker and PickSaveFileAsync will crashed even using `InitializeWithWindow()` with any WinUI3 version.

**Steps to reproduce the bug**

1. `git clone git@github.com:Aloento/Waifu2x-Vulkan-Reunion.git`
2. Open `Waifu2x-Vulkan-Reunion.sln`
3. Start and Run Debug
4. Click `Set Export Folder` Button

**Expected behavior**

`There is an unhandled exception at 0x00007FFCFA61B39C (KernelBase.dll) (in Waifu2x-Vulkan-Reunion.exe): 0xC000027B: An internal application exception has occurred. (Parameter: 0x0000021869E6BA10, 0x0000000000000001).`

NuGet package version: 
[Microsoft.ProjectReunion 0.8.0-preview]

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2020 Update (19041)            | Yes   |
| November 2019 Update (18363)       | Yes  |
| May 2019 Update (18362)            | Yes   |
| October 2018 Update (17763)        | Yes   |

**Additional context**

https://github.com/Aloento/Waifu2x-Vulkan-Reunion/blob/621531fa891bb9b8fef02ff0ff3e4d437d86273b/Waifu2x-Vulkan-Reunion/Views/OverviewPage.xaml.cs#L43

**Comment by andrewleader** [comment]
Hi @Aloento, it looks like you aren't specifying any FileTypeChoices, which is required as per the [docs remarks](https://docs.microsoft.com/uwp/api/windows.storage.pickers.filesavepicker?view=winrt-20348#remarks).

**You must use the FileTypeChoices property property to specify one or more file types before you call the PickSaveFileAsync method, or the picker will thrown an exception.**

For example...

```csharp
    // TODO: Initialize with IInitializeWithWindow as you were doing before

    savePicker.SuggestedStartLocation = PickerLocationId.DocumentsLibrary;
    // Dropdown of file types the user can save the file as
    savePicker.FileTypeChoices.Add("Plain Text", new List<string>() { ".txt" });
    // Default file name if the user does not type one in or select a file to replace
    savePicker.SuggestedFileName = "New Document";

    StorageFile file = await savePicker.PickSaveFileAsync();
```

If that doesn't resolve your problem, please reopen! Thanks!

**Comment by riverar** [comment]
@andrewleader Is this being tracked as a bug internally? Everyone hits this at least once and it's pretty silly that it throws.

**Comment by andrewleader** [comment]
I've shared this feedback with the team that owns the file picker APIs. Fully agreed that we at least need better exceptions. The file picker team is currently figuring out the plan forward for file picker APIs including considering some feedback here: #88

**Comment by mdtauk** [comment]
There was a discussion about Reunion bringing in new and better File Picker APIs
https://github.com/microsoft/ProjectReunion/issues/88
