### ISSUE TITLE
APPX0501: App manifest validation error in Visual Studio 16.10 in UWP projects with desktop extension

### ISSUE THREAD

**Issue by soumyamahunt** [microsoft/ProjectReunion#912]
**Describe the bug**

In an UWP app with [desktop extension](https://docs.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-desktop-extension) project if both uwp project and desktop extension project reference a common WinRT component `windows.activatableClass.inProcessServer` is added in `AppxManifest.xml` for both project which causes this validation error.

**Steps to reproduce the bug**

1. Update Visual Studio to 16.10.
2. Create a MSIX packaging project.
3. Create an UWP project and a Console application project and add reference for these two in the packaging project.
4. Create a WinRT component and add reference for it in both UWP and Console application project.
5. Try to deploy the packaging project and see error.

**Expected behavior**

When adding new `windows.activatableClass.inProcessServer`  to manifest only add if no similar entry exists.

**Version Info**

NuGet package version: Not applicable

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2020 Update (19041)            | Yes   |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |

**Comment by soumyamahunt** [comment]
Not sure if this issue belongs here, if not please transfer it to the required repo.

**Comment by andrewleader** [comment]
Hi @soumyamahunt, thanks for filing this! I'm working on finding the right owner for this (you're correct that this is not technically the right repo, but I'll help this get to the right folks regardless 😊)

**Comment by andrewleader** [comment]
The Visual Studio team owns the MSIX packaging project. To submit this bug with all applicable logs, they would like you to open your project in Visual Studio, and go to **Help -> Send Feedback -> Report a Problem**.

I'll close this bug here. Thanks!
