### ISSUE TITLE
CommandLineActivation bug in multi-instance UWP apps

### ISSUE THREAD

**Issue by soumyamahunt** [microsoft/ProjectReunion#913]
**Describe the bug**

Currently CommandLineActivation works differently for multi-instance UWP apps than single-instance UWP apps:

For single instance UWP apps when launching an app from command line with `start /wait alias.exe`, command will complete with 0 exit code as soon as app launched. Optionally UWP apps can use  `CommandLineActivatedEventArgs.Operation.GetDeferral()` to take deferral for extended execution and can set `CommandLineActivatedEventArgs.Operation.ExitCode` before completing deferral to indicate whether command was executed successfully.

But none of the above work if UWP app supports multi-instancing. Command line activation always waits for the process to exit regardless of whether deferral is taken or not, and the exit code is always set to 1 with no way of changing it.

**Steps to reproduce the bug**

1. Create UWP app with command line activation support.
2. Test activation with command `start /wait alias.exe` with both with and without deferral and check exit code.
3. Add multi-instancing support to UWP app and repeat above procedure.

**Expected behavior**

Should have the same behavior as in single-instance UWP app.

**Version Info**

NuGet package version: Not applicable

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2020 Update (19041)            | Yes   |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |

**Additional context**

Git uses command line activation for its editors and checks for exit code to know whether command was executed successfully or not. Since exit code is always 1, UWP apps like [Notepads](https://github.com/JasonStein/Notepads) can't be set as default git editor.

**Comment by andrewleader** [comment]
Hi @soumyamahunt, thanks for reporting this. I've sent this feedback to the team that works on this area inside UWP, but since this feedback is related to OS APIs (and not Project Reunion APIs), I'll close this bug here. I've informed the team to reach out to you if they have any further questions/updates though!

**Comment by soumyamahunt** [comment]
@andrewleader I have reported this bug in feedback hub: https://aka.ms/AAd5f0n, since this seems the recommended platform for reporting UWP API related bugs. I hope the progress is reported in that feedback.
