### ISSUE TITLE
What are people using for crash reporting?

### ISSUE THREAD

**Issue by Marv51** [microsoft/ProjectReunion#920]
Hi, 
Before WinUI 3 I was using [AppCenter](https://appcenter.ms/) to gather crash reports and get some basic analytic insights into the usage of my app.

AppCenter does not work with [WinUI 3](https://github.com/microsoft/appcenter-sdk-dotnet/issues/1523). 

So, any recommendations? What are people using for this? 

(My app is sideloaded, so the store infrastructure is not a replacement)

**Comment by andrewleader** [comment]
Transferring this to a discussion (excellent question/discussion!)
