### ISSUE TITLE
[0.8 Preview] Cannot build class library using Project Reunion, AnyCPU error

### ISSUE THREAD

**Issue by andrewleader** [microsoft/ProjectReunion#922]
**Describe the bug**
This is a **known issue** that affects the **0.8 Preview**. If you use a class library that uses Project Reunion and are using the 0.8 Preview, attempting to build your class library will fail with the error seen below. The stable 0.5 release is not affected by this issue.

```
This version of WinUI does not support AnyCPU. Either set Platform or PlatformTarget to one of the following: x86, x64, or arm64.	
```

**Workaround**
Add `<Platforms>x86;x64;arm64</Platforms>` to your class library project.

Full example...

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net5.0-windows10.0.19041.0</TargetFramework>
    <TargetPlatformMinVersion>10.0.17763.0</TargetPlatformMinVersion>
    <RootNamespace>ClassLibrary1</RootNamespace>
    <Platforms>x86;x64;arm64</Platforms>
    <RuntimeIdentifiers>win10-x86;win10-x64;win10-arm64</RuntimeIdentifiers>
  </PropertyGroup>

  <ItemGroup>
      <PackageReference Include="Microsoft.ProjectReunion" Version="0.8.0-preview" />
      <PackageReference Include="Microsoft.ProjectReunion.Foundation" Version="0.8.0-preview" />
      <PackageReference Include="Microsoft.ProjectReunion.WinUI" Version="0.8.0-preview" />
  </ItemGroup>
</Project>
```

**Steps to reproduce the bug**

1. Create a 0.8 Preview WinUI 3 desktop app
2. Add a 0.8 Preview WinUI 3 class library
3. Reference the class library from the desktop app
4. Attempt to build the app

**Expected behavior**
App should build and run.

**Version Info**

NuGet package version: 
`0.8.0-preview`

**Comment by huichen123** [comment]
In 0.8 GA, WinUI allows AnyCPU.

**Comment by gmurray81** [comment]
Hi,
I'm not sure if this fixes the problem? 
All that has done is to change the project template to not include the AnyCPU platform.
But we need to be able to compile _as_ AnyCPU rather than a specific platform, for a class library.

**Comment by huichen123** [comment]
@gmurray81 we didn't take the approach in previously linked PR for 0.8 GA.
