### ISSUE TITLE
DLLs not copied to Project Reunion Package Solution

### ISSUE THREAD

**Issue by nlogozzo** [microsoft/ProjectReunion#930]
Hi,
This issue is still a thing: https://github.com/microsoft/vcpkg/issues/16184
It's preventing most WinUI 3 developers using C++ and vcpkg from testing, developing, and distributing their apps.
If anyone has come up with a solution to this issue please share.

**Comment by andrewleader** [comment]
Thanks @nlogozzo, the original issue you have is still the correct primary issue to track. We've pinged that team to make sure they know people are blocked by this issue. I'll close this issue. Thanks!
